// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/purego-cef/internal/ports/in"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResponse creates a new instance of MockResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResponse {
	mock := &MockResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResponse is an autogenerated mock type for the Response type
type MockResponse struct {
	mock.Mock
}

type MockResponse_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResponse) EXPECT() *MockResponse_Expecter {
	return &MockResponse_Expecter{mock: &_m.Mock}
}

// GetCharset provides a mock function for the type MockResponse
func (_mock *MockResponse) GetCharset() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCharset")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockResponse_GetCharset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCharset'
type MockResponse_GetCharset_Call struct {
	*mock.Call
}

// GetCharset is a helper method to define mock.On call
func (_e *MockResponse_Expecter) GetCharset() *MockResponse_GetCharset_Call {
	return &MockResponse_GetCharset_Call{Call: _e.mock.On("GetCharset")}
}

func (_c *MockResponse_GetCharset_Call) Run(run func()) *MockResponse_GetCharset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponse_GetCharset_Call) Return(s string) *MockResponse_GetCharset_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockResponse_GetCharset_Call) RunAndReturn(run func() string) *MockResponse_GetCharset_Call {
	_c.Call.Return(run)
	return _c
}

// GetError provides a mock function for the type MockResponse
func (_mock *MockResponse) GetError() in.Errorcode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetError")
	}

	var r0 in.Errorcode
	if returnFunc, ok := ret.Get(0).(func() in.Errorcode); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(in.Errorcode)
	}
	return r0
}

// MockResponse_GetError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetError'
type MockResponse_GetError_Call struct {
	*mock.Call
}

// GetError is a helper method to define mock.On call
func (_e *MockResponse_Expecter) GetError() *MockResponse_GetError_Call {
	return &MockResponse_GetError_Call{Call: _e.mock.On("GetError")}
}

func (_c *MockResponse_GetError_Call) Run(run func()) *MockResponse_GetError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponse_GetError_Call) Return(v in.Errorcode) *MockResponse_GetError_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockResponse_GetError_Call) RunAndReturn(run func() in.Errorcode) *MockResponse_GetError_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeaderByName provides a mock function for the type MockResponse
func (_mock *MockResponse) GetHeaderByName(name string) string {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetHeaderByName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockResponse_GetHeaderByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeaderByName'
type MockResponse_GetHeaderByName_Call struct {
	*mock.Call
}

// GetHeaderByName is a helper method to define mock.On call
//   - name string
func (_e *MockResponse_Expecter) GetHeaderByName(name interface{}) *MockResponse_GetHeaderByName_Call {
	return &MockResponse_GetHeaderByName_Call{Call: _e.mock.On("GetHeaderByName", name)}
}

func (_c *MockResponse_GetHeaderByName_Call) Run(run func(name string)) *MockResponse_GetHeaderByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponse_GetHeaderByName_Call) Return(s string) *MockResponse_GetHeaderByName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockResponse_GetHeaderByName_Call) RunAndReturn(run func(name string) string) *MockResponse_GetHeaderByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeaderMap provides a mock function for the type MockResponse
func (_mock *MockResponse) GetHeaderMap(headermap in.StringMultimap) {
	_mock.Called(headermap)
	return
}

// MockResponse_GetHeaderMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeaderMap'
type MockResponse_GetHeaderMap_Call struct {
	*mock.Call
}

// GetHeaderMap is a helper method to define mock.On call
//   - headermap in.StringMultimap
func (_e *MockResponse_Expecter) GetHeaderMap(headermap interface{}) *MockResponse_GetHeaderMap_Call {
	return &MockResponse_GetHeaderMap_Call{Call: _e.mock.On("GetHeaderMap", headermap)}
}

func (_c *MockResponse_GetHeaderMap_Call) Run(run func(headermap in.StringMultimap)) *MockResponse_GetHeaderMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.StringMultimap
		if args[0] != nil {
			arg0 = args[0].(in.StringMultimap)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponse_GetHeaderMap_Call) Return() *MockResponse_GetHeaderMap_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponse_GetHeaderMap_Call) RunAndReturn(run func(headermap in.StringMultimap)) *MockResponse_GetHeaderMap_Call {
	_c.Run(run)
	return _c
}

// GetMimeType provides a mock function for the type MockResponse
func (_mock *MockResponse) GetMimeType() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMimeType")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockResponse_GetMimeType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMimeType'
type MockResponse_GetMimeType_Call struct {
	*mock.Call
}

// GetMimeType is a helper method to define mock.On call
func (_e *MockResponse_Expecter) GetMimeType() *MockResponse_GetMimeType_Call {
	return &MockResponse_GetMimeType_Call{Call: _e.mock.On("GetMimeType")}
}

func (_c *MockResponse_GetMimeType_Call) Run(run func()) *MockResponse_GetMimeType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponse_GetMimeType_Call) Return(s string) *MockResponse_GetMimeType_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockResponse_GetMimeType_Call) RunAndReturn(run func() string) *MockResponse_GetMimeType_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockResponse
func (_mock *MockResponse) GetStatus() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockResponse_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockResponse_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
func (_e *MockResponse_Expecter) GetStatus() *MockResponse_GetStatus_Call {
	return &MockResponse_GetStatus_Call{Call: _e.mock.On("GetStatus")}
}

func (_c *MockResponse_GetStatus_Call) Run(run func()) *MockResponse_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponse_GetStatus_Call) Return(n int32) *MockResponse_GetStatus_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockResponse_GetStatus_Call) RunAndReturn(run func() int32) *MockResponse_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusText provides a mock function for the type MockResponse
func (_mock *MockResponse) GetStatusText() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatusText")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockResponse_GetStatusText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusText'
type MockResponse_GetStatusText_Call struct {
	*mock.Call
}

// GetStatusText is a helper method to define mock.On call
func (_e *MockResponse_Expecter) GetStatusText() *MockResponse_GetStatusText_Call {
	return &MockResponse_GetStatusText_Call{Call: _e.mock.On("GetStatusText")}
}

func (_c *MockResponse_GetStatusText_Call) Run(run func()) *MockResponse_GetStatusText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponse_GetStatusText_Call) Return(s string) *MockResponse_GetStatusText_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockResponse_GetStatusText_Call) RunAndReturn(run func() string) *MockResponse_GetStatusText_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function for the type MockResponse
func (_mock *MockResponse) GetURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockResponse_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockResponse_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
func (_e *MockResponse_Expecter) GetURL() *MockResponse_GetURL_Call {
	return &MockResponse_GetURL_Call{Call: _e.mock.On("GetURL")}
}

func (_c *MockResponse_GetURL_Call) Run(run func()) *MockResponse_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponse_GetURL_Call) Return(s string) *MockResponse_GetURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockResponse_GetURL_Call) RunAndReturn(run func() string) *MockResponse_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// IsReadOnly provides a mock function for the type MockResponse
func (_mock *MockResponse) IsReadOnly() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsReadOnly")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockResponse_IsReadOnly_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsReadOnly'
type MockResponse_IsReadOnly_Call struct {
	*mock.Call
}

// IsReadOnly is a helper method to define mock.On call
func (_e *MockResponse_Expecter) IsReadOnly() *MockResponse_IsReadOnly_Call {
	return &MockResponse_IsReadOnly_Call{Call: _e.mock.On("IsReadOnly")}
}

func (_c *MockResponse_IsReadOnly_Call) Run(run func()) *MockResponse_IsReadOnly_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponse_IsReadOnly_Call) Return(b bool) *MockResponse_IsReadOnly_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockResponse_IsReadOnly_Call) RunAndReturn(run func() bool) *MockResponse_IsReadOnly_Call {
	_c.Call.Return(run)
	return _c
}

// SetCharset provides a mock function for the type MockResponse
func (_mock *MockResponse) SetCharset(charset string) {
	_mock.Called(charset)
	return
}

// MockResponse_SetCharset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCharset'
type MockResponse_SetCharset_Call struct {
	*mock.Call
}

// SetCharset is a helper method to define mock.On call
//   - charset string
func (_e *MockResponse_Expecter) SetCharset(charset interface{}) *MockResponse_SetCharset_Call {
	return &MockResponse_SetCharset_Call{Call: _e.mock.On("SetCharset", charset)}
}

func (_c *MockResponse_SetCharset_Call) Run(run func(charset string)) *MockResponse_SetCharset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponse_SetCharset_Call) Return() *MockResponse_SetCharset_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponse_SetCharset_Call) RunAndReturn(run func(charset string)) *MockResponse_SetCharset_Call {
	_c.Run(run)
	return _c
}

// SetError provides a mock function for the type MockResponse
func (_mock *MockResponse) SetError(error in.Errorcode) {
	_mock.Called(error)
	return
}

// MockResponse_SetError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetError'
type MockResponse_SetError_Call struct {
	*mock.Call
}

// SetError is a helper method to define mock.On call
//   - error in.Errorcode
func (_e *MockResponse_Expecter) SetError(error interface{}) *MockResponse_SetError_Call {
	return &MockResponse_SetError_Call{Call: _e.mock.On("SetError", error)}
}

func (_c *MockResponse_SetError_Call) Run(run func(error in.Errorcode)) *MockResponse_SetError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.Errorcode
		if args[0] != nil {
			arg0 = args[0].(in.Errorcode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponse_SetError_Call) Return() *MockResponse_SetError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponse_SetError_Call) RunAndReturn(run func(error in.Errorcode)) *MockResponse_SetError_Call {
	_c.Run(run)
	return _c
}

// SetHeaderByName provides a mock function for the type MockResponse
func (_mock *MockResponse) SetHeaderByName(name string, value string, overwrite int32) {
	_mock.Called(name, value, overwrite)
	return
}

// MockResponse_SetHeaderByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeaderByName'
type MockResponse_SetHeaderByName_Call struct {
	*mock.Call
}

// SetHeaderByName is a helper method to define mock.On call
//   - name string
//   - value string
//   - overwrite int32
func (_e *MockResponse_Expecter) SetHeaderByName(name interface{}, value interface{}, overwrite interface{}) *MockResponse_SetHeaderByName_Call {
	return &MockResponse_SetHeaderByName_Call{Call: _e.mock.On("SetHeaderByName", name, value, overwrite)}
}

func (_c *MockResponse_SetHeaderByName_Call) Run(run func(name string, value string, overwrite int32)) *MockResponse_SetHeaderByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResponse_SetHeaderByName_Call) Return() *MockResponse_SetHeaderByName_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponse_SetHeaderByName_Call) RunAndReturn(run func(name string, value string, overwrite int32)) *MockResponse_SetHeaderByName_Call {
	_c.Run(run)
	return _c
}

// SetHeaderMap provides a mock function for the type MockResponse
func (_mock *MockResponse) SetHeaderMap(headermap in.StringMultimap) {
	_mock.Called(headermap)
	return
}

// MockResponse_SetHeaderMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeaderMap'
type MockResponse_SetHeaderMap_Call struct {
	*mock.Call
}

// SetHeaderMap is a helper method to define mock.On call
//   - headermap in.StringMultimap
func (_e *MockResponse_Expecter) SetHeaderMap(headermap interface{}) *MockResponse_SetHeaderMap_Call {
	return &MockResponse_SetHeaderMap_Call{Call: _e.mock.On("SetHeaderMap", headermap)}
}

func (_c *MockResponse_SetHeaderMap_Call) Run(run func(headermap in.StringMultimap)) *MockResponse_SetHeaderMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.StringMultimap
		if args[0] != nil {
			arg0 = args[0].(in.StringMultimap)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponse_SetHeaderMap_Call) Return() *MockResponse_SetHeaderMap_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponse_SetHeaderMap_Call) RunAndReturn(run func(headermap in.StringMultimap)) *MockResponse_SetHeaderMap_Call {
	_c.Run(run)
	return _c
}

// SetMimeType provides a mock function for the type MockResponse
func (_mock *MockResponse) SetMimeType(mimetype string) {
	_mock.Called(mimetype)
	return
}

// MockResponse_SetMimeType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMimeType'
type MockResponse_SetMimeType_Call struct {
	*mock.Call
}

// SetMimeType is a helper method to define mock.On call
//   - mimetype string
func (_e *MockResponse_Expecter) SetMimeType(mimetype interface{}) *MockResponse_SetMimeType_Call {
	return &MockResponse_SetMimeType_Call{Call: _e.mock.On("SetMimeType", mimetype)}
}

func (_c *MockResponse_SetMimeType_Call) Run(run func(mimetype string)) *MockResponse_SetMimeType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponse_SetMimeType_Call) Return() *MockResponse_SetMimeType_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponse_SetMimeType_Call) RunAndReturn(run func(mimetype string)) *MockResponse_SetMimeType_Call {
	_c.Run(run)
	return _c
}

// SetStatus provides a mock function for the type MockResponse
func (_mock *MockResponse) SetStatus(status int32) {
	_mock.Called(status)
	return
}

// MockResponse_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockResponse_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - status int32
func (_e *MockResponse_Expecter) SetStatus(status interface{}) *MockResponse_SetStatus_Call {
	return &MockResponse_SetStatus_Call{Call: _e.mock.On("SetStatus", status)}
}

func (_c *MockResponse_SetStatus_Call) Run(run func(status int32)) *MockResponse_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponse_SetStatus_Call) Return() *MockResponse_SetStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponse_SetStatus_Call) RunAndReturn(run func(status int32)) *MockResponse_SetStatus_Call {
	_c.Run(run)
	return _c
}

// SetStatusText provides a mock function for the type MockResponse
func (_mock *MockResponse) SetStatusText(statustext string) {
	_mock.Called(statustext)
	return
}

// MockResponse_SetStatusText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusText'
type MockResponse_SetStatusText_Call struct {
	*mock.Call
}

// SetStatusText is a helper method to define mock.On call
//   - statustext string
func (_e *MockResponse_Expecter) SetStatusText(statustext interface{}) *MockResponse_SetStatusText_Call {
	return &MockResponse_SetStatusText_Call{Call: _e.mock.On("SetStatusText", statustext)}
}

func (_c *MockResponse_SetStatusText_Call) Run(run func(statustext string)) *MockResponse_SetStatusText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponse_SetStatusText_Call) Return() *MockResponse_SetStatusText_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponse_SetStatusText_Call) RunAndReturn(run func(statustext string)) *MockResponse_SetStatusText_Call {
	_c.Run(run)
	return _c
}

// SetURL provides a mock function for the type MockResponse
func (_mock *MockResponse) SetURL(uRL string) {
	_mock.Called(uRL)
	return
}

// MockResponse_SetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetURL'
type MockResponse_SetURL_Call struct {
	*mock.Call
}

// SetURL is a helper method to define mock.On call
//   - uRL string
func (_e *MockResponse_Expecter) SetURL(uRL interface{}) *MockResponse_SetURL_Call {
	return &MockResponse_SetURL_Call{Call: _e.mock.On("SetURL", uRL)}
}

func (_c *MockResponse_SetURL_Call) Run(run func(uRL string)) *MockResponse_SetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponse_SetURL_Call) Return() *MockResponse_SetURL_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponse_SetURL_Call) RunAndReturn(run func(uRL string)) *MockResponse_SetURL_Call {
	_c.Run(run)
	return _c
}
