// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/purego-cef/internal/ports/in"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRequestContext creates a new instance of MockRequestContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestContext {
	mock := &MockRequestContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRequestContext is an autogenerated mock type for the RequestContext type
type MockRequestContext struct {
	mock.Mock
}

type MockRequestContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestContext) EXPECT() *MockRequestContext_Expecter {
	return &MockRequestContext_Expecter{mock: &_m.Mock}
}

// AddSettingObserver provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) AddSettingObserver(observer in.SettingObserver) in.Registration {
	ret := _mock.Called(observer)

	if len(ret) == 0 {
		panic("no return value specified for AddSettingObserver")
	}

	var r0 in.Registration
	if returnFunc, ok := ret.Get(0).(func(in.SettingObserver) in.Registration); ok {
		r0 = returnFunc(observer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(in.Registration)
		}
	}
	return r0
}

// MockRequestContext_AddSettingObserver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSettingObserver'
type MockRequestContext_AddSettingObserver_Call struct {
	*mock.Call
}

// AddSettingObserver is a helper method to define mock.On call
//   - observer in.SettingObserver
func (_e *MockRequestContext_Expecter) AddSettingObserver(observer any) *MockRequestContext_AddSettingObserver_Call {
	return &MockRequestContext_AddSettingObserver_Call{Call: _e.mock.On("AddSettingObserver", observer)}
}

func (_c *MockRequestContext_AddSettingObserver_Call) Run(run func(observer in.SettingObserver)) *MockRequestContext_AddSettingObserver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.SettingObserver
		if args[0] != nil {
			arg0 = args[0].(in.SettingObserver)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestContext_AddSettingObserver_Call) Return(registration in.Registration) *MockRequestContext_AddSettingObserver_Call {
	_c.Call.Return(registration)
	return _c
}

func (_c *MockRequestContext_AddSettingObserver_Call) RunAndReturn(run func(observer in.SettingObserver) in.Registration) *MockRequestContext_AddSettingObserver_Call {
	_c.Call.Return(run)
	return _c
}

// ClearCertificateExceptions provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) ClearCertificateExceptions(callback in.CompletionCallback) {
	_mock.Called(callback)
	return
}

// MockRequestContext_ClearCertificateExceptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCertificateExceptions'
type MockRequestContext_ClearCertificateExceptions_Call struct {
	*mock.Call
}

// ClearCertificateExceptions is a helper method to define mock.On call
//   - callback in.CompletionCallback
func (_e *MockRequestContext_Expecter) ClearCertificateExceptions(callback any) *MockRequestContext_ClearCertificateExceptions_Call {
	return &MockRequestContext_ClearCertificateExceptions_Call{Call: _e.mock.On("ClearCertificateExceptions", callback)}
}

func (_c *MockRequestContext_ClearCertificateExceptions_Call) Run(run func(callback in.CompletionCallback)) *MockRequestContext_ClearCertificateExceptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.CompletionCallback
		if args[0] != nil {
			arg0 = args[0].(in.CompletionCallback)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestContext_ClearCertificateExceptions_Call) Return() *MockRequestContext_ClearCertificateExceptions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestContext_ClearCertificateExceptions_Call) RunAndReturn(run func(callback in.CompletionCallback)) *MockRequestContext_ClearCertificateExceptions_Call {
	_c.Run(run)
	return _c
}

// ClearHttpAuthCredentials provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) ClearHttpAuthCredentials(callback in.CompletionCallback) {
	_mock.Called(callback)
	return
}

// MockRequestContext_ClearHttpAuthCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearHttpAuthCredentials'
type MockRequestContext_ClearHttpAuthCredentials_Call struct {
	*mock.Call
}

// ClearHttpAuthCredentials is a helper method to define mock.On call
//   - callback in.CompletionCallback
func (_e *MockRequestContext_Expecter) ClearHttpAuthCredentials(callback any) *MockRequestContext_ClearHttpAuthCredentials_Call {
	return &MockRequestContext_ClearHttpAuthCredentials_Call{Call: _e.mock.On("ClearHttpAuthCredentials", callback)}
}

func (_c *MockRequestContext_ClearHttpAuthCredentials_Call) Run(run func(callback in.CompletionCallback)) *MockRequestContext_ClearHttpAuthCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.CompletionCallback
		if args[0] != nil {
			arg0 = args[0].(in.CompletionCallback)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestContext_ClearHttpAuthCredentials_Call) Return() *MockRequestContext_ClearHttpAuthCredentials_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestContext_ClearHttpAuthCredentials_Call) RunAndReturn(run func(callback in.CompletionCallback)) *MockRequestContext_ClearHttpAuthCredentials_Call {
	_c.Run(run)
	return _c
}

// ClearHttpCache provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) ClearHttpCache(callback in.CompletionCallback) {
	_mock.Called(callback)
	return
}

// MockRequestContext_ClearHttpCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearHttpCache'
type MockRequestContext_ClearHttpCache_Call struct {
	*mock.Call
}

// ClearHttpCache is a helper method to define mock.On call
//   - callback in.CompletionCallback
func (_e *MockRequestContext_Expecter) ClearHttpCache(callback any) *MockRequestContext_ClearHttpCache_Call {
	return &MockRequestContext_ClearHttpCache_Call{Call: _e.mock.On("ClearHttpCache", callback)}
}

func (_c *MockRequestContext_ClearHttpCache_Call) Run(run func(callback in.CompletionCallback)) *MockRequestContext_ClearHttpCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.CompletionCallback
		if args[0] != nil {
			arg0 = args[0].(in.CompletionCallback)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestContext_ClearHttpCache_Call) Return() *MockRequestContext_ClearHttpCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestContext_ClearHttpCache_Call) RunAndReturn(run func(callback in.CompletionCallback)) *MockRequestContext_ClearHttpCache_Call {
	_c.Run(run)
	return _c
}

// ClearSchemeHandlerFactories provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) ClearSchemeHandlerFactories() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClearSchemeHandlerFactories")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockRequestContext_ClearSchemeHandlerFactories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSchemeHandlerFactories'
type MockRequestContext_ClearSchemeHandlerFactories_Call struct {
	*mock.Call
}

// ClearSchemeHandlerFactories is a helper method to define mock.On call
func (_e *MockRequestContext_Expecter) ClearSchemeHandlerFactories() *MockRequestContext_ClearSchemeHandlerFactories_Call {
	return &MockRequestContext_ClearSchemeHandlerFactories_Call{Call: _e.mock.On("ClearSchemeHandlerFactories")}
}

func (_c *MockRequestContext_ClearSchemeHandlerFactories_Call) Run(run func()) *MockRequestContext_ClearSchemeHandlerFactories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestContext_ClearSchemeHandlerFactories_Call) Return(n int32) *MockRequestContext_ClearSchemeHandlerFactories_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockRequestContext_ClearSchemeHandlerFactories_Call) RunAndReturn(run func() int32) *MockRequestContext_ClearSchemeHandlerFactories_Call {
	_c.Call.Return(run)
	return _c
}

// CloseAllConnections provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) CloseAllConnections(callback in.CompletionCallback) {
	_mock.Called(callback)
	return
}

// MockRequestContext_CloseAllConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAllConnections'
type MockRequestContext_CloseAllConnections_Call struct {
	*mock.Call
}

// CloseAllConnections is a helper method to define mock.On call
//   - callback in.CompletionCallback
func (_e *MockRequestContext_Expecter) CloseAllConnections(callback any) *MockRequestContext_CloseAllConnections_Call {
	return &MockRequestContext_CloseAllConnections_Call{Call: _e.mock.On("CloseAllConnections", callback)}
}

func (_c *MockRequestContext_CloseAllConnections_Call) Run(run func(callback in.CompletionCallback)) *MockRequestContext_CloseAllConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.CompletionCallback
		if args[0] != nil {
			arg0 = args[0].(in.CompletionCallback)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestContext_CloseAllConnections_Call) Return() *MockRequestContext_CloseAllConnections_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestContext_CloseAllConnections_Call) RunAndReturn(run func(callback in.CompletionCallback)) *MockRequestContext_CloseAllConnections_Call {
	_c.Run(run)
	return _c
}

// GetCachePath provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) GetCachePath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCachePath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRequestContext_GetCachePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCachePath'
type MockRequestContext_GetCachePath_Call struct {
	*mock.Call
}

// GetCachePath is a helper method to define mock.On call
func (_e *MockRequestContext_Expecter) GetCachePath() *MockRequestContext_GetCachePath_Call {
	return &MockRequestContext_GetCachePath_Call{Call: _e.mock.On("GetCachePath")}
}

func (_c *MockRequestContext_GetCachePath_Call) Run(run func()) *MockRequestContext_GetCachePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestContext_GetCachePath_Call) Return(s string) *MockRequestContext_GetCachePath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRequestContext_GetCachePath_Call) RunAndReturn(run func() string) *MockRequestContext_GetCachePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetChromeColorSchemeColor provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) GetChromeColorSchemeColor() uintptr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChromeColorSchemeColor")
	}

	var r0 uintptr
	if returnFunc, ok := ret.Get(0).(func() uintptr); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uintptr)
	}
	return r0
}

// MockRequestContext_GetChromeColorSchemeColor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChromeColorSchemeColor'
type MockRequestContext_GetChromeColorSchemeColor_Call struct {
	*mock.Call
}

// GetChromeColorSchemeColor is a helper method to define mock.On call
func (_e *MockRequestContext_Expecter) GetChromeColorSchemeColor() *MockRequestContext_GetChromeColorSchemeColor_Call {
	return &MockRequestContext_GetChromeColorSchemeColor_Call{Call: _e.mock.On("GetChromeColorSchemeColor")}
}

func (_c *MockRequestContext_GetChromeColorSchemeColor_Call) Run(run func()) *MockRequestContext_GetChromeColorSchemeColor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestContext_GetChromeColorSchemeColor_Call) Return(v uintptr) *MockRequestContext_GetChromeColorSchemeColor_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockRequestContext_GetChromeColorSchemeColor_Call) RunAndReturn(run func() uintptr) *MockRequestContext_GetChromeColorSchemeColor_Call {
	_c.Call.Return(run)
	return _c
}

// GetChromeColorSchemeMode provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) GetChromeColorSchemeMode() in.ColorVariant {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChromeColorSchemeMode")
	}

	var r0 in.ColorVariant
	if returnFunc, ok := ret.Get(0).(func() in.ColorVariant); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(in.ColorVariant)
	}
	return r0
}

// MockRequestContext_GetChromeColorSchemeMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChromeColorSchemeMode'
type MockRequestContext_GetChromeColorSchemeMode_Call struct {
	*mock.Call
}

// GetChromeColorSchemeMode is a helper method to define mock.On call
func (_e *MockRequestContext_Expecter) GetChromeColorSchemeMode() *MockRequestContext_GetChromeColorSchemeMode_Call {
	return &MockRequestContext_GetChromeColorSchemeMode_Call{Call: _e.mock.On("GetChromeColorSchemeMode")}
}

func (_c *MockRequestContext_GetChromeColorSchemeMode_Call) Run(run func()) *MockRequestContext_GetChromeColorSchemeMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestContext_GetChromeColorSchemeMode_Call) Return(v in.ColorVariant) *MockRequestContext_GetChromeColorSchemeMode_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockRequestContext_GetChromeColorSchemeMode_Call) RunAndReturn(run func() in.ColorVariant) *MockRequestContext_GetChromeColorSchemeMode_Call {
	_c.Call.Return(run)
	return _c
}

// GetChromeColorSchemeVariant provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) GetChromeColorSchemeVariant() in.ColorVariant {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChromeColorSchemeVariant")
	}

	var r0 in.ColorVariant
	if returnFunc, ok := ret.Get(0).(func() in.ColorVariant); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(in.ColorVariant)
	}
	return r0
}

// MockRequestContext_GetChromeColorSchemeVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChromeColorSchemeVariant'
type MockRequestContext_GetChromeColorSchemeVariant_Call struct {
	*mock.Call
}

// GetChromeColorSchemeVariant is a helper method to define mock.On call
func (_e *MockRequestContext_Expecter) GetChromeColorSchemeVariant() *MockRequestContext_GetChromeColorSchemeVariant_Call {
	return &MockRequestContext_GetChromeColorSchemeVariant_Call{Call: _e.mock.On("GetChromeColorSchemeVariant")}
}

func (_c *MockRequestContext_GetChromeColorSchemeVariant_Call) Run(run func()) *MockRequestContext_GetChromeColorSchemeVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestContext_GetChromeColorSchemeVariant_Call) Return(v in.ColorVariant) *MockRequestContext_GetChromeColorSchemeVariant_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockRequestContext_GetChromeColorSchemeVariant_Call) RunAndReturn(run func() in.ColorVariant) *MockRequestContext_GetChromeColorSchemeVariant_Call {
	_c.Call.Return(run)
	return _c
}

// GetContentSetting provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) GetContentSetting(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes) in.ContentSettingValues {
	ret := _mock.Called(requestingURL, topLevelURL, contentType)

	if len(ret) == 0 {
		panic("no return value specified for GetContentSetting")
	}

	var r0 in.ContentSettingValues
	if returnFunc, ok := ret.Get(0).(func(string, string, in.ContentSettingTypes) in.ContentSettingValues); ok {
		r0 = returnFunc(requestingURL, topLevelURL, contentType)
	} else {
		r0 = ret.Get(0).(in.ContentSettingValues)
	}
	return r0
}

// MockRequestContext_GetContentSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContentSetting'
type MockRequestContext_GetContentSetting_Call struct {
	*mock.Call
}

// GetContentSetting is a helper method to define mock.On call
//   - requestingURL string
//   - topLevelURL string
//   - contentType in.ContentSettingTypes
func (_e *MockRequestContext_Expecter) GetContentSetting(requestingURL any, topLevelURL any, contentType any) *MockRequestContext_GetContentSetting_Call {
	return &MockRequestContext_GetContentSetting_Call{Call: _e.mock.On("GetContentSetting", requestingURL, topLevelURL, contentType)}
}

func (_c *MockRequestContext_GetContentSetting_Call) Run(run func(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes)) *MockRequestContext_GetContentSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 in.ContentSettingTypes
		if args[2] != nil {
			arg2 = args[2].(in.ContentSettingTypes)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRequestContext_GetContentSetting_Call) Return(v in.ContentSettingValues) *MockRequestContext_GetContentSetting_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockRequestContext_GetContentSetting_Call) RunAndReturn(run func(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes) in.ContentSettingValues) *MockRequestContext_GetContentSetting_Call {
	_c.Call.Return(run)
	return _c
}

// GetCookieManager provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) GetCookieManager(callback in.CompletionCallback) in.CookieManager {
	ret := _mock.Called(callback)

	if len(ret) == 0 {
		panic("no return value specified for GetCookieManager")
	}

	var r0 in.CookieManager
	if returnFunc, ok := ret.Get(0).(func(in.CompletionCallback) in.CookieManager); ok {
		r0 = returnFunc(callback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(in.CookieManager)
		}
	}
	return r0
}

// MockRequestContext_GetCookieManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCookieManager'
type MockRequestContext_GetCookieManager_Call struct {
	*mock.Call
}

// GetCookieManager is a helper method to define mock.On call
//   - callback in.CompletionCallback
func (_e *MockRequestContext_Expecter) GetCookieManager(callback any) *MockRequestContext_GetCookieManager_Call {
	return &MockRequestContext_GetCookieManager_Call{Call: _e.mock.On("GetCookieManager", callback)}
}

func (_c *MockRequestContext_GetCookieManager_Call) Run(run func(callback in.CompletionCallback)) *MockRequestContext_GetCookieManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.CompletionCallback
		if args[0] != nil {
			arg0 = args[0].(in.CompletionCallback)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestContext_GetCookieManager_Call) Return(cookieManager in.CookieManager) *MockRequestContext_GetCookieManager_Call {
	_c.Call.Return(cookieManager)
	return _c
}

func (_c *MockRequestContext_GetCookieManager_Call) RunAndReturn(run func(callback in.CompletionCallback) in.CookieManager) *MockRequestContext_GetCookieManager_Call {
	_c.Call.Return(run)
	return _c
}

// GetHandler provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) GetHandler() in.RequestContextHandler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHandler")
	}

	var r0 in.RequestContextHandler
	if returnFunc, ok := ret.Get(0).(func() in.RequestContextHandler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(in.RequestContextHandler)
		}
	}
	return r0
}

// MockRequestContext_GetHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHandler'
type MockRequestContext_GetHandler_Call struct {
	*mock.Call
}

// GetHandler is a helper method to define mock.On call
func (_e *MockRequestContext_Expecter) GetHandler() *MockRequestContext_GetHandler_Call {
	return &MockRequestContext_GetHandler_Call{Call: _e.mock.On("GetHandler")}
}

func (_c *MockRequestContext_GetHandler_Call) Run(run func()) *MockRequestContext_GetHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestContext_GetHandler_Call) Return(requestContextHandler in.RequestContextHandler) *MockRequestContext_GetHandler_Call {
	_c.Call.Return(requestContextHandler)
	return _c
}

func (_c *MockRequestContext_GetHandler_Call) RunAndReturn(run func() in.RequestContextHandler) *MockRequestContext_GetHandler_Call {
	_c.Call.Return(run)
	return _c
}

// GetMediaRouter provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) GetMediaRouter(callback in.CompletionCallback) in.MediaRouter {
	ret := _mock.Called(callback)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaRouter")
	}

	var r0 in.MediaRouter
	if returnFunc, ok := ret.Get(0).(func(in.CompletionCallback) in.MediaRouter); ok {
		r0 = returnFunc(callback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(in.MediaRouter)
		}
	}
	return r0
}

// MockRequestContext_GetMediaRouter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMediaRouter'
type MockRequestContext_GetMediaRouter_Call struct {
	*mock.Call
}

// GetMediaRouter is a helper method to define mock.On call
//   - callback in.CompletionCallback
func (_e *MockRequestContext_Expecter) GetMediaRouter(callback any) *MockRequestContext_GetMediaRouter_Call {
	return &MockRequestContext_GetMediaRouter_Call{Call: _e.mock.On("GetMediaRouter", callback)}
}

func (_c *MockRequestContext_GetMediaRouter_Call) Run(run func(callback in.CompletionCallback)) *MockRequestContext_GetMediaRouter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.CompletionCallback
		if args[0] != nil {
			arg0 = args[0].(in.CompletionCallback)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestContext_GetMediaRouter_Call) Return(mediaRouter in.MediaRouter) *MockRequestContext_GetMediaRouter_Call {
	_c.Call.Return(mediaRouter)
	return _c
}

func (_c *MockRequestContext_GetMediaRouter_Call) RunAndReturn(run func(callback in.CompletionCallback) in.MediaRouter) *MockRequestContext_GetMediaRouter_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebsiteSetting provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) GetWebsiteSetting(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes) in.Value {
	ret := _mock.Called(requestingURL, topLevelURL, contentType)

	if len(ret) == 0 {
		panic("no return value specified for GetWebsiteSetting")
	}

	var r0 in.Value
	if returnFunc, ok := ret.Get(0).(func(string, string, in.ContentSettingTypes) in.Value); ok {
		r0 = returnFunc(requestingURL, topLevelURL, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(in.Value)
		}
	}
	return r0
}

// MockRequestContext_GetWebsiteSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebsiteSetting'
type MockRequestContext_GetWebsiteSetting_Call struct {
	*mock.Call
}

// GetWebsiteSetting is a helper method to define mock.On call
//   - requestingURL string
//   - topLevelURL string
//   - contentType in.ContentSettingTypes
func (_e *MockRequestContext_Expecter) GetWebsiteSetting(requestingURL any, topLevelURL any, contentType any) *MockRequestContext_GetWebsiteSetting_Call {
	return &MockRequestContext_GetWebsiteSetting_Call{Call: _e.mock.On("GetWebsiteSetting", requestingURL, topLevelURL, contentType)}
}

func (_c *MockRequestContext_GetWebsiteSetting_Call) Run(run func(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes)) *MockRequestContext_GetWebsiteSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 in.ContentSettingTypes
		if args[2] != nil {
			arg2 = args[2].(in.ContentSettingTypes)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRequestContext_GetWebsiteSetting_Call) Return(value in.Value) *MockRequestContext_GetWebsiteSetting_Call {
	_c.Call.Return(value)
	return _c
}

func (_c *MockRequestContext_GetWebsiteSetting_Call) RunAndReturn(run func(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes) in.Value) *MockRequestContext_GetWebsiteSetting_Call {
	_c.Call.Return(run)
	return _c
}

// IsGlobal provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) IsGlobal() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsGlobal")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRequestContext_IsGlobal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsGlobal'
type MockRequestContext_IsGlobal_Call struct {
	*mock.Call
}

// IsGlobal is a helper method to define mock.On call
func (_e *MockRequestContext_Expecter) IsGlobal() *MockRequestContext_IsGlobal_Call {
	return &MockRequestContext_IsGlobal_Call{Call: _e.mock.On("IsGlobal")}
}

func (_c *MockRequestContext_IsGlobal_Call) Run(run func()) *MockRequestContext_IsGlobal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestContext_IsGlobal_Call) Return(b bool) *MockRequestContext_IsGlobal_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRequestContext_IsGlobal_Call) RunAndReturn(run func() bool) *MockRequestContext_IsGlobal_Call {
	_c.Call.Return(run)
	return _c
}

// IsSame provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) IsSame(other in.RequestContext) bool {
	ret := _mock.Called(other)

	if len(ret) == 0 {
		panic("no return value specified for IsSame")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(in.RequestContext) bool); ok {
		r0 = returnFunc(other)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRequestContext_IsSame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSame'
type MockRequestContext_IsSame_Call struct {
	*mock.Call
}

// IsSame is a helper method to define mock.On call
//   - other in.RequestContext
func (_e *MockRequestContext_Expecter) IsSame(other any) *MockRequestContext_IsSame_Call {
	return &MockRequestContext_IsSame_Call{Call: _e.mock.On("IsSame", other)}
}

func (_c *MockRequestContext_IsSame_Call) Run(run func(other in.RequestContext)) *MockRequestContext_IsSame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.RequestContext
		if args[0] != nil {
			arg0 = args[0].(in.RequestContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestContext_IsSame_Call) Return(b bool) *MockRequestContext_IsSame_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRequestContext_IsSame_Call) RunAndReturn(run func(other in.RequestContext) bool) *MockRequestContext_IsSame_Call {
	_c.Call.Return(run)
	return _c
}

// IsSharingWith provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) IsSharingWith(other in.RequestContext) bool {
	ret := _mock.Called(other)

	if len(ret) == 0 {
		panic("no return value specified for IsSharingWith")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(in.RequestContext) bool); ok {
		r0 = returnFunc(other)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRequestContext_IsSharingWith_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSharingWith'
type MockRequestContext_IsSharingWith_Call struct {
	*mock.Call
}

// IsSharingWith is a helper method to define mock.On call
//   - other in.RequestContext
func (_e *MockRequestContext_Expecter) IsSharingWith(other any) *MockRequestContext_IsSharingWith_Call {
	return &MockRequestContext_IsSharingWith_Call{Call: _e.mock.On("IsSharingWith", other)}
}

func (_c *MockRequestContext_IsSharingWith_Call) Run(run func(other in.RequestContext)) *MockRequestContext_IsSharingWith_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.RequestContext
		if args[0] != nil {
			arg0 = args[0].(in.RequestContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRequestContext_IsSharingWith_Call) Return(b bool) *MockRequestContext_IsSharingWith_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRequestContext_IsSharingWith_Call) RunAndReturn(run func(other in.RequestContext) bool) *MockRequestContext_IsSharingWith_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterSchemeHandlerFactory provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) RegisterSchemeHandlerFactory(schemeName string, domainName string, factory in.SchemeHandlerFactory) int32 {
	ret := _mock.Called(schemeName, domainName, factory)

	if len(ret) == 0 {
		panic("no return value specified for RegisterSchemeHandlerFactory")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func(string, string, in.SchemeHandlerFactory) int32); ok {
		r0 = returnFunc(schemeName, domainName, factory)
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockRequestContext_RegisterSchemeHandlerFactory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterSchemeHandlerFactory'
type MockRequestContext_RegisterSchemeHandlerFactory_Call struct {
	*mock.Call
}

// RegisterSchemeHandlerFactory is a helper method to define mock.On call
//   - schemeName string
//   - domainName string
//   - factory in.SchemeHandlerFactory
func (_e *MockRequestContext_Expecter) RegisterSchemeHandlerFactory(schemeName any, domainName any, factory any) *MockRequestContext_RegisterSchemeHandlerFactory_Call {
	return &MockRequestContext_RegisterSchemeHandlerFactory_Call{Call: _e.mock.On("RegisterSchemeHandlerFactory", schemeName, domainName, factory)}
}

func (_c *MockRequestContext_RegisterSchemeHandlerFactory_Call) Run(run func(schemeName string, domainName string, factory in.SchemeHandlerFactory)) *MockRequestContext_RegisterSchemeHandlerFactory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 in.SchemeHandlerFactory
		if args[2] != nil {
			arg2 = args[2].(in.SchemeHandlerFactory)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRequestContext_RegisterSchemeHandlerFactory_Call) Return(n int32) *MockRequestContext_RegisterSchemeHandlerFactory_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockRequestContext_RegisterSchemeHandlerFactory_Call) RunAndReturn(run func(schemeName string, domainName string, factory in.SchemeHandlerFactory) int32) *MockRequestContext_RegisterSchemeHandlerFactory_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveHost provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) ResolveHost(origin string, callback in.ResolveCallback) {
	_mock.Called(origin, callback)
	return
}

// MockRequestContext_ResolveHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveHost'
type MockRequestContext_ResolveHost_Call struct {
	*mock.Call
}

// ResolveHost is a helper method to define mock.On call
//   - origin string
//   - callback in.ResolveCallback
func (_e *MockRequestContext_Expecter) ResolveHost(origin any, callback any) *MockRequestContext_ResolveHost_Call {
	return &MockRequestContext_ResolveHost_Call{Call: _e.mock.On("ResolveHost", origin, callback)}
}

func (_c *MockRequestContext_ResolveHost_Call) Run(run func(origin string, callback in.ResolveCallback)) *MockRequestContext_ResolveHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 in.ResolveCallback
		if args[1] != nil {
			arg1 = args[1].(in.ResolveCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestContext_ResolveHost_Call) Return() *MockRequestContext_ResolveHost_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestContext_ResolveHost_Call) RunAndReturn(run func(origin string, callback in.ResolveCallback)) *MockRequestContext_ResolveHost_Call {
	_c.Run(run)
	return _c
}

// SetChromeColorScheme provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) SetChromeColorScheme(variant in.ColorVariant, userColor uintptr) {
	_mock.Called(variant, userColor)
	return
}

// MockRequestContext_SetChromeColorScheme_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetChromeColorScheme'
type MockRequestContext_SetChromeColorScheme_Call struct {
	*mock.Call
}

// SetChromeColorScheme is a helper method to define mock.On call
//   - variant in.ColorVariant
//   - userColor uintptr
func (_e *MockRequestContext_Expecter) SetChromeColorScheme(variant any, userColor any) *MockRequestContext_SetChromeColorScheme_Call {
	return &MockRequestContext_SetChromeColorScheme_Call{Call: _e.mock.On("SetChromeColorScheme", variant, userColor)}
}

func (_c *MockRequestContext_SetChromeColorScheme_Call) Run(run func(variant in.ColorVariant, userColor uintptr)) *MockRequestContext_SetChromeColorScheme_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.ColorVariant
		if args[0] != nil {
			arg0 = args[0].(in.ColorVariant)
		}
		var arg1 uintptr
		if args[1] != nil {
			arg1 = args[1].(uintptr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestContext_SetChromeColorScheme_Call) Return() *MockRequestContext_SetChromeColorScheme_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestContext_SetChromeColorScheme_Call) RunAndReturn(run func(variant in.ColorVariant, userColor uintptr)) *MockRequestContext_SetChromeColorScheme_Call {
	_c.Run(run)
	return _c
}

// SetContentSetting provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) SetContentSetting(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes, value in.ContentSettingValues) {
	_mock.Called(requestingURL, topLevelURL, contentType, value)
	return
}

// MockRequestContext_SetContentSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContentSetting'
type MockRequestContext_SetContentSetting_Call struct {
	*mock.Call
}

// SetContentSetting is a helper method to define mock.On call
//   - requestingURL string
//   - topLevelURL string
//   - contentType in.ContentSettingTypes
//   - value in.ContentSettingValues
func (_e *MockRequestContext_Expecter) SetContentSetting(requestingURL any, topLevelURL any, contentType any, value any) *MockRequestContext_SetContentSetting_Call {
	return &MockRequestContext_SetContentSetting_Call{Call: _e.mock.On("SetContentSetting", requestingURL, topLevelURL, contentType, value)}
}

func (_c *MockRequestContext_SetContentSetting_Call) Run(run func(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes, value in.ContentSettingValues)) *MockRequestContext_SetContentSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 in.ContentSettingTypes
		if args[2] != nil {
			arg2 = args[2].(in.ContentSettingTypes)
		}
		var arg3 in.ContentSettingValues
		if args[3] != nil {
			arg3 = args[3].(in.ContentSettingValues)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRequestContext_SetContentSetting_Call) Return() *MockRequestContext_SetContentSetting_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestContext_SetContentSetting_Call) RunAndReturn(run func(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes, value in.ContentSettingValues)) *MockRequestContext_SetContentSetting_Call {
	_c.Run(run)
	return _c
}

// SetWebsiteSetting provides a mock function for the type MockRequestContext
func (_mock *MockRequestContext) SetWebsiteSetting(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes, value in.Value) {
	_mock.Called(requestingURL, topLevelURL, contentType, value)
	return
}

// MockRequestContext_SetWebsiteSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWebsiteSetting'
type MockRequestContext_SetWebsiteSetting_Call struct {
	*mock.Call
}

// SetWebsiteSetting is a helper method to define mock.On call
//   - requestingURL string
//   - topLevelURL string
//   - contentType in.ContentSettingTypes
//   - value in.Value
func (_e *MockRequestContext_Expecter) SetWebsiteSetting(requestingURL any, topLevelURL any, contentType any, value any) *MockRequestContext_SetWebsiteSetting_Call {
	return &MockRequestContext_SetWebsiteSetting_Call{Call: _e.mock.On("SetWebsiteSetting", requestingURL, topLevelURL, contentType, value)}
}

func (_c *MockRequestContext_SetWebsiteSetting_Call) Run(run func(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes, value in.Value)) *MockRequestContext_SetWebsiteSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 in.ContentSettingTypes
		if args[2] != nil {
			arg2 = args[2].(in.ContentSettingTypes)
		}
		var arg3 in.Value
		if args[3] != nil {
			arg3 = args[3].(in.Value)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRequestContext_SetWebsiteSetting_Call) Return() *MockRequestContext_SetWebsiteSetting_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestContext_SetWebsiteSetting_Call) RunAndReturn(run func(requestingURL string, topLevelURL string, contentType in.ContentSettingTypes, value in.Value)) *MockRequestContext_SetWebsiteSetting_Call {
	_c.Run(run)
	return _c
}
