// Code generated by cefgen. DO NOT EDIT.

package in

import (
	"github.com/bnema/purego-cef/internal/capi"
)

// MainArgs is a type alias for the raw data struct.
type MainArgs = capi.CEFMainArgsT

// WindowInfo is a type alias for the raw data struct.
type WindowInfo = capi.CEFWindowInfoT

// AcceleratedPaintNativePixmapPlane is a type alias for the raw data struct.
type AcceleratedPaintNativePixmapPlane = capi.CEFAcceleratedPaintNativePixmapPlaneT

// AcceleratedPaintInfo is a type alias for the raw data struct.
type AcceleratedPaintInfo = capi.CEFAcceleratedPaintInfoT
