// Code generated by cefgen. DO NOT EDIT.

package in

// PrintDialogCallback defines the inbound port interface.
type PrintDialogCallback interface {
	Cont(settings PrintSettings)
	Cancel()
}

// PrintJobCallback defines the inbound port interface.
type PrintJobCallback interface {
	Cont()
}

// PrintHandler defines the inbound port interface.
type PrintHandler interface {
	OnPrintStart(browser Browser)
	OnPrintSettings(browser Browser, settings PrintSettings, getDefaults int32)
	OnPrintDialog(browser Browser, hasSelection int32, callback PrintDialogCallback) int32
	OnPrintJob(browser Browser, documentName string, pdfFilePath string, callback PrintJobCallback) int32
	OnPrintReset(browser Browser)
	GetPdfPaperSize(browser Browser, deviceUnitsPerInch int32) uintptr
}
