// Code generated by cefgen. DO NOT EDIT.

package in

import (
	"github.com/bnema/purego-cef/internal/capi"
)

// Point is a type alias for the raw data struct.
type Point = capi.CEFPointT

// Rect is a type alias for the raw data struct.
type Rect = capi.CEFRectT

// Size is a type alias for the raw data struct.
type Size = capi.CEFSizeT

// Insets is a type alias for the raw data struct.
type Insets = capi.CEFInsetsT
