// Code generated by cefgen. DO NOT EDIT.

package in

// Sslstatus defines the inbound port interface.
type Sslstatus interface {
	IsSecureConnection() bool
	GetCertStatus() CertStatus
	GetSslversion() SslVersion
	GetContentStatus() SslContentStatus
	GetX509Certificate() X509Certificate
}
