// Code generated by cefgen. DO NOT EDIT.

package in

// MenuButtonPressedLock defines the inbound port interface.
type MenuButtonPressedLock interface {
}

// MenuButtonDelegate defines the inbound port interface.
type MenuButtonDelegate interface {
	OnMenuButtonPressed(menuButton MenuButton, screenPoint *Point, buttonPressedLock MenuButtonPressedLock)
}
