// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// ResourceRequestHandler Implement this structure to handle events related to browser requests. The functions of this structure will be called on the IO thread unless otherwise indicated.
type ResourceRequestHandler = portin.ResourceRequestHandler

// resourceRequestHandlerWrapper wraps a user-provided ResourceRequestHandler implementation together
// with the raw CEF struct pointer allocated by NewResourceRequestHandler.  It satisfies the
// ResourceRequestHandler interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type resourceRequestHandlerWrapper struct {
	ResourceRequestHandler // embed user impl for interface delegation
	rawPtr                 *capi.CEFResourceRequestHandlerT
}

func (w *resourceRequestHandlerWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

var resourceRequestHandlerGetCookieAccessFilterSharedOnce sync.Once
var resourceRequestHandlerGetCookieAccessFilterSharedCallback uintptr

func resourceRequestHandlerGetCookieAccessFilterCEFCallback() uintptr {
	return sharedCEFCallback(&resourceRequestHandlerGetCookieAccessFilterSharedOnce, &resourceRequestHandlerGetCookieAccessFilterSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
		impl, ownerOK := cefCallbackOwnerAs[ResourceRequestHandler](self)
		if !ownerOK {
			return 0
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		request := wrapRequest(unsafe.Pointer(arg2))
		result := impl.GetCookieAccessFilter(browser, frame, request)
		if result == nil {
			return 0
		}
		return uintptr(extractOrWrapRawPointer(result, func() any {
			return NewCookieAccessFilter(result)
		}))
	})
}

var resourceRequestHandlerOnBeforeResourceLoadSharedOnce sync.Once
var resourceRequestHandlerOnBeforeResourceLoadSharedCallback uintptr

func resourceRequestHandlerOnBeforeResourceLoadCEFCallback() uintptr {
	return sharedCEFCallback(&resourceRequestHandlerOnBeforeResourceLoadSharedOnce, &resourceRequestHandlerOnBeforeResourceLoadSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
		impl, ownerOK := cefCallbackOwnerAs[ResourceRequestHandler](self)
		if !ownerOK {
			return 0
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		request := wrapRequest(unsafe.Pointer(arg2))
		callback := wrapCallback(unsafe.Pointer(arg3))
		return uintptr(impl.OnBeforeResourceLoad(browser, frame, request, callback))
	})
}

var resourceRequestHandlerGetResourceHandlerSharedOnce sync.Once
var resourceRequestHandlerGetResourceHandlerSharedCallback uintptr

func resourceRequestHandlerGetResourceHandlerCEFCallback() uintptr {
	return sharedCEFCallback(&resourceRequestHandlerGetResourceHandlerSharedOnce, &resourceRequestHandlerGetResourceHandlerSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
		impl, ownerOK := cefCallbackOwnerAs[ResourceRequestHandler](self)
		if !ownerOK {
			return 0
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		request := wrapRequest(unsafe.Pointer(arg2))
		result := impl.GetResourceHandler(browser, frame, request)
		if result == nil {
			return 0
		}
		return uintptr(extractOrWrapRawPointer(result, func() any {
			return NewResourceHandler(result)
		}))
	})
}

var resourceRequestHandlerOnResourceRedirectSharedOnce sync.Once
var resourceRequestHandlerOnResourceRedirectSharedCallback uintptr

func resourceRequestHandlerOnResourceRedirectCEFCallback() uintptr {
	return sharedCEFCallback(&resourceRequestHandlerOnResourceRedirectSharedOnce, &resourceRequestHandlerOnResourceRedirectSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr, arg4 uintptr) {
		impl, ownerOK := cefCallbackOwnerAs[ResourceRequestHandler](self)
		if !ownerOK {
			return
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		request := wrapRequest(unsafe.Pointer(arg2))
		response := wrapResponse(unsafe.Pointer(arg3))
		newURL := uintptr(arg4)
		impl.OnResourceRedirect(browser, frame, request, response, newURL)
	})
}

var resourceRequestHandlerOnResourceResponseSharedOnce sync.Once
var resourceRequestHandlerOnResourceResponseSharedCallback uintptr

func resourceRequestHandlerOnResourceResponseCEFCallback() uintptr {
	return sharedCEFCallback(&resourceRequestHandlerOnResourceResponseSharedOnce, &resourceRequestHandlerOnResourceResponseSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
		impl, ownerOK := cefCallbackOwnerAs[ResourceRequestHandler](self)
		if !ownerOK {
			return 0
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		request := wrapRequest(unsafe.Pointer(arg2))
		response := wrapResponse(unsafe.Pointer(arg3))
		return uintptr(impl.OnResourceResponse(browser, frame, request, response))
	})
}

var resourceRequestHandlerGetResourceResponseFilterSharedOnce sync.Once
var resourceRequestHandlerGetResourceResponseFilterSharedCallback uintptr

func resourceRequestHandlerGetResourceResponseFilterCEFCallback() uintptr {
	return sharedCEFCallback(&resourceRequestHandlerGetResourceResponseFilterSharedOnce, &resourceRequestHandlerGetResourceResponseFilterSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
		impl, ownerOK := cefCallbackOwnerAs[ResourceRequestHandler](self)
		if !ownerOK {
			return 0
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		request := wrapRequest(unsafe.Pointer(arg2))
		response := wrapResponse(unsafe.Pointer(arg3))
		result := impl.GetResourceResponseFilter(browser, frame, request, response)
		if result == nil {
			return 0
		}
		return uintptr(extractOrWrapRawPointer(result, func() any {
			return NewResponseFilter(result)
		}))
	})
}

var resourceRequestHandlerOnResourceLoadCompleteSharedOnce sync.Once
var resourceRequestHandlerOnResourceLoadCompleteSharedCallback uintptr

func resourceRequestHandlerOnResourceLoadCompleteCEFCallback() uintptr {
	return sharedCEFCallback(&resourceRequestHandlerOnResourceLoadCompleteSharedOnce, &resourceRequestHandlerOnResourceLoadCompleteSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 int64) {
		impl, ownerOK := cefCallbackOwnerAs[ResourceRequestHandler](self)
		if !ownerOK {
			return
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		request := wrapRequest(unsafe.Pointer(arg2))
		response := wrapResponse(unsafe.Pointer(arg3))
		status := UrlrequestStatus(arg4)
		receivedContentLength := arg5
		impl.OnResourceLoadComplete(browser, frame, request, response, status, receivedContentLength)
	})
}

var resourceRequestHandlerOnProtocolExecutionSharedOnce sync.Once
var resourceRequestHandlerOnProtocolExecutionSharedCallback uintptr

func resourceRequestHandlerOnProtocolExecutionCEFCallback() uintptr {
	return sharedCEFCallback(&resourceRequestHandlerOnProtocolExecutionSharedOnce, &resourceRequestHandlerOnProtocolExecutionSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) {
		impl, ownerOK := cefCallbackOwnerAs[ResourceRequestHandler](self)
		if !ownerOK {
			return
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		request := wrapRequest(unsafe.Pointer(arg2))
		allowOsExecution := (*int32)(unsafe.Pointer(arg3))
		impl.OnProtocolExecution(browser, frame, request, allowOsExecution)
	})
}

// NewResourceRequestHandler creates a CEF handler backed by the given implementation.
func NewResourceRequestHandler(impl ResourceRequestHandler) ResourceRequestHandler {
	if isNilImpl(impl) {
		return nil
	}
	r := new(capi.CEFResourceRequestHandlerT)
	w := &resourceRequestHandlerWrapper{rawPtr: r}
	w.ResourceRequestHandler = impl
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), w)

	r.OverrideGetCookieAccessFilter(resourceRequestHandlerGetCookieAccessFilterCEFCallback())

	r.OverrideOnBeforeResourceLoad(resourceRequestHandlerOnBeforeResourceLoadCEFCallback())

	r.OverrideGetResourceHandler(resourceRequestHandlerGetResourceHandlerCEFCallback())

	r.OverrideOnResourceRedirect(resourceRequestHandlerOnResourceRedirectCEFCallback())

	r.OverrideOnResourceResponse(resourceRequestHandlerOnResourceResponseCEFCallback())

	r.OverrideGetResourceResponseFilter(resourceRequestHandlerGetResourceResponseFilterCEFCallback())

	r.OverrideOnResourceLoadComplete(resourceRequestHandlerOnResourceLoadCompleteCEFCallback())

	r.OverrideOnProtocolExecution(resourceRequestHandlerOnProtocolExecutionCEFCallback())

	return w
}

// resourceRequestHandlerImpl is a reverse wrapper for a CEF-owned ResourceRequestHandler pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type resourceRequestHandlerImpl struct {
	rawPtr                     *capi.CEFResourceRequestHandlerT
	releaseOnce                sync.Once
	onResourceLoadCompleteOnce sync.Once
	onResourceLoadCompleteFunc func(*capi.CEFResourceRequestHandlerT, uintptr, uintptr, uintptr, uintptr, uintptr, int64)
}

func (obj *resourceRequestHandlerImpl) GetCookieAccessFilter(browser Browser, frame Frame, request Request) CookieAccessFilter {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetCookieAccessFilter(uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(frame)), uintptr(extractRawPointer(request)))
	return wrapCookieAccessFilter(unsafe.Pointer(ret))
}

func (obj *resourceRequestHandlerImpl) OnBeforeResourceLoad(browser Browser, frame Frame, request Request, callback Callback) ReturnValue {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallOnBeforeResourceLoad(uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(frame)), uintptr(extractRawPointer(request)), uintptr(extractRawPointer(callback)))
	return ReturnValue(ret)
}

func (obj *resourceRequestHandlerImpl) GetResourceHandler(browser Browser, frame Frame, request Request) ResourceHandler {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetResourceHandler(uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(frame)), uintptr(extractRawPointer(request)))
	return wrapResourceHandler(unsafe.Pointer(ret))
}

func (obj *resourceRequestHandlerImpl) OnResourceRedirect(browser Browser, frame Frame, request Request, response Response, newURL uintptr) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallOnResourceRedirect(uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(frame)), uintptr(extractRawPointer(request)), uintptr(extractRawPointer(response)), newURL)
}

func (obj *resourceRequestHandlerImpl) OnResourceResponse(browser Browser, frame Frame, request Request, response Response) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallOnResourceResponse(uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(frame)), uintptr(extractRawPointer(request)), uintptr(extractRawPointer(response)))
	return int32(ret)
}

func (obj *resourceRequestHandlerImpl) GetResourceResponseFilter(browser Browser, frame Frame, request Request, response Response) ResponseFilter {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetResourceResponseFilter(uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(frame)), uintptr(extractRawPointer(request)), uintptr(extractRawPointer(response)))
	return wrapResponseFilter(unsafe.Pointer(ret))
}

func (obj *resourceRequestHandlerImpl) OnResourceLoadComplete(browser Browser, frame Frame, request Request, response Response, status UrlrequestStatus, receivedContentLength int64) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	obj.onResourceLoadCompleteOnce.Do(func() {
		registerTypedCallback(&obj.onResourceLoadCompleteFunc, rawPtr.OnResourceLoadComplete)
	})
	obj.onResourceLoadCompleteFunc(rawPtr, uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(frame)), uintptr(extractRawPointer(request)), uintptr(extractRawPointer(response)), uintptr(status), receivedContentLength)
}

func (obj *resourceRequestHandlerImpl) OnProtocolExecution(browser Browser, frame Frame, request Request, allowOsExecution *int32) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallOnProtocolExecution(uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(frame)), uintptr(extractRawPointer(request)), uintptr(unsafe.Pointer(allowOsExecution)))
}

func (obj *resourceRequestHandlerImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *resourceRequestHandlerImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

// wrapResourceRequestHandler wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapResourceRequestHandler(ptr unsafe.Pointer) ResourceRequestHandler {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFResourceRequestHandlerT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &resourceRequestHandlerImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*resourceRequestHandlerImpl).Release)
	return impl
}

// CookieAccessFilter Implement this structure to filter cookies that may be sent or received from resource requests. The functions of this structure will be called on the IO thread unless otherwise indicated.
type CookieAccessFilter = portin.CookieAccessFilter

// cookieAccessFilterWrapper wraps a user-provided CookieAccessFilter implementation together
// with the raw CEF struct pointer allocated by NewCookieAccessFilter.  It satisfies the
// CookieAccessFilter interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type cookieAccessFilterWrapper struct {
	CookieAccessFilter // embed user impl for interface delegation
	rawPtr             *capi.CEFCookieAccessFilterT
}

func (w *cookieAccessFilterWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

var cookieAccessFilterCanSendCookieSharedOnce sync.Once
var cookieAccessFilterCanSendCookieSharedCallback uintptr

func cookieAccessFilterCanSendCookieCEFCallback() uintptr {
	return sharedCEFCallback(&cookieAccessFilterCanSendCookieSharedOnce, &cookieAccessFilterCanSendCookieSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
		impl, ownerOK := cefCallbackOwnerAs[CookieAccessFilter](self)
		if !ownerOK {
			return 0
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		request := wrapRequest(unsafe.Pointer(arg2))
		cookie := (*Cookie)(unsafe.Pointer(arg3))
		if impl.CanSendCookie(browser, frame, request, cookie) {
			return 1
		}
		return 0
	})
}

var cookieAccessFilterCanSaveCookieSharedOnce sync.Once
var cookieAccessFilterCanSaveCookieSharedCallback uintptr

func cookieAccessFilterCanSaveCookieCEFCallback() uintptr {
	return sharedCEFCallback(&cookieAccessFilterCanSaveCookieSharedOnce, &cookieAccessFilterCanSaveCookieSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr, arg4 uintptr) uintptr {
		impl, ownerOK := cefCallbackOwnerAs[CookieAccessFilter](self)
		if !ownerOK {
			return 0
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		request := wrapRequest(unsafe.Pointer(arg2))
		response := wrapResponse(unsafe.Pointer(arg3))
		cookie := (*Cookie)(unsafe.Pointer(arg4))
		if impl.CanSaveCookie(browser, frame, request, response, cookie) {
			return 1
		}
		return 0
	})
}

// NewCookieAccessFilter creates a CEF handler backed by the given implementation.
func NewCookieAccessFilter(impl CookieAccessFilter) CookieAccessFilter {
	if isNilImpl(impl) {
		return nil
	}
	r := new(capi.CEFCookieAccessFilterT)
	w := &cookieAccessFilterWrapper{rawPtr: r}
	w.CookieAccessFilter = impl
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), w)

	r.OverrideCanSendCookie(cookieAccessFilterCanSendCookieCEFCallback())

	r.OverrideCanSaveCookie(cookieAccessFilterCanSaveCookieCEFCallback())

	return w
}

// cookieAccessFilterImpl is a reverse wrapper for a CEF-owned CookieAccessFilter pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type cookieAccessFilterImpl struct {
	rawPtr      *capi.CEFCookieAccessFilterT
	releaseOnce sync.Once
}

func (obj *cookieAccessFilterImpl) CanSendCookie(browser Browser, frame Frame, request Request, cookie *Cookie) bool {
	if obj == nil || obj.rawPtr == nil {
		return false
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallCanSendCookie(uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(frame)), uintptr(extractRawPointer(request)), uintptr(unsafe.Pointer(cookie)))
	return ret != 0
}

func (obj *cookieAccessFilterImpl) CanSaveCookie(browser Browser, frame Frame, request Request, response Response, cookie *Cookie) bool {
	if obj == nil || obj.rawPtr == nil {
		return false
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallCanSaveCookie(uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(frame)), uintptr(extractRawPointer(request)), uintptr(extractRawPointer(response)), uintptr(unsafe.Pointer(cookie)))
	return ret != 0
}

func (obj *cookieAccessFilterImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *cookieAccessFilterImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

// wrapCookieAccessFilter wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapCookieAccessFilter(ptr unsafe.Pointer) CookieAccessFilter {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFCookieAccessFilterT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &cookieAccessFilterImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*cookieAccessFilterImpl).Release)
	return impl
}
