// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// WaitableEvent WaitableEvent is a thread synchronization tool that allows one thread to wait for another thread to finish some work. This is equivalent to using a Lock+ConditionVariable to protect a simple boolean value. However, using WaitableEvent in conjunction with a Lock to wait for a more complex state change (e.g., for an item to be added to a queue) is not recommended. In that case consider using a ConditionVariable instead of a WaitableEvent. It is safe to create and/or signal a WaitableEvent from any thread. Blocking on a WaitableEvent by calling the *wait() functions is not allowed on the browser process UI or IO threads.
type WaitableEvent interface {
	// Reset Put the event in the un-signaled state.
	Reset()
	Signal()
	// IsSignaled Returns true (1) if the event is in the signaled state, else false (0). If the event was created with |automatic_reset| set to true (1) then calling this function will also cause a reset.
	IsSignaled() bool
	Wait()
	// TimedWait Wait up to |max_ms| milliseconds for the event to be signaled. Returns true (1) if the event was signaled. A return value of false (0) does not necessarily mean that |max_ms| was exceeded. This function will not return until after the call to signal() has completed. This function cannot be called on the browser process UI or IO threads.
	TimedWait(maxMs int64) int32
}

type waitableEventImpl struct {
	rawPtr *raw.CEFWaitableEventT
}

func (obj *waitableEventImpl) Reset() {
	obj.rawPtr.CallReset()
}

func (obj *waitableEventImpl) Signal() {
	obj.rawPtr.CallSignal()
}

func (obj *waitableEventImpl) IsSignaled() bool {
	return obj.rawPtr.CallIsSignaled() != 0
}

func (obj *waitableEventImpl) Wait() {
	obj.rawPtr.CallWait()
}

func (obj *waitableEventImpl) TimedWait(maxMs int64) int32 {
	return int32(obj.rawPtr.CallTimedWait(uintptr(maxMs)))
}

func (obj *waitableEventImpl) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *waitableEventImpl) Release() {
	base := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapWaitableEvent(ptr unsafe.Pointer) WaitableEvent {
	if ptr == nil {
		return nil
	}
	r := (*raw.CEFWaitableEventT)(ptr)
	base := (*raw.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &waitableEventImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *waitableEventImpl) {
		b := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// WaitableEventCreate Create a new waitable event. If |automatic_reset| is true (1) then the event state is automatically reset to un-signaled after a single waiting thread has been released; otherwise, the state remains signaled until reset() is called manually. If |initially_signaled| is true (1) then the event will start in the signaled state.
func WaitableEventCreate(automaticReset int32, initiallySignaled int32) WaitableEvent {
	return wrapWaitableEvent(raw.CEFWaitableEventCreate(automaticReset, initiallySignaled))
}
