// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/ebitengine/purego"

	"github.com/bnema/purego-cef/internal/capi"
)

// Value Structure that wraps other data value types. Complex types (binary, dictionary and list) will be referenced but not owned by this object. Can be used on any process and thread.
type Value interface {
	// IsValid Returns true (1) if the underlying data is valid. This will always be true (1) for simple types. For complex types (binary, dictionary and list) the underlying data may become invalid if owned by another object (e.g. list or dictionary) and that other object is then modified or destroyed. This value object can be re-used by calling Set*() even if the underlying data is invalid.
	IsValid() bool
	// IsOwned Returns true (1) if the underlying data is owned by another object.
	IsOwned() bool
	// IsReadOnly Returns true (1) if the underlying data is read-only. Some APIs may expose read-only objects.
	IsReadOnly() bool
	// IsSame Returns true (1) if this object and |that| object have the same underlying data. If true (1) modifications to this object will also affect |that| object and vice-versa.
	IsSame(that Value) bool
	// IsEqual Returns true (1) if this object and |that| object have an equivalent underlying value but are not necessarily the same object.
	IsEqual(that Value) bool
	Copy() Value
	// GetType Returns the underlying value type.
	GetType() ValueType
	// GetBool Returns the underlying value as type bool.
	GetBool() int32
	// GetInt Returns the underlying value as type int.
	GetInt() int32
	// GetDouble Returns the underlying value as type double.
	GetDouble() float64
	// GetString Returns the underlying value as type string.
	GetString() string
	// GetBinary Returns the underlying value as type binary. The returned reference may become invalid if the value is owned by another object or if ownership is transferred to another object in the future. To maintain a reference to the value after assigning ownership to a dictionary or list pass this object to the set_value() function instead of passing the returned reference to set_binary().
	GetBinary() BinaryValue
	// GetDictionary Returns the underlying value as type dictionary. The returned reference may become invalid if the value is owned by another object or if ownership is transferred to another object in the future. To maintain a reference to the value after assigning ownership to a dictionary or list pass this object to the set_value() function instead of passing the returned reference to set_dictionary().
	GetDictionary() DictionaryValue
	// GetList Returns the underlying value as type list. The returned reference may become invalid if the value is owned by another object or if ownership is transferred to another object in the future. To maintain a reference to the value after assigning ownership to a dictionary or list pass this object to the set_value() function instead of passing the returned reference to set_list().
	GetList() ListValue
	// SetNull Sets the underlying value as type null. Returns true (1) if the value was set successfully.
	SetNull() int32
	// SetBool Sets the underlying value as type bool. Returns true (1) if the value was set successfully.
	SetBool(value int32) int32
	// SetInt Sets the underlying value as type int. Returns true (1) if the value was set successfully.
	SetInt(value int32) int32
	// SetDouble Sets the underlying value as type double. Returns true (1) if the value was set successfully.
	SetDouble(value float64) int32
	// SetString Sets the underlying value as type string. Returns true (1) if the value was set successfully.
	SetString(value string) int32
	SetBinary(value BinaryValue) int32
	SetDictionary(value DictionaryValue) int32
	SetList(value ListValue) int32
}

type valueImpl struct {
	rawPtr *capi.CEFValueT
}

func (obj *valueImpl) IsValid() bool {
	return obj.rawPtr.CallIsValid() != 0
}

func (obj *valueImpl) IsOwned() bool {
	return obj.rawPtr.CallIsOwned() != 0
}

func (obj *valueImpl) IsReadOnly() bool {
	return obj.rawPtr.CallIsReadOnly() != 0
}

func (obj *valueImpl) IsSame(that Value) bool {
	return obj.rawPtr.CallIsSame(uintptr(extractRawPointer(that))) != 0
}

func (obj *valueImpl) IsEqual(that Value) bool {
	return obj.rawPtr.CallIsEqual(uintptr(extractRawPointer(that))) != 0
}

func (obj *valueImpl) Copy() Value {
	return wrapValue(unsafe.Pointer(obj.rawPtr.CallCopy()))
}

func (obj *valueImpl) GetType() ValueType {
	return ValueType(obj.rawPtr.CallGetType())
}

func (obj *valueImpl) GetBool() int32 {
	return int32(obj.rawPtr.CallGetBool())
}

func (obj *valueImpl) GetInt() int32 {
	return int32(obj.rawPtr.CallGetInt())
}

func (obj *valueImpl) GetDouble() float64 {
	var fn func(*capi.CEFValueT) float64
	purego.RegisterFunc(&fn, obj.rawPtr.GetDouble)
	return fn(obj.rawPtr)
}

func (obj *valueImpl) GetString() string {
	return goStringUserfree(unsafe.Pointer(obj.rawPtr.CallGetString()))
}

func (obj *valueImpl) GetBinary() BinaryValue {
	return wrapBinaryValue(unsafe.Pointer(obj.rawPtr.CallGetBinary()))
}

func (obj *valueImpl) GetDictionary() DictionaryValue {
	return wrapDictionaryValue(unsafe.Pointer(obj.rawPtr.CallGetDictionary()))
}

func (obj *valueImpl) GetList() ListValue {
	return wrapListValue(unsafe.Pointer(obj.rawPtr.CallGetList()))
}

func (obj *valueImpl) SetNull() int32 {
	return int32(obj.rawPtr.CallSetNull())
}

func (obj *valueImpl) SetBool(value int32) int32 {
	return int32(obj.rawPtr.CallSetBool(uintptr(value)))
}

func (obj *valueImpl) SetInt(value int32) int32 {
	return int32(obj.rawPtr.CallSetInt(uintptr(value)))
}

func (obj *valueImpl) SetDouble(value float64) int32 {
	var fn func(*capi.CEFValueT, float64) uintptr
	purego.RegisterFunc(&fn, obj.rawPtr.SetDouble)
	return int32(fn(obj.rawPtr, value))
}

func (obj *valueImpl) SetString(value string) int32 {
	valueStr := cefString(value)
	defer freeCefString(&valueStr)
	return int32(obj.rawPtr.CallSetString(uintptr(unsafe.Pointer(&valueStr))))
}

func (obj *valueImpl) SetBinary(value BinaryValue) int32 {
	return int32(obj.rawPtr.CallSetBinary(uintptr(extractRawPointer(value))))
}

func (obj *valueImpl) SetDictionary(value DictionaryValue) int32 {
	return int32(obj.rawPtr.CallSetDictionary(uintptr(extractRawPointer(value))))
}

func (obj *valueImpl) SetList(value ListValue) int32 {
	return int32(obj.rawPtr.CallSetList(uintptr(extractRawPointer(value))))
}

func (obj *valueImpl) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *valueImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapValue(ptr unsafe.Pointer) Value {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFValueT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &valueImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *valueImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// BinaryValue Structure representing a binary value. Can be used on any process and thread.
type BinaryValue interface {
	// IsValid Returns true (1) if this object is valid. This object may become invalid if the underlying data is owned by another object (e.g. list or dictionary) and that other object is then modified or destroyed. Do not call any other functions if this function returns false (0).
	IsValid() bool
	// IsOwned Returns true (1) if this object is currently owned by another object.
	IsOwned() bool
	// IsSame Returns true (1) if this object and |that| object have the same underlying data.
	IsSame(that BinaryValue) bool
	// IsEqual Returns true (1) if this object and |that| object have an equivalent underlying value but are not necessarily the same object.
	IsEqual(that BinaryValue) bool
	Copy() BinaryValue
	// GetRawData Returns a pointer to the beginning of the memory block. The returned pointer is valid as long as the cef_binary_value_t is alive.
	GetRawData() unsafe.Pointer
	// GetSize Returns the data size.
	GetSize() int
	// GetData Read up to |buffer_size| number of bytes into |buffer|. Reading begins at the specified byte |data_offset|. Returns the number of bytes read.
	GetData(buffer unsafe.Pointer, bufferSize int, dataOffset int) int
}

type binaryValueImpl struct {
	rawPtr *capi.CEFBinaryValueT
}

func (obj *binaryValueImpl) IsValid() bool {
	return obj.rawPtr.CallIsValid() != 0
}

func (obj *binaryValueImpl) IsOwned() bool {
	return obj.rawPtr.CallIsOwned() != 0
}

func (obj *binaryValueImpl) IsSame(that BinaryValue) bool {
	return obj.rawPtr.CallIsSame(uintptr(extractRawPointer(that))) != 0
}

func (obj *binaryValueImpl) IsEqual(that BinaryValue) bool {
	return obj.rawPtr.CallIsEqual(uintptr(extractRawPointer(that))) != 0
}

func (obj *binaryValueImpl) Copy() BinaryValue {
	return wrapBinaryValue(unsafe.Pointer(obj.rawPtr.CallCopy()))
}

func (obj *binaryValueImpl) GetRawData() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr.CallGetRawData())
}

func (obj *binaryValueImpl) GetSize() int {
	return int(obj.rawPtr.CallGetSize())
}

func (obj *binaryValueImpl) GetData(buffer unsafe.Pointer, bufferSize int, dataOffset int) int {
	return int(obj.rawPtr.CallGetData(uintptr(buffer), uintptr(bufferSize), uintptr(dataOffset)))
}

func (obj *binaryValueImpl) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *binaryValueImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapBinaryValue(ptr unsafe.Pointer) BinaryValue {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFBinaryValueT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &binaryValueImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *binaryValueImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// DictionaryValue Structure representing a dictionary value. Can be used on any process and thread.
type DictionaryValue interface {
	// IsValid Returns true (1) if this object is valid. This object may become invalid if the underlying data is owned by another object (e.g. list or dictionary) and that other object is then modified or destroyed. Do not call any other functions if this function returns false (0).
	IsValid() bool
	// IsOwned Returns true (1) if this object is currently owned by another object.
	IsOwned() bool
	// IsReadOnly Returns true (1) if the values of this object are read-only. Some APIs may expose read-only objects.
	IsReadOnly() bool
	// IsSame Returns true (1) if this object and |that| object have the same underlying data. If true (1) modifications to this object will also affect |that| object and vice-versa.
	IsSame(that DictionaryValue) bool
	// IsEqual Returns true (1) if this object and |that| object have an equivalent underlying value but are not necessarily the same object.
	IsEqual(that DictionaryValue) bool
	Copy(excludeEmptyChildren int32) DictionaryValue
	// GetSize Returns the number of values.
	GetSize() int
	// Clear Removes all values. Returns true (1) on success.
	Clear() int32
	// HasKey Returns true (1) if the current dictionary has a value for the given key.
	HasKey(key string) bool
	// GetKeys Reads all keys for this dictionary into the specified vector.
	GetKeys(keys uintptr) int32
	Remove(key string) int32
	// GetType Returns the value type for the specified key.
	GetType(key string) ValueType
	// GetValue Returns the value at the specified key. For simple types the returned value will copy existing data and modifications to the value will not modify this object. For complex types (binary, dictionary and list) the returned value will reference existing data and modifications to the value will modify this object.
	GetValue(key string) Value
	// GetBool Returns the value at the specified key as type bool.
	GetBool(key string) int32
	// GetInt Returns the value at the specified key as type int.
	GetInt(key string) int32
	// GetDouble Returns the value at the specified key as type double.
	GetDouble(key string) float64
	// GetString Returns the value at the specified key as type string.
	GetString(key string) string
	// GetBinary Returns the value at the specified key as type binary. The returned value will reference existing data.
	GetBinary(key string) BinaryValue
	// GetDictionary Returns the value at the specified key as type dictionary. The returned value will reference existing data and modifications to the value will modify this object.
	GetDictionary(key string) DictionaryValue
	// GetList Returns the value at the specified key as type list. The returned value will reference existing data and modifications to the value will modify this object.
	GetList(key string) ListValue
	// SetValue Sets the value at the specified key. Returns true (1) if the value was set successfully. If |value| represents simple data then the underlying data will be copied and modifications to |value| will not modify this object. If |value| represents complex data (binary, dictionary or list) then the underlying data will be referenced and modifications to |value| will modify this object.
	SetValue(key string, value Value) int32
	// SetNull Sets the value at the specified key as type null. Returns true (1) if the value was set successfully.
	SetNull(key string) int32
	// SetBool Sets the value at the specified key as type bool. Returns true (1) if the value was set successfully.
	SetBool(key string, value int32) int32
	// SetInt Sets the value at the specified key as type int. Returns true (1) if the value was set successfully.
	SetInt(key string, value int32) int32
	// SetDouble Sets the value at the specified key as type double. Returns true (1) if the value was set successfully.
	SetDouble(key string, value float64) int32
	// SetString Sets the value at the specified key as type string. Returns true (1) if the value was set successfully.
	SetString(key string, value string) int32
	// SetBinary Sets the value at the specified key as type binary. Returns true (1) if the value was set successfully. If |value| is currently owned by another object then the value will be copied and the |value| reference will not change. Otherwise, ownership will be transferred to this object and the |value| reference will be invalidated.
	SetBinary(key string, value BinaryValue) int32
	// SetDictionary Sets the value at the specified key as type dict. Returns true (1) if the value was set successfully. If |value| is currently owned by another object then the value will be copied and the |value| reference will not change. Otherwise, ownership will be transferred to this object and the |value| reference will be invalidated.
	SetDictionary(key string, value DictionaryValue) int32
	// SetList Sets the value at the specified key as type list. Returns true (1) if the value was set successfully. If |value| is currently owned by another object then the value will be copied and the |value| reference will not change. Otherwise, ownership will be transferred to this object and the |value| reference will be invalidated.
	SetList(key string, value ListValue) int32
}

type dictionaryValueImpl struct {
	rawPtr *capi.CEFDictionaryValueT
}

func (obj *dictionaryValueImpl) IsValid() bool {
	return obj.rawPtr.CallIsValid() != 0
}

func (obj *dictionaryValueImpl) IsOwned() bool {
	return obj.rawPtr.CallIsOwned() != 0
}

func (obj *dictionaryValueImpl) IsReadOnly() bool {
	return obj.rawPtr.CallIsReadOnly() != 0
}

func (obj *dictionaryValueImpl) IsSame(that DictionaryValue) bool {
	return obj.rawPtr.CallIsSame(uintptr(extractRawPointer(that))) != 0
}

func (obj *dictionaryValueImpl) IsEqual(that DictionaryValue) bool {
	return obj.rawPtr.CallIsEqual(uintptr(extractRawPointer(that))) != 0
}

func (obj *dictionaryValueImpl) Copy(excludeEmptyChildren int32) DictionaryValue {
	return wrapDictionaryValue(unsafe.Pointer(obj.rawPtr.CallCopy(uintptr(excludeEmptyChildren))))
}

func (obj *dictionaryValueImpl) GetSize() int {
	return int(obj.rawPtr.CallGetSize())
}

func (obj *dictionaryValueImpl) Clear() int32 {
	return int32(obj.rawPtr.CallClear())
}

func (obj *dictionaryValueImpl) HasKey(key string) bool {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return obj.rawPtr.CallHasKey(uintptr(unsafe.Pointer(&keyStr))) != 0
}

func (obj *dictionaryValueImpl) GetKeys(keys uintptr) int32 {
	return int32(obj.rawPtr.CallGetKeys(keys))
}

func (obj *dictionaryValueImpl) Remove(key string) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return int32(obj.rawPtr.CallRemove(uintptr(unsafe.Pointer(&keyStr))))
}

func (obj *dictionaryValueImpl) GetType(key string) ValueType {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return ValueType(obj.rawPtr.CallGetType(uintptr(unsafe.Pointer(&keyStr))))
}

func (obj *dictionaryValueImpl) GetValue(key string) Value {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return wrapValue(unsafe.Pointer(obj.rawPtr.CallGetValue(uintptr(unsafe.Pointer(&keyStr)))))
}

func (obj *dictionaryValueImpl) GetBool(key string) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return int32(obj.rawPtr.CallGetBool(uintptr(unsafe.Pointer(&keyStr))))
}

func (obj *dictionaryValueImpl) GetInt(key string) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return int32(obj.rawPtr.CallGetInt(uintptr(unsafe.Pointer(&keyStr))))
}

func (obj *dictionaryValueImpl) GetDouble(key string) float64 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	var fn func(*capi.CEFDictionaryValueT, uintptr) float64
	purego.RegisterFunc(&fn, obj.rawPtr.GetDouble)
	return fn(obj.rawPtr, uintptr(unsafe.Pointer(&keyStr)))
}

func (obj *dictionaryValueImpl) GetString(key string) string {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return goStringUserfree(unsafe.Pointer(obj.rawPtr.CallGetString(uintptr(unsafe.Pointer(&keyStr)))))
}

func (obj *dictionaryValueImpl) GetBinary(key string) BinaryValue {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return wrapBinaryValue(unsafe.Pointer(obj.rawPtr.CallGetBinary(uintptr(unsafe.Pointer(&keyStr)))))
}

func (obj *dictionaryValueImpl) GetDictionary(key string) DictionaryValue {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return wrapDictionaryValue(unsafe.Pointer(obj.rawPtr.CallGetDictionary(uintptr(unsafe.Pointer(&keyStr)))))
}

func (obj *dictionaryValueImpl) GetList(key string) ListValue {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return wrapListValue(unsafe.Pointer(obj.rawPtr.CallGetList(uintptr(unsafe.Pointer(&keyStr)))))
}

func (obj *dictionaryValueImpl) SetValue(key string, value Value) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return int32(obj.rawPtr.CallSetValue(uintptr(unsafe.Pointer(&keyStr)), uintptr(extractRawPointer(value))))
}

func (obj *dictionaryValueImpl) SetNull(key string) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return int32(obj.rawPtr.CallSetNull(uintptr(unsafe.Pointer(&keyStr))))
}

func (obj *dictionaryValueImpl) SetBool(key string, value int32) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return int32(obj.rawPtr.CallSetBool(uintptr(unsafe.Pointer(&keyStr)), uintptr(value)))
}

func (obj *dictionaryValueImpl) SetInt(key string, value int32) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return int32(obj.rawPtr.CallSetInt(uintptr(unsafe.Pointer(&keyStr)), uintptr(value)))
}

func (obj *dictionaryValueImpl) SetDouble(key string, value float64) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	var fn func(*capi.CEFDictionaryValueT, uintptr, float64) uintptr
	purego.RegisterFunc(&fn, obj.rawPtr.SetDouble)
	return int32(fn(obj.rawPtr, uintptr(unsafe.Pointer(&keyStr)), value))
}

func (obj *dictionaryValueImpl) SetString(key string, value string) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	valueStr := cefString(value)
	defer freeCefString(&valueStr)
	return int32(obj.rawPtr.CallSetString(uintptr(unsafe.Pointer(&keyStr)), uintptr(unsafe.Pointer(&valueStr))))
}

func (obj *dictionaryValueImpl) SetBinary(key string, value BinaryValue) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return int32(obj.rawPtr.CallSetBinary(uintptr(unsafe.Pointer(&keyStr)), uintptr(extractRawPointer(value))))
}

func (obj *dictionaryValueImpl) SetDictionary(key string, value DictionaryValue) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return int32(obj.rawPtr.CallSetDictionary(uintptr(unsafe.Pointer(&keyStr)), uintptr(extractRawPointer(value))))
}

func (obj *dictionaryValueImpl) SetList(key string, value ListValue) int32 {
	keyStr := cefString(key)
	defer freeCefString(&keyStr)
	return int32(obj.rawPtr.CallSetList(uintptr(unsafe.Pointer(&keyStr)), uintptr(extractRawPointer(value))))
}

func (obj *dictionaryValueImpl) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *dictionaryValueImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapDictionaryValue(ptr unsafe.Pointer) DictionaryValue {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFDictionaryValueT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &dictionaryValueImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *dictionaryValueImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// ListValue Structure representing a list value. Can be used on any process and thread.
type ListValue interface {
	// IsValid Returns true (1) if this object is valid. This object may become invalid if the underlying data is owned by another object (e.g. list or dictionary) and that other object is then modified or destroyed. Do not call any other functions if this function returns false (0).
	IsValid() bool
	// IsOwned Returns true (1) if this object is currently owned by another object.
	IsOwned() bool
	// IsReadOnly Returns true (1) if the values of this object are read-only. Some APIs may expose read-only objects.
	IsReadOnly() bool
	// IsSame Returns true (1) if this object and |that| object have the same underlying data. If true (1) modifications to this object will also affect |that| object and vice-versa.
	IsSame(that ListValue) bool
	// IsEqual Returns true (1) if this object and |that| object have an equivalent underlying value but are not necessarily the same object.
	IsEqual(that ListValue) bool
	Copy() ListValue
	// SetSize Sets the number of values. If the number of values is expanded all new value slots will default to type null. Returns true (1) on success.
	SetSize(size int) int32
	// GetSize Returns the number of values.
	GetSize() int
	// Clear Removes all values. Returns true (1) on success.
	Clear() int32
	// Remove Removes the value at the specified index.
	Remove(index int) int32
	// GetType Returns the value type at the specified index.
	GetType(index int) ValueType
	// GetValue Returns the value at the specified index. For simple types the returned value will copy existing data and modifications to the value will not modify this object. For complex types (binary, dictionary and list) the returned value will reference existing data and modifications to the value will modify this object.
	GetValue(index int) Value
	// GetBool Returns the value at the specified index as type bool.
	GetBool(index int) int32
	// GetInt Returns the value at the specified index as type int.
	GetInt(index int) int32
	// GetDouble Returns the value at the specified index as type double.
	GetDouble(index int) float64
	// GetString Returns the value at the specified index as type string.
	GetString(index int) string
	// GetBinary Returns the value at the specified index as type binary. The returned value will reference existing data.
	GetBinary(index int) BinaryValue
	// GetDictionary Returns the value at the specified index as type dictionary. The returned value will reference existing data and modifications to the value will modify this object.
	GetDictionary(index int) DictionaryValue
	// GetList Returns the value at the specified index as type list. The returned value will reference existing data and modifications to the value will modify this object.
	GetList(index int) ListValue
	// SetValue Sets the value at the specified index. Returns true (1) if the value was set successfully. If |value| represents simple data then the underlying data will be copied and modifications to |value| will not modify this object. If |value| represents complex data (binary, dictionary or list) then the underlying data will be referenced and modifications to |value| will modify this object.
	SetValue(index int, value Value) int32
	// SetNull Sets the value at the specified index as type null. Returns true (1) if the value was set successfully.
	SetNull(index int) int32
	// SetBool Sets the value at the specified index as type bool. Returns true (1) if the value was set successfully.
	SetBool(index int, value int32) int32
	// SetInt Sets the value at the specified index as type int. Returns true (1) if the value was set successfully.
	SetInt(index int, value int32) int32
	// SetDouble Sets the value at the specified index as type double. Returns true (1) if the value was set successfully.
	SetDouble(index int, value float64) int32
	// SetString Sets the value at the specified index as type string. Returns true (1) if the value was set successfully.
	SetString(index int, value string) int32
	// SetBinary Sets the value at the specified index as type binary. Returns true (1) if the value was set successfully. If |value| is currently owned by another object then the value will be copied and the |value| reference will not change. Otherwise, ownership will be transferred to this object and the |value| reference will be invalidated.
	SetBinary(index int, value BinaryValue) int32
	// SetDictionary Sets the value at the specified index as type dict. Returns true (1) if the value was set successfully. If |value| is currently owned by another object then the value will be copied and the |value| reference will not change. Otherwise, ownership will be transferred to this object and the |value| reference will be invalidated.
	SetDictionary(index int, value DictionaryValue) int32
	// SetList Sets the value at the specified index as type list. Returns true (1) if the value was set successfully. If |value| is currently owned by another object then the value will be copied and the |value| reference will not change. Otherwise, ownership will be transferred to this object and the |value| reference will be invalidated.
	SetList(index int, value ListValue) int32
}

type listValueImpl struct {
	rawPtr *capi.CEFListValueT
}

func (obj *listValueImpl) IsValid() bool {
	return obj.rawPtr.CallIsValid() != 0
}

func (obj *listValueImpl) IsOwned() bool {
	return obj.rawPtr.CallIsOwned() != 0
}

func (obj *listValueImpl) IsReadOnly() bool {
	return obj.rawPtr.CallIsReadOnly() != 0
}

func (obj *listValueImpl) IsSame(that ListValue) bool {
	return obj.rawPtr.CallIsSame(uintptr(extractRawPointer(that))) != 0
}

func (obj *listValueImpl) IsEqual(that ListValue) bool {
	return obj.rawPtr.CallIsEqual(uintptr(extractRawPointer(that))) != 0
}

func (obj *listValueImpl) Copy() ListValue {
	return wrapListValue(unsafe.Pointer(obj.rawPtr.CallCopy()))
}

func (obj *listValueImpl) SetSize(size int) int32 {
	return int32(obj.rawPtr.CallSetSize(uintptr(size)))
}

func (obj *listValueImpl) GetSize() int {
	return int(obj.rawPtr.CallGetSize())
}

func (obj *listValueImpl) Clear() int32 {
	return int32(obj.rawPtr.CallClear())
}

func (obj *listValueImpl) Remove(index int) int32 {
	return int32(obj.rawPtr.CallRemove(uintptr(index)))
}

func (obj *listValueImpl) GetType(index int) ValueType {
	return ValueType(obj.rawPtr.CallGetType(uintptr(index)))
}

func (obj *listValueImpl) GetValue(index int) Value {
	return wrapValue(unsafe.Pointer(obj.rawPtr.CallGetValue(uintptr(index))))
}

func (obj *listValueImpl) GetBool(index int) int32 {
	return int32(obj.rawPtr.CallGetBool(uintptr(index)))
}

func (obj *listValueImpl) GetInt(index int) int32 {
	return int32(obj.rawPtr.CallGetInt(uintptr(index)))
}

func (obj *listValueImpl) GetDouble(index int) float64 {
	var fn func(*capi.CEFListValueT, uintptr) float64
	purego.RegisterFunc(&fn, obj.rawPtr.GetDouble)
	return fn(obj.rawPtr, uintptr(index))
}

func (obj *listValueImpl) GetString(index int) string {
	return goStringUserfree(unsafe.Pointer(obj.rawPtr.CallGetString(uintptr(index))))
}

func (obj *listValueImpl) GetBinary(index int) BinaryValue {
	return wrapBinaryValue(unsafe.Pointer(obj.rawPtr.CallGetBinary(uintptr(index))))
}

func (obj *listValueImpl) GetDictionary(index int) DictionaryValue {
	return wrapDictionaryValue(unsafe.Pointer(obj.rawPtr.CallGetDictionary(uintptr(index))))
}

func (obj *listValueImpl) GetList(index int) ListValue {
	return wrapListValue(unsafe.Pointer(obj.rawPtr.CallGetList(uintptr(index))))
}

func (obj *listValueImpl) SetValue(index int, value Value) int32 {
	return int32(obj.rawPtr.CallSetValue(uintptr(index), uintptr(extractRawPointer(value))))
}

func (obj *listValueImpl) SetNull(index int) int32 {
	return int32(obj.rawPtr.CallSetNull(uintptr(index)))
}

func (obj *listValueImpl) SetBool(index int, value int32) int32 {
	return int32(obj.rawPtr.CallSetBool(uintptr(index), uintptr(value)))
}

func (obj *listValueImpl) SetInt(index int, value int32) int32 {
	return int32(obj.rawPtr.CallSetInt(uintptr(index), uintptr(value)))
}

func (obj *listValueImpl) SetDouble(index int, value float64) int32 {
	var fn func(*capi.CEFListValueT, uintptr, float64) uintptr
	purego.RegisterFunc(&fn, obj.rawPtr.SetDouble)
	return int32(fn(obj.rawPtr, uintptr(index), value))
}

func (obj *listValueImpl) SetString(index int, value string) int32 {
	valueStr := cefString(value)
	defer freeCefString(&valueStr)
	return int32(obj.rawPtr.CallSetString(uintptr(index), uintptr(unsafe.Pointer(&valueStr))))
}

func (obj *listValueImpl) SetBinary(index int, value BinaryValue) int32 {
	return int32(obj.rawPtr.CallSetBinary(uintptr(index), uintptr(extractRawPointer(value))))
}

func (obj *listValueImpl) SetDictionary(index int, value DictionaryValue) int32 {
	return int32(obj.rawPtr.CallSetDictionary(uintptr(index), uintptr(extractRawPointer(value))))
}

func (obj *listValueImpl) SetList(index int, value ListValue) int32 {
	return int32(obj.rawPtr.CallSetList(uintptr(index), uintptr(extractRawPointer(value))))
}

func (obj *listValueImpl) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *listValueImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapListValue(ptr unsafe.Pointer) ListValue {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFListValueT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &listValueImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *listValueImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// ValueCreate Creates a new object.
func ValueCreate() Value {
	return wrapValue(capi.CEFValueCreate())
}

// BinaryValueCreate Creates a new object that is not owned by any other object. The specified |data| will be copied.
func BinaryValueCreate(data unsafe.Pointer, dataSize int) BinaryValue {
	return wrapBinaryValue(capi.CEFBinaryValueCreate(data, uintptr(dataSize)))
}

// DictionaryValueCreate Creates a new object that is not owned by any other object.
func DictionaryValueCreate() DictionaryValue {
	return wrapDictionaryValue(capi.CEFDictionaryValueCreate())
}

// ListValueCreate Creates a new object that is not owned by any other object.
func ListValueCreate() ListValue {
	return wrapListValue(capi.CEFListValueCreate())
}
