// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// PrintDialogCallback Callback structure for asynchronous continuation of print dialog requests.
type PrintDialogCallback = portin.PrintDialogCallback

// printDialogCallbackImpl is a reverse wrapper for a CEF-owned PrintDialogCallback pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type printDialogCallbackImpl struct {
	rawPtr      *capi.CEFPrintDialogCallbackT
	releaseOnce sync.Once
}

func (obj *printDialogCallbackImpl) Cont(settings PrintSettings) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallCont(uintptr(extractRawPointer(settings)))
	runtime.KeepAlive(obj)
}

func (obj *printDialogCallbackImpl) Cancel() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallCancel()
	runtime.KeepAlive(obj)
}

func (obj *printDialogCallbackImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *printDialogCallbackImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

func wrapPrintDialogCallback(ptr unsafe.Pointer) PrintDialogCallback {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFPrintDialogCallbackT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &printDialogCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*printDialogCallbackImpl).Release)
	return impl
}

// PrintJobCallback Callback structure for asynchronous continuation of print job requests.
type PrintJobCallback = portin.PrintJobCallback

// printJobCallbackImpl is a reverse wrapper for a CEF-owned PrintJobCallback pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type printJobCallbackImpl struct {
	rawPtr      *capi.CEFPrintJobCallbackT
	releaseOnce sync.Once
}

func (obj *printJobCallbackImpl) Cont() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallCont()
	runtime.KeepAlive(obj)
}

func (obj *printJobCallbackImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *printJobCallbackImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

func wrapPrintJobCallback(ptr unsafe.Pointer) PrintJobCallback {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFPrintJobCallbackT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &printJobCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*printJobCallbackImpl).Release)
	return impl
}

// PrintHandler Implement this structure to handle printing on Linux. Each browser will have only one print job in progress at a time. The functions of this structure will be called on the browser process UI thread.
type PrintHandler = portin.PrintHandler

// printHandlerWrapper wraps a user-provided PrintHandler implementation together
// with the raw CEF struct pointer allocated by NewPrintHandler.  It satisfies the
// PrintHandler interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type printHandlerWrapper struct {
	PrintHandler // embed user impl for interface delegation
	rawPtr       *capi.CEFPrintHandlerT
}

func (w *printHandlerWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewPrintHandler creates a CEF handler backed by the given implementation.
func NewPrintHandler(impl PrintHandler) PrintHandler {
	if isNilImpl(impl) {
		return nil
	}
	r := new(capi.CEFPrintHandlerT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnPrintStart(newCEFCallback(unsafe.Pointer(r), func(self uintptr, arg0 uintptr) {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		impl.OnPrintStart(browser)
	}))

	r.OverrideOnPrintSettings(newCEFCallback(unsafe.Pointer(r), func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr) {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		settings := wrapPrintSettings(unsafe.Pointer(arg1))
		getDefaults := int32(arg2)
		impl.OnPrintSettings(browser, settings, getDefaults)
	}))

	r.OverrideOnPrintDialog(newCEFCallback(unsafe.Pointer(r), func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		hasSelection := int32(arg1)
		callback := wrapPrintDialogCallback(unsafe.Pointer(arg2))
		return uintptr(impl.OnPrintDialog(browser, hasSelection, callback))
	}))

	r.OverrideOnPrintJob(newCEFCallback(unsafe.Pointer(r), func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		documentName := goString(unsafe.Pointer(arg1))
		pdfFilePath := goString(unsafe.Pointer(arg2))
		callback := wrapPrintJobCallback(unsafe.Pointer(arg3))
		return uintptr(impl.OnPrintJob(browser, documentName, pdfFilePath, callback))
	}))

	r.OverrideOnPrintReset(newCEFCallback(unsafe.Pointer(r), func(self uintptr, arg0 uintptr) {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		impl.OnPrintReset(browser)
	}))

	r.OverrideGetPdfPaperSize(newCEFCallback(unsafe.Pointer(r), func(self uintptr, arg0 uintptr, arg1 uintptr) uintptr {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		deviceUnitsPerInch := int32(arg1)
		return uintptr(impl.GetPdfPaperSize(browser, deviceUnitsPerInch))
	}))

	w := &printHandlerWrapper{rawPtr: r}
	w.PrintHandler = impl
	return w
}

// printHandlerImpl is a reverse wrapper for a CEF-owned PrintHandler pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type printHandlerImpl struct {
	rawPtr      *capi.CEFPrintHandlerT
	releaseOnce sync.Once
}

func (obj *printHandlerImpl) OnPrintStart(browser Browser) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallOnPrintStart(uintptr(extractRawPointer(browser)))
	runtime.KeepAlive(obj)
}

func (obj *printHandlerImpl) OnPrintSettings(browser Browser, settings PrintSettings, getDefaults int32) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallOnPrintSettings(uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(settings)), uintptr(getDefaults))
	runtime.KeepAlive(obj)
}

func (obj *printHandlerImpl) OnPrintDialog(browser Browser, hasSelection int32, callback PrintDialogCallback) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallOnPrintDialog(uintptr(extractRawPointer(browser)), uintptr(hasSelection), uintptr(extractRawPointer(callback)))
	runtime.KeepAlive(obj)
	return int32(ret)
}

func (obj *printHandlerImpl) OnPrintJob(browser Browser, documentName string, pdfFilePath string, callback PrintJobCallback) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	documentNameStr := cefString(documentName)
	defer freeCefString(&documentNameStr)
	pdfFilePathStr := cefString(pdfFilePath)
	defer freeCefString(&pdfFilePathStr)
	ret := rawPtr.CallOnPrintJob(uintptr(extractRawPointer(browser)), uintptr(unsafe.Pointer(&documentNameStr)), uintptr(unsafe.Pointer(&pdfFilePathStr)), uintptr(extractRawPointer(callback)))
	runtime.KeepAlive(obj)
	return int32(ret)
}

func (obj *printHandlerImpl) OnPrintReset(browser Browser) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallOnPrintReset(uintptr(extractRawPointer(browser)))
	runtime.KeepAlive(obj)
}

func (obj *printHandlerImpl) GetPdfPaperSize(browser Browser, deviceUnitsPerInch int32) uintptr {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetPdfPaperSize(uintptr(extractRawPointer(browser)), uintptr(deviceUnitsPerInch))
	runtime.KeepAlive(obj)
	return uintptr(ret)
}

func (obj *printHandlerImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *printHandlerImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

// wrapPrintHandler wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapPrintHandler(ptr unsafe.Pointer) PrintHandler {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFPrintHandlerT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &printHandlerImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*printHandlerImpl).Release)
	return impl
}
