// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"unsafe"

	"github.com/ebitengine/purego"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// FocusHandler Implement this structure to handle events related to focus. The functions of this structure will be called on the UI thread.
type FocusHandler interface {
	// OnTakeFocus Called when the browser component is about to loose focus. For instance, if focus was on the last HTML element and the user pressed the TAB key. |next| will be true (1) if the browser is giving focus to the next component and false (0) if the browser is giving focus to the previous component.
	OnTakeFocus(browser Browser, next int32)
	// OnSetFocus Called when the browser component is requesting focus. |source| indicates where the focus request is originating from. Return false (0) to allow the focus to be set or true (1) to cancel setting the focus.
	OnSetFocus(browser Browser, source FocusSource) int32
	// OnGotFocus Called when the browser component has received focus.
	OnGotFocus(browser Browser)
}

// NewFocusHandler creates a CEF handler backed by the given implementation.
// The returned pointer can be passed to CEF functions that expect this handler type.
func NewFocusHandler(impl FocusHandler) unsafe.Pointer {
	r := new(raw.CEFFocusHandlerT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnTakeFocus(purego.NewCallback(func(_ uintptr, _ uintptr) {
		// TODO: unmarshal args, call impl.OnTakeFocus(...)
	}))

	r.OverrideOnSetFocus(purego.NewCallback(func(_ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.OnSetFocus(...), marshal return
		return 0
	}))

	r.OverrideOnGotFocus(purego.NewCallback(func(_ uintptr) {
		// TODO: unmarshal args, call impl.OnGotFocus(...)
	}))

	return unsafe.Pointer(r)
}
