// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// ProcessMessage Structure representing a message. Can be used on any process and thread.
type ProcessMessage interface {
	// IsValid Returns true (1) if this object is valid. Do not call any other functions if this function returns false (0).
	IsValid() bool
	// IsReadOnly Returns true (1) if the values of this object are read-only. Some APIs may expose read-only objects.
	IsReadOnly() bool
	Copy() ProcessMessage
	// GetName Returns the message name.
	GetName() string
	// GetArgumentList Returns the list of arguments. Returns nullptr when message contains a shared memory region.
	GetArgumentList() ListValue
	// GetSharedMemoryRegion Returns the shared memory region. Returns nullptr when message contains an argument list.
	GetSharedMemoryRegion() SharedMemoryRegion
}

type processMessageImpl struct {
	rawPtr *raw.CEFProcessMessageT
}

func (obj *processMessageImpl) IsValid() bool {
	return obj.rawPtr.CallIsValid() != 0
}

func (obj *processMessageImpl) IsReadOnly() bool {
	return obj.rawPtr.CallIsReadOnly() != 0
}

func (obj *processMessageImpl) Copy() ProcessMessage {
	ret := obj.rawPtr.CallCopy()
	_ = ret
	return nil
}

func (obj *processMessageImpl) GetName() string {
	ret := obj.rawPtr.CallGetName()
	_ = ret
	return ""
}

func (obj *processMessageImpl) GetArgumentList() ListValue {
	ret := obj.rawPtr.CallGetArgumentList()
	_ = ret
	return nil
}

func (obj *processMessageImpl) GetSharedMemoryRegion() SharedMemoryRegion {
	ret := obj.rawPtr.CallGetSharedMemoryRegion()
	_ = ret
	return nil
}

// Release releases the underlying CEF object.
func (obj *processMessageImpl) Release() {
	base := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapProcessMessage(ptr unsafe.Pointer) ProcessMessage {
	if ptr == nil {
		return nil
	}
	r := (*raw.CEFProcessMessageT)(ptr)
	base := (*raw.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &processMessageImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *processMessageImpl) {
		b := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// ProcessMessageCreate Create a new cef_process_message_t object with the specified name.
func ProcessMessageCreate(name string) uintptr {
	// TODO: marshal args, call raw.CEFProcessMessageCreate(...), marshal return
	_ = raw.CEFProcessMessageCreate
	return 0
}
