// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"unsafe"

	"github.com/ebitengine/purego"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// ResponseFilter Implement this structure to filter resource response content. The functions of this structure will be called on the browser process IO thread.
type ResponseFilter interface {
	// InitFilter Initialize the response filter. Will only be called a single time. The filter will not be installed if this function returns false (0).
	InitFilter() int32
	Filter(dataIn unsafe.Pointer, dataInSize int, dataInRead *int, dataOut unsafe.Pointer, dataOutSize int, dataOutWritten *int) ResponseFilterStatus
}

// NewResponseFilter creates a CEF handler backed by the given implementation.
// The returned pointer can be passed to CEF functions that expect this handler type.
func NewResponseFilter(impl ResponseFilter) unsafe.Pointer {
	r := new(raw.CEFResponseFilterT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideInitFilter(purego.NewCallback(func() uintptr {
		// TODO: unmarshal args, call impl.InitFilter(...), marshal return
		return 0
	}))

	r.OverrideFilter(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.Filter(...), marshal return
		return 0
	}))

	return unsafe.Pointer(r)
}
