// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/bnema/purego"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// BrowserProcessHandler Structure used to implement browser process callbacks. The functions of this structure will be called on the browser process main thread unless otherwise indicated.
type BrowserProcessHandler = portin.BrowserProcessHandler

// browserProcessHandlerWrapper wraps a user-provided BrowserProcessHandler implementation together
// with the raw CEF struct pointer allocated by NewBrowserProcessHandler.  It satisfies the
// BrowserProcessHandler interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type browserProcessHandlerWrapper struct {
	BrowserProcessHandler // embed user impl for interface delegation
	rawPtr                *capi.CEFBrowserProcessHandlerT
}

func (w *browserProcessHandlerWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewBrowserProcessHandler creates a CEF handler backed by the given implementation.
func NewBrowserProcessHandler(impl BrowserProcessHandler) BrowserProcessHandler {
	if isNilImpl(impl) {
		return nil
	}
	r := new(capi.CEFBrowserProcessHandlerT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnRegisterCustomPreferences(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr) {
		type_ := PreferencesType(arg0)
		registrar := wrapPreferenceRegistrar(unsafe.Pointer(arg1))
		impl.OnRegisterCustomPreferences(type_, registrar)
	}))

	r.OverrideOnContextInitialized(purego.NewCallback(func(self uintptr) {
		impl.OnContextInitialized()
	}))

	r.OverrideOnBeforeChildProcessLaunch(purego.NewCallback(func(self uintptr, arg0 uintptr) {
		commandLine := wrapCommandLine(unsafe.Pointer(arg0))
		impl.OnBeforeChildProcessLaunch(commandLine)
	}))

	r.OverrideOnAlreadyRunningAppRelaunch(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr) uintptr {
		commandLine := wrapCommandLine(unsafe.Pointer(arg0))
		currentDirectory := goString(unsafe.Pointer(arg1))
		return uintptr(impl.OnAlreadyRunningAppRelaunch(commandLine, currentDirectory))
	}))

	r.OverrideOnScheduleMessagePumpWork(purego.NewCallback(func(self uintptr, arg0 int64) {
		delayMs := arg0
		impl.OnScheduleMessagePumpWork(delayMs)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetDefaultClientPtr unsafe.Pointer
	if h := impl.GetDefaultClient(); h != nil {
		cachedGetDefaultClientPtr = extractOrWrapRawPointer(h, func() any {
			return NewRawClient(h)
		})
	}
	r.OverrideGetDefaultClient(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetDefaultClientPtr != nil {
			addRef(cachedGetDefaultClientPtr)
		}
		return uintptr(cachedGetDefaultClientPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetDefaultRequestContextHandlerPtr unsafe.Pointer
	if h := impl.GetDefaultRequestContextHandler(); h != nil {
		cachedGetDefaultRequestContextHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewRequestContextHandler(h)
		})
	}
	r.OverrideGetDefaultRequestContextHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetDefaultRequestContextHandlerPtr != nil {
			addRef(cachedGetDefaultRequestContextHandlerPtr)
		}
		return uintptr(cachedGetDefaultRequestContextHandlerPtr)
	}))

	w := &browserProcessHandlerWrapper{rawPtr: r}
	w.BrowserProcessHandler = impl
	return w
}

// browserProcessHandlerImpl is a reverse wrapper for a CEF-owned BrowserProcessHandler pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type browserProcessHandlerImpl struct {
	rawPtr                        *capi.CEFBrowserProcessHandlerT
	releaseOnce                   sync.Once
	onScheduleMessagePumpWorkOnce sync.Once
	onScheduleMessagePumpWorkFunc func(*capi.CEFBrowserProcessHandlerT, int64)
}

func (obj *browserProcessHandlerImpl) OnRegisterCustomPreferences(type_ PreferencesType, registrar PreferenceRegistrar) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallOnRegisterCustomPreferences(uintptr(type_), uintptr(extractRawPointer(registrar)))
}

func (obj *browserProcessHandlerImpl) OnContextInitialized() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallOnContextInitialized()
}

func (obj *browserProcessHandlerImpl) OnBeforeChildProcessLaunch(commandLine CommandLine) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallOnBeforeChildProcessLaunch(uintptr(extractRawPointer(commandLine)))
}

func (obj *browserProcessHandlerImpl) OnAlreadyRunningAppRelaunch(commandLine CommandLine, currentDirectory string) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	currentDirectoryStr := cefString(currentDirectory)
	defer freeCefString(&currentDirectoryStr)
	ret := rawPtr.CallOnAlreadyRunningAppRelaunch(uintptr(extractRawPointer(commandLine)), uintptr(unsafe.Pointer(&currentDirectoryStr)))
	return int32(ret)
}

func (obj *browserProcessHandlerImpl) OnScheduleMessagePumpWork(delayMs int64) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	obj.onScheduleMessagePumpWorkOnce.Do(func() {
		registerTypedCallback(&obj.onScheduleMessagePumpWorkFunc, rawPtr.OnScheduleMessagePumpWork)
	})
	obj.onScheduleMessagePumpWorkFunc(rawPtr, delayMs)
}

func (obj *browserProcessHandlerImpl) GetDefaultClient() RawClient {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetDefaultClient()
	return wrapRawClient(unsafe.Pointer(ret))
}

func (obj *browserProcessHandlerImpl) GetDefaultRequestContextHandler() RequestContextHandler {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetDefaultRequestContextHandler()
	return wrapRequestContextHandler(unsafe.Pointer(ret))
}

func (obj *browserProcessHandlerImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *browserProcessHandlerImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

// wrapBrowserProcessHandler wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapBrowserProcessHandler(ptr unsafe.Pointer) BrowserProcessHandler {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFBrowserProcessHandlerT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &browserProcessHandlerImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*browserProcessHandlerImpl).Release)
	return impl
}
