// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/ebitengine/purego"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// SelectClientCertificateCallback Callback structure used to select a client certificate for authentication.
type SelectClientCertificateCallback interface {
	Select(cert X509Certificate)
}

type selectClientCertificateCallbackImpl struct {
	rawPtr *raw.CEFSelectClientCertificateCallbackT
}

func (obj *selectClientCertificateCallbackImpl) Select(cert X509Certificate) {
	obj.rawPtr.CallSelect(uintptr(0) /* cert */)
}

// Release releases the underlying CEF object.
func (obj *selectClientCertificateCallbackImpl) Release() {
	base := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapSelectClientCertificateCallback(ptr unsafe.Pointer) SelectClientCertificateCallback {
	if ptr == nil {
		return nil
	}
	r := (*raw.CEFSelectClientCertificateCallbackT)(ptr)
	base := (*raw.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &selectClientCertificateCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *selectClientCertificateCallbackImpl) {
		b := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// RequestHandler Implement this structure to handle events related to browser requests. The functions of this structure will be called on the thread indicated.
type RequestHandler interface {
	// OnBeforeBrowse Called on the UI thread before browser navigation. Return true (1) to cancel the navigation or false (0) to allow the navigation to proceed. The |request| object cannot be modified in this callback. cef_load_handler_t::OnLoadingStateChange will be called twice in all cases. If the navigation is allowed cef_load_handler_t::OnLoadStart and cef_load_handler_t::OnLoadEnd will be called. If the navigation is canceled cef_load_handler_t::OnLoadError will be called with an |errorCode| value of ERR_ABORTED. The |user_gesture| value will be true (1) if the browser navigated via explicit user gesture (e.g. clicking a link) or false (0) if it navigated automatically (e.g. via the DomContentLoaded event).
	OnBeforeBrowse(browser Browser, frame Frame, request Request, userGesture int32, isRedirect int32) bool
	// OnOpenUrlfromTab Called on the UI thread before OnBeforeBrowse in certain limited cases where navigating a new or different browser might be desirable. This includes user-initiated navigation that might open in a special way (e.g. links clicked via middle-click or ctrl + left-click) and certain types of cross-origin navigation initiated from the renderer process (e.g. navigating the top-level frame to/from a file URL). The |browser| and |frame| values represent the source of the navigation. The |target_disposition| value indicates where the user intended to navigate the browser based on standard Chromium behaviors (e.g. current tab, new tab, etc). The |user_gesture| value will be true (1) if the browser navigated via explicit user gesture (e.g. clicking a link) or false (0) if it navigated automatically (e.g. via the DomContentLoaded event). Return true (1) to cancel the navigation or false (0) to allow the navigation to proceed in the source browser's top-level frame.
	OnOpenUrlfromTab(browser Browser, frame Frame, targetURL string, targetDisposition WindowOpenDisposition, userGesture int32) int32
	// GetResourceRequestHandler Called on the browser process IO thread before a resource request is initiated. The |browser| and |frame| values represent the source of the request. |request| represents the request contents and cannot be modified in this callback. |is_navigation| will be true (1) if the resource request is a navigation. |is_download| will be true (1) if the resource request is a download. |request_initiator| is the origin (scheme + domain) of the page that initiated the request. Set |disable_default_handling| to true (1) to disable default handling of the request, in which case it will need to be handled via cef_resource_request_handler_t::GetResourceHandler or it will be canceled. To allow the resource load to proceed with default handling return NULL. To specify a handler for the resource return a cef_resource_request_handler_t object. If this callback returns NULL the same function will be called on the associated cef_request_context_handler_t, if any.
	GetResourceRequestHandler(browser Browser, frame Frame, request Request, isNavigation int32, isDownload int32, requestInitiator string, disableDefaultHandling unsafe.Pointer) ResourceRequestHandler
	// GetAuthCredentials Called on the IO thread when the browser needs credentials from the user. |origin_url| is the origin making this authentication request. |isProxy| indicates whether the host is a proxy server. |host| contains the hostname and |port| contains the port number. |realm| is the realm of the challenge and may be NULL. |scheme| is the authentication scheme used, such as "basic" or "digest", and will be NULL if the source of the request is an FTP server. Return true (1) to continue the request and call cef_auth_callback_t::cont() either in this function or at a later time when the authentication information is available. Return false (0) to cancel the request immediately.
	GetAuthCredentials(browser Browser, originURL string, isproxy int32, host string, port int32, realm string, scheme string, callback AuthCallback) int32
	// OnCertificateError Called on the UI thread to handle requests for URLs with an invalid SSL certificate. Return true (1) and call cef_callback_t functions either in this function or at a later time to continue or cancel the request. Return false (0) to cancel the request immediately. If cef_settings_t.ignore_certificate_errors is set all invalid certificates will be accepted without calling this function.
	OnCertificateError(browser Browser, certError Errorcode, requestURL string, sslInfo Sslinfo, callback Callback) int32
	// OnSelectClientCertificate Called on the UI thread when a client certificate is being requested for authentication. Return false (0) to use the default behavior.  If the |certificates| list is not NULL the default behavior will be to display a dialog for certificate selection. If the |certificates| list is NULL then the default behavior will be not to show a dialog and it will continue without using any certificate. Return true (1) and call cef_select_client_certificate_callback_t::Select either in this function or at a later time to select a certificate. Do not call Select or call it with NULL to continue without using any certificate. |isProxy| indicates whether the host is an HTTPS proxy or the origin server. |host| and |port| contains the hostname and port of the SSL server. |certificates| is the list of certificates to choose from; this list has already been pruned by Chromium so that it only contains certificates from issuers that the server trusts.
	OnSelectClientCertificate(browser Browser, isproxy int32, host string, port int32, certificatescount int, certificates unsafe.Pointer, callback SelectClientCertificateCallback) int32
	// OnRenderViewReady Called on the browser process UI thread when the render view associated with |browser| is ready to receive/handle IPC messages in the render process.
	OnRenderViewReady(browser Browser)
	// OnRenderProcessUnresponsive Called on the browser process UI thread when the render process is unresponsive as indicated by a lack of input event processing for at least 15 seconds. Return false (0) for the default behavior which is to continue waiting with Alloy style or display of the "Page unresponsive" dialog with Chrome style. Return true (1) and don't execute the callback to continue waiting without display of the Chrome style dialog. Return true (1) and call cef_unresponsive_process_callback_t::Wait either in this function or at a later time to reset the wait timer. In cases where you continue waiting there may be another call to this function if the process remains unresponsive. Return true (1) and call cef_unresponsive_process_callback_t::Terminate either in this function or at a later time to terminate the unresponsive process, resulting in a call to OnRenderProcessTerminated. OnRenderProcessResponsive will be called if the process becomes responsive after this function is called. This functionality depends on the hang monitor which can be disabled by passing the `--disable-hang-monitor` command-line flag.
	OnRenderProcessUnresponsive(browser Browser, callback UnresponsiveProcessCallback) int32
	// OnRenderProcessResponsive Called on the browser process UI thread when the render process becomes responsive after previously being unresponsive. See documentation on OnRenderProcessUnresponsive.
	OnRenderProcessResponsive(browser Browser)
	// OnRenderProcessTerminated Called on the browser process UI thread when the render process terminates unexpectedly. |status| indicates how the process terminated. |error_code| and |error_string| represent the error that would be displayed in Chrome's "Aw, Snap!" view. Possible |error_code| values include cef_resultcode_t non-normal exit values and platform-specific crash values (for example, a Posix signal or Windows hardware exception).
	OnRenderProcessTerminated(browser Browser, status TerminationStatus, errorCode int32, errorString string)
	// OnDocumentAvailableInMainFrame Called on the browser process UI thread when the window.document object of the main frame has been created.
	OnDocumentAvailableInMainFrame(browser Browser)
}

// NewRequestHandler creates a CEF handler backed by the given implementation.
// The returned pointer can be passed to CEF functions that expect this handler type.
func NewRequestHandler(impl RequestHandler) unsafe.Pointer {
	r := new(raw.CEFRequestHandlerT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnBeforeBrowse(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.OnBeforeBrowse(...), marshal return
		return 0
	}))

	r.OverrideOnOpenUrlfromTab(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.OnOpenUrlfromTab(...), marshal return
		return 0
	}))

	r.OverrideGetResourceRequestHandler(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.GetResourceRequestHandler(...), marshal return
		return 0
	}))

	r.OverrideGetAuthCredentials(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.GetAuthCredentials(...), marshal return
		return 0
	}))

	r.OverrideOnCertificateError(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.OnCertificateError(...), marshal return
		return 0
	}))

	r.OverrideOnSelectClientCertificate(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.OnSelectClientCertificate(...), marshal return
		return 0
	}))

	r.OverrideOnRenderViewReady(purego.NewCallback(func(_ uintptr) {
		// TODO: unmarshal args, call impl.OnRenderViewReady(...)
	}))

	r.OverrideOnRenderProcessUnresponsive(purego.NewCallback(func(_ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.OnRenderProcessUnresponsive(...), marshal return
		return 0
	}))

	r.OverrideOnRenderProcessResponsive(purego.NewCallback(func(_ uintptr) {
		// TODO: unmarshal args, call impl.OnRenderProcessResponsive(...)
	}))

	r.OverrideOnRenderProcessTerminated(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr, _ uintptr) {
		// TODO: unmarshal args, call impl.OnRenderProcessTerminated(...)
	}))

	r.OverrideOnDocumentAvailableInMainFrame(purego.NewCallback(func(_ uintptr) {
		// TODO: unmarshal args, call impl.OnDocumentAvailableInMainFrame(...)
	}))

	return unsafe.Pointer(r)
}
