// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// CommandHandler Implement this structure to handle events related to commands. The functions of this structure will be called on the UI thread.
type CommandHandler = portin.CommandHandler

// commandHandlerWrapper wraps a user-provided CommandHandler implementation together
// with the raw CEF struct pointer allocated by NewCommandHandler.  It satisfies the
// CommandHandler interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type commandHandlerWrapper struct {
	CommandHandler // embed user impl for interface delegation
	rawPtr         *capi.CEFCommandHandlerT
}

func (w *commandHandlerWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewCommandHandler creates a CEF handler backed by the given implementation.
func NewCommandHandler(impl CommandHandler) CommandHandler {
	r := new(capi.CEFCommandHandlerT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnChromeCommand(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		commandID := int32(arg1)
		disposition := WindowOpenDisposition(arg2)
		return uintptr(impl.OnChromeCommand(browser, commandID, disposition))
	}))

	r.OverrideIsChromeAppMenuItemVisible(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr) uintptr {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		commandID := int32(arg1)
		if impl.IsChromeAppMenuItemVisible(browser, commandID) {
			return 1
		}
		return 0
	}))

	r.OverrideIsChromeAppMenuItemEnabled(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr) uintptr {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		commandID := int32(arg1)
		if impl.IsChromeAppMenuItemEnabled(browser, commandID) {
			return 1
		}
		return 0
	}))

	r.OverrideIsChromePageActionIconVisible(purego.NewCallback(func(self uintptr, arg0 uintptr) uintptr {
		iconType := ChromePageActionIconType(arg0)
		if impl.IsChromePageActionIconVisible(iconType) {
			return 1
		}
		return 0
	}))

	r.OverrideIsChromeToolbarButtonVisible(purego.NewCallback(func(self uintptr, arg0 uintptr) uintptr {
		buttonType := ChromeToolbarButtonType(arg0)
		if impl.IsChromeToolbarButtonVisible(buttonType) {
			return 1
		}
		return 0
	}))

	w := &commandHandlerWrapper{rawPtr: r}
	w.CommandHandler = impl
	return w
}

type commandHandlerImpl struct {
	rawPtr *capi.CEFCommandHandlerT
}

func (obj *commandHandlerImpl) OnChromeCommand(browser Browser, commandID int32, disposition WindowOpenDisposition) int32 {
	ret := obj.rawPtr.CallOnChromeCommand(uintptr(extractRawPointer(browser)), uintptr(commandID), uintptr(disposition))
	return int32(ret)
}

func (obj *commandHandlerImpl) IsChromeAppMenuItemVisible(browser Browser, commandID int32) bool {
	ret := obj.rawPtr.CallIsChromeAppMenuItemVisible(uintptr(extractRawPointer(browser)), uintptr(commandID))
	return ret != 0
}

func (obj *commandHandlerImpl) IsChromeAppMenuItemEnabled(browser Browser, commandID int32) bool {
	ret := obj.rawPtr.CallIsChromeAppMenuItemEnabled(uintptr(extractRawPointer(browser)), uintptr(commandID))
	return ret != 0
}

func (obj *commandHandlerImpl) IsChromePageActionIconVisible(iconType ChromePageActionIconType) bool {
	ret := obj.rawPtr.CallIsChromePageActionIconVisible(uintptr(iconType))
	return ret != 0
}

func (obj *commandHandlerImpl) IsChromeToolbarButtonVisible(buttonType ChromeToolbarButtonType) bool {
	ret := obj.rawPtr.CallIsChromeToolbarButtonVisible(uintptr(buttonType))
	return ret != 0
}

func (obj *commandHandlerImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *commandHandlerImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

// wrapCommandHandler wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapCommandHandler(ptr unsafe.Pointer) CommandHandler {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFCommandHandlerT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &commandHandlerImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *commandHandlerImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}
