// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// Thread A simple thread abstraction that establishes a message loop on a new thread. The consumer uses cef_task_runner_t to execute code on the thread's message loop. The thread is terminated when the cef_thread_t object is destroyed or stop() is called. All pending tasks queued on the thread's message loop will run to completion before the thread is terminated. cef_thread_create() can be called on any valid CEF thread in either the browser or render process. This structure should only be used for tasks that require a dedicated thread. In most cases you can post tasks to an existing CEF thread instead of creating a new one; see cef_task.h for details.
type Thread = portin.Thread

// threadImpl is a reverse wrapper for a CEF-owned Thread pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type threadImpl struct {
	rawPtr      *capi.CEFThreadT
	releaseOnce sync.Once
}

func (obj *threadImpl) GetTaskRunner() TaskRunner {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetTaskRunner()
	return wrapTaskRunner(unsafe.Pointer(ret))
}

func (obj *threadImpl) GetPlatformThreadID() uintptr {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetPlatformThreadID()
	return uintptr(ret)
}

func (obj *threadImpl) Stop() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallStop()
}

func (obj *threadImpl) IsRunning() bool {
	if obj == nil || obj.rawPtr == nil {
		return false
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallIsRunning()
	return ret != 0
}

func (obj *threadImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *threadImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

func wrapThread(ptr unsafe.Pointer) Thread {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFThreadT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &threadImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*threadImpl).Release)
	return impl
}

// ThreadCreate wraps the CEF CEFThreadCreate function.
func ThreadCreate(displayName string, priority ThreadPriority, messageLoopType MessageLoopType, stoppable int32, comInitMode ComInitMode) Thread {
	displayNameStr := cefString(displayName)
	defer freeCefString(&displayNameStr)
	ret := capi.CEFThreadCreate(unsafe.Pointer(&displayNameStr), capi.CEFThreadPriorityT(priority), capi.CEFMessageLoopTypeT(messageLoopType), stoppable, capi.CEFComInitModeT(comInitMode))
	return wrapThread(ret)
}
