// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/ebitengine/purego"

	"github.com/bnema/purego-cef/internal/capi"
)

// MediaAccessCallback Callback structure used for asynchronous continuation of media access permission requests.
type MediaAccessCallback interface {
	// Cont Call to allow or deny media access. If this callback was initiated in response to a getUserMedia (indicated by CEF_MEDIA_PERMISSION_DEVICE_AUDIO_CAPTURE and/or CEF_MEDIA_PERMISSION_DEVICE_VIDEO_CAPTURE being set) then |allowed_permissions| must match |required_permissions| passed to OnRequestMediaAccessPermission.
	Cont(allowedPermissions uint32)
	// Cancel Cancel the media access request.
	Cancel()
}

type mediaAccessCallbackImpl struct {
	rawPtr *capi.CEFMediaAccessCallbackT
}

func (obj *mediaAccessCallbackImpl) Cont(allowedPermissions uint32) {
	obj.rawPtr.CallCont(uintptr(allowedPermissions))
}

func (obj *mediaAccessCallbackImpl) Cancel() {
	obj.rawPtr.CallCancel()
}

func (obj *mediaAccessCallbackImpl) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *mediaAccessCallbackImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapMediaAccessCallback(ptr unsafe.Pointer) MediaAccessCallback {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFMediaAccessCallbackT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &mediaAccessCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *mediaAccessCallbackImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// PermissionPromptCallback Callback structure used for asynchronous continuation of permission prompts.
type PermissionPromptCallback interface {
	// Cont Complete the permissions request with the specified |result|.
	Cont(result PermissionRequestResult)
}

type permissionPromptCallbackImpl struct {
	rawPtr *capi.CEFPermissionPromptCallbackT
}

func (obj *permissionPromptCallbackImpl) Cont(result PermissionRequestResult) {
	obj.rawPtr.CallCont(uintptr(result))
}

func (obj *permissionPromptCallbackImpl) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *permissionPromptCallbackImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapPermissionPromptCallback(ptr unsafe.Pointer) PermissionPromptCallback {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFPermissionPromptCallbackT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &permissionPromptCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *permissionPromptCallbackImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// PermissionHandler Implement this structure to handle events related to permission requests. The functions of this structure will be called on the browser process UI thread.
type PermissionHandler interface {
	// OnRequestMediaAccessPermission Called when a page requests permission to access media. |requesting_origin| is the URL origin requesting permission. |requested_permissions| is a combination of values from cef_media_access_permission_types_t that represent the requested permissions. Return true (1) and call cef_media_access_callback_t functions either in this function or at a later time to continue or cancel the request. Return false (0) to proceed with default handling. With Chrome style, default handling will display the permission request UI. With Alloy style, default handling will deny the request. This function will not be called if the "--enable-media-stream" command-line switch is used to grant all permissions.
	OnRequestMediaAccessPermission(browser Browser, frame Frame, requestingOrigin string, requestedPermissions uint32, callback MediaAccessCallback) int32
	// OnShowPermissionPrompt Called when a page should show a permission prompt. |prompt_id| uniquely identifies the prompt. |requesting_origin| is the URL origin requesting permission. |requested_permissions| is a combination of values from cef_permission_request_types_t that represent the requested permissions. Return true (1) and call cef_permission_prompt_callback_t::Continue either in this function or at a later time to continue or cancel the request. Return false (0) to proceed with default handling. With Chrome style, default handling will display the permission prompt UI. With Alloy style, default handling is CEF_PERMISSION_RESULT_IGNORE.
	OnShowPermissionPrompt(browser Browser, promptID uint64, requestingOrigin string, requestedPermissions uint32, callback PermissionPromptCallback) int32
	// OnDismissPermissionPrompt Called when a permission prompt handled via OnShowPermissionPrompt is dismissed. |prompt_id| will match the value that was passed to OnShowPermissionPrompt. |result| will be the value passed to cef_permission_prompt_callback_t::Continue or CEF_PERMISSION_RESULT_IGNORE if the dialog was dismissed for other reasons such as navigation, browser closure, etc. This function will not be called if OnShowPermissionPrompt returned false (0) for |prompt_id|.
	OnDismissPermissionPrompt(browser Browser, promptID uint64, result PermissionRequestResult)
}

// permissionHandlerWrapper wraps a user-provided PermissionHandler implementation together
// with the raw CEF struct pointer allocated by NewPermissionHandler.  It satisfies the
// PermissionHandler interface (by embedding the user impl) and rawPointerHolder (so
// extractRawPointer can recover the raw pointer).
type permissionHandlerWrapper struct {
	PermissionHandler // embed user impl for interface delegation
	rawPtr            *capi.CEFPermissionHandlerT
}

func (w *permissionHandlerWrapper) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewPermissionHandler creates a CEF handler backed by the given implementation.
// The returned value can be passed directly to CEF functions that expect
// this handler type (e.g. BrowserHostCreateBrowser for Client).
func NewPermissionHandler(impl PermissionHandler) PermissionHandler {
	r := new(capi.CEFPermissionHandlerT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnRequestMediaAccessPermission(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr, arg4 uintptr) uintptr {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		requestingOrigin := goString(unsafe.Pointer(arg2))
		requestedPermissions := uint32(arg3)
		callback := wrapMediaAccessCallback(unsafe.Pointer(arg4))
		return uintptr(impl.OnRequestMediaAccessPermission(browser, frame, requestingOrigin, requestedPermissions, callback))
	}))

	r.OverrideOnShowPermissionPrompt(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr, arg4 uintptr) uintptr {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		promptID := uint64(arg1)
		requestingOrigin := goString(unsafe.Pointer(arg2))
		requestedPermissions := uint32(arg3)
		callback := wrapPermissionPromptCallback(unsafe.Pointer(arg4))
		return uintptr(impl.OnShowPermissionPrompt(browser, promptID, requestingOrigin, requestedPermissions, callback))
	}))

	r.OverrideOnDismissPermissionPrompt(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr) {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		promptID := uint64(arg1)
		result := PermissionRequestResult(arg2)
		impl.OnDismissPermissionPrompt(browser, promptID, result)
	}))

	w := &permissionHandlerWrapper{rawPtr: r}
	w.PermissionHandler = impl
	return w
}

// wrapPermissionHandler wraps a CEF handler pointer received from CEF into a Go interface.
// This is a no-op wrapper since handler pointers from CEF are opaque; the returned
// interface is a thin facade that cannot call back into the original implementation.
func wrapPermissionHandler(ptr unsafe.Pointer) PermissionHandler {
	// Handler pointers returned by CEF cannot be meaningfully wrapped because
	// the underlying function pointers may be Go callbacks that we cannot call
	// back through purego.  Return nil for now; callers that need the handler
	// should keep their own reference.
	return nil
}
