// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// Frame Structure used to represent a frame in the browser window. When used in the browser process the functions of this structure may be called on any thread unless otherwise indicated in the comments. When used in the render process the functions of this structure may only be called on the main thread.
type Frame = portin.Frame

// frameImpl is a reverse wrapper for a CEF-owned Frame pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type frameImpl struct {
	rawPtr      *capi.CEFFrameT
	releaseOnce sync.Once
}

func (obj *frameImpl) IsValid() bool {
	if obj == nil || obj.rawPtr == nil {
		return false
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallIsValid()
	return ret != 0
}

func (obj *frameImpl) Undo() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallUndo()
}

func (obj *frameImpl) Redo() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallRedo()
}

func (obj *frameImpl) Cut() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallCut()
}

func (obj *frameImpl) Copy() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallCopy()
}

func (obj *frameImpl) Paste() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallPaste()
}

func (obj *frameImpl) PasteAndMatchStyle() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallPasteAndMatchStyle()
}

func (obj *frameImpl) Del() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallDel()
}

func (obj *frameImpl) SelectAll() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallSelectAll()
}

func (obj *frameImpl) ViewSource() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallViewSource()
}

func (obj *frameImpl) GetSource(visitor StringVisitor) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	if rawPtr.GetSource == 0 {
		return
	}
	visitorPtr := extractOrWrapRawPointer(visitor, func() any { return NewStringVisitor(visitor) })
	transferRef(visitorPtr)
	rawPtr.CallGetSource(visitorPtr)
	runtime.KeepAlive(visitor)
}

func (obj *frameImpl) GetText(visitor StringVisitor) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	if rawPtr.GetText == 0 {
		return
	}
	visitorPtr := extractOrWrapRawPointer(visitor, func() any { return NewStringVisitor(visitor) })
	transferRef(visitorPtr)
	rawPtr.CallGetText(visitorPtr)
	runtime.KeepAlive(visitor)
}

func (obj *frameImpl) LoadRequest(request Request) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	if rawPtr.LoadRequest == 0 {
		return
	}
	requestPtr := extractRawPointer(request)
	transferRef(requestPtr)
	rawPtr.CallLoadRequest(requestPtr)
	runtime.KeepAlive(request)
}

func (obj *frameImpl) LoadURL(uRL string) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	uRLStr := cefString(uRL)
	defer freeCefString(&uRLStr)
	rawPtr.CallLoadURL(unsafe.Pointer(&uRLStr))
}

func (obj *frameImpl) ExecuteJavaScript(code string, scriptURL string, startLine int32) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	codeStr := cefString(code)
	defer freeCefString(&codeStr)
	scriptURLStr := cefString(scriptURL)
	defer freeCefString(&scriptURLStr)
	rawPtr.CallExecuteJavaScript(unsafe.Pointer(&codeStr), unsafe.Pointer(&scriptURLStr), uintptr(startLine))
}

func (obj *frameImpl) IsMain() bool {
	if obj == nil || obj.rawPtr == nil {
		return false
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallIsMain()
	return ret != 0
}

func (obj *frameImpl) IsFocused() bool {
	if obj == nil || obj.rawPtr == nil {
		return false
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallIsFocused()
	return ret != 0
}

func (obj *frameImpl) GetName() string {
	if obj == nil || obj.rawPtr == nil {
		return ""
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetName()
	return goStringUserfree(unsafe.Pointer(ret))
}

func (obj *frameImpl) GetIdentifier() string {
	if obj == nil || obj.rawPtr == nil {
		return ""
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetIdentifier()
	return goStringUserfree(unsafe.Pointer(ret))
}

func (obj *frameImpl) GetParent() Frame {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetParent()
	return wrapFrame(unsafe.Pointer(ret))
}

func (obj *frameImpl) GetURL() string {
	if obj == nil || obj.rawPtr == nil {
		return ""
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetURL()
	return goStringUserfree(unsafe.Pointer(ret))
}

func (obj *frameImpl) GetBrowser() Browser {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetBrowser()
	return wrapBrowser(unsafe.Pointer(ret))
}

func (obj *frameImpl) GetV8Context() V8Context {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallGetV8Context()
	return wrapV8Context(unsafe.Pointer(ret))
}

func (obj *frameImpl) VisitDom(visitor Domvisitor) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	if rawPtr.VisitDom == 0 {
		return
	}
	visitorPtr := extractOrWrapRawPointer(visitor, func() any { return NewDomvisitor(visitor) })
	transferRef(visitorPtr)
	rawPtr.CallVisitDom(visitorPtr)
	runtime.KeepAlive(visitor)
}

func (obj *frameImpl) CreateUrlrequest(request Request, client UrlrequestClient) Urlrequest {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	rawPtr := obj.rawPtr
	if rawPtr.CreateUrlrequest == 0 {
		return nil
	}
	requestPtr := extractRawPointer(request)
	transferRef(requestPtr)
	clientPtr := extractOrWrapRawPointer(client, func() any { return NewUrlrequestClient(client) })
	transferRef(clientPtr)
	ret := rawPtr.CallCreateUrlrequest(requestPtr, clientPtr)
	runtime.KeepAlive(request)
	runtime.KeepAlive(client)
	return wrapUrlrequest(unsafe.Pointer(ret))
}

func (obj *frameImpl) SendProcessMessage(targetProcess ProcessID, message ProcessMessage) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	if rawPtr.SendProcessMessage == 0 {
		return
	}
	messagePtr := extractRawPointer(message)
	transferRef(messagePtr)
	rawPtr.CallSendProcessMessage(uintptr(targetProcess), messagePtr)
	runtime.KeepAlive(message)
}

func (obj *frameImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *frameImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

func wrapFrame(ptr unsafe.Pointer) Frame {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFFrameT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &frameImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*frameImpl).Release)
	return impl
}
