// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// SchemeRegistrar Structure that manages custom scheme registrations.
type SchemeRegistrar = portin.SchemeRegistrar

// schemeRegistrarImpl is a reverse wrapper for a CEF-owned SchemeRegistrar pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type schemeRegistrarImpl struct {
	rawPtr *capi.CEFSchemeRegistrarT
}

func (obj *schemeRegistrarImpl) AddCustomScheme(schemeName string, options int32) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	schemeNameStr := cefString(schemeName)
	defer freeCefString(&schemeNameStr)
	ret := rawPtr.CallAddCustomScheme(uintptr(unsafe.Pointer(&schemeNameStr)), uintptr(options))
	return int32(ret)
}

func (obj *schemeRegistrarImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

func wrapSchemeRegistrar(ptr unsafe.Pointer) SchemeRegistrar {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFSchemeRegistrarT)(ptr)
	return &schemeRegistrarImpl{rawPtr: r}
}

// SchemeHandlerFactory Structure that creates cef_resource_handler_t instances for handling scheme requests. The functions of this structure will always be called on the IO thread.
type SchemeHandlerFactory = portin.SchemeHandlerFactory

// schemeHandlerFactoryWrapper wraps a user-provided SchemeHandlerFactory implementation together
// with the raw CEF struct pointer allocated by NewSchemeHandlerFactory.  It satisfies the
// SchemeHandlerFactory interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type schemeHandlerFactoryWrapper struct {
	SchemeHandlerFactory // embed user impl for interface delegation
	rawPtr               *capi.CEFSchemeHandlerFactoryT
}

func (w *schemeHandlerFactoryWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

var schemeHandlerFactoryCreateSharedOnce sync.Once
var schemeHandlerFactoryCreateSharedCallback uintptr

func schemeHandlerFactoryCreateCEFCallback() uintptr {
	return sharedCEFCallback(&schemeHandlerFactoryCreateSharedOnce, &schemeHandlerFactoryCreateSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
		impl, ownerOK := cefCallbackOwnerAs[SchemeHandlerFactory](self)
		if !ownerOK {
			return 0
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		schemeName := goString(unsafe.Pointer(arg2))
		request := wrapRequest(unsafe.Pointer(arg3))
		result := impl.Create(browser, frame, schemeName, request)
		if result == nil {
			return 0
		}
		return uintptr(extractOrWrapRawPointer(result, func() any {
			return NewResourceHandler(result)
		}))
	})
}

// NewSchemeHandlerFactory creates a CEF handler backed by the given implementation.
func NewSchemeHandlerFactory(impl SchemeHandlerFactory) SchemeHandlerFactory {
	if isNilImpl(impl) {
		return nil
	}
	r := new(capi.CEFSchemeHandlerFactoryT)
	w := &schemeHandlerFactoryWrapper{rawPtr: r}
	w.SchemeHandlerFactory = impl
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), w)

	r.OverrideCreate(schemeHandlerFactoryCreateCEFCallback())

	return w
}

// schemeHandlerFactoryImpl is a reverse wrapper for a CEF-owned SchemeHandlerFactory pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type schemeHandlerFactoryImpl struct {
	rawPtr      *capi.CEFSchemeHandlerFactoryT
	releaseOnce sync.Once
}

func (obj *schemeHandlerFactoryImpl) Create(browser Browser, frame Frame, schemeName string, request Request) ResourceHandler {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	rawPtr := obj.rawPtr
	schemeNameStr := cefString(schemeName)
	defer freeCefString(&schemeNameStr)
	ret := rawPtr.CallCreate(uintptr(extractRawPointer(browser)), uintptr(extractRawPointer(frame)), uintptr(unsafe.Pointer(&schemeNameStr)), uintptr(extractRawPointer(request)))
	return wrapResourceHandler(unsafe.Pointer(ret))
}

func (obj *schemeHandlerFactoryImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *schemeHandlerFactoryImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

// wrapSchemeHandlerFactory wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapSchemeHandlerFactory(ptr unsafe.Pointer) SchemeHandlerFactory {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFSchemeHandlerFactoryT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &schemeHandlerFactoryImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*schemeHandlerFactoryImpl).Release)
	return impl
}

// RegisterSchemeHandlerFactory Register a scheme handler factory with the global request context. An NULL |domain_name| value for a standard scheme will cause the factory to match all domain names. The |domain_name| value will be ignored for non-standard schemes. If |scheme_name| is a built-in scheme and no handler is returned by |factory| then the built-in scheme handler factory will be called. If |scheme_name| is a custom scheme then you must also implement the cef_app_t::on_register_custom_schemes() function in all processes. This function may be called multiple times to change or remove the factory that matches the specified |scheme_name| and optional |domain_name|. Returns false (0) if an error occurs. This function may be called on any thread in the browser process. Using this function is equivalent to calling cef_reques t_context_t::cef_request_context_get_global_context()- >register_scheme_handler_factory().
func RegisterSchemeHandlerFactory(schemeName string, domainName string, factory SchemeHandlerFactory) int32 {
	schemeNameStr := cefString(schemeName)
	defer freeCefString(&schemeNameStr)
	domainNameStr := cefString(domainName)
	defer freeCefString(&domainNameStr)
	ret := capi.CEFRegisterSchemeHandlerFactory(unsafe.Pointer(&schemeNameStr), unsafe.Pointer(&domainNameStr), extractOrWrapRawPointer(factory, func() any { return NewSchemeHandlerFactory(factory) }))
	return int32(ret)
}

// ClearSchemeHandlerFactories Clear all scheme handler factories registered with the global request context. Returns false (0) on error. This function may be called on any thread in the browser process. Using this function is equivalent to calling cef_request_context_t::cef_request_context_get_global_context()- >clear_scheme_handler_factories().
func ClearSchemeHandlerFactories() int32 {
	ret := capi.CEFClearSchemeHandlerFactories()
	return int32(ret)
}
