// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// DownloadItem Structure used to represent a download item.
type DownloadItem interface {
	// IsValid Returns true (1) if this object is valid. Do not call any other functions if this function returns false (0).
	IsValid() bool
	// IsInProgress Returns true (1) if the download is in progress.
	IsInProgress() bool
	// IsComplete Returns true (1) if the download is complete.
	IsComplete() bool
	// IsCanceled Returns true (1) if the download has been canceled.
	IsCanceled() bool
	// IsInterrupted Returns true (1) if the download has been interrupted.
	IsInterrupted() bool
	// GetInterruptReason Returns the most recent interrupt reason.
	GetInterruptReason() DownloadInterruptReason
	// GetCurrentSpeed Returns a simple speed estimate in bytes/s.
	GetCurrentSpeed() int64
	// GetPercentComplete Returns the rough percent complete or -1 if the receive total size is unknown.
	GetPercentComplete() int32
	// GetTotalBytes Returns the total number of bytes.
	GetTotalBytes() int64
	// GetReceivedBytes Returns the number of received bytes.
	GetReceivedBytes() int64
	// GetStartTime Returns the time that the download started.
	GetStartTime() uintptr
	// GetEndTime Returns the time that the download ended.
	GetEndTime() uintptr
	// GetFullPath Returns the full path to the downloaded or downloading file.
	GetFullPath() string
	// GetID Returns the unique identifier for this download.
	GetID() uint32
	// GetURL Returns the URL.
	GetURL() string
	// GetOriginalURL Returns the original URL before any redirections.
	GetOriginalURL() string
	// GetSuggestedFileName Returns the suggested file name.
	GetSuggestedFileName() string
	// GetContentDisposition Returns the content disposition.
	GetContentDisposition() string
	// GetMimeType Returns the mime type.
	GetMimeType() string
	// IsPaused Returns true (1) if the download has been paused.
	IsPaused() bool
}

type downloadItemImpl struct {
	rawPtr *raw.CEFDownloadItemT
}

func (obj *downloadItemImpl) IsValid() bool {
	return obj.rawPtr.CallIsValid() != 0
}

func (obj *downloadItemImpl) IsInProgress() bool {
	return obj.rawPtr.CallIsInProgress() != 0
}

func (obj *downloadItemImpl) IsComplete() bool {
	return obj.rawPtr.CallIsComplete() != 0
}

func (obj *downloadItemImpl) IsCanceled() bool {
	return obj.rawPtr.CallIsCanceled() != 0
}

func (obj *downloadItemImpl) IsInterrupted() bool {
	return obj.rawPtr.CallIsInterrupted() != 0
}

func (obj *downloadItemImpl) GetInterruptReason() DownloadInterruptReason {
	return DownloadInterruptReason(obj.rawPtr.CallGetInterruptReason())
}

func (obj *downloadItemImpl) GetCurrentSpeed() int64 {
	ret := obj.rawPtr.CallGetCurrentSpeed()
	_ = ret
	return 0
}

func (obj *downloadItemImpl) GetPercentComplete() int32 {
	ret := obj.rawPtr.CallGetPercentComplete()
	_ = ret
	return 0
}

func (obj *downloadItemImpl) GetTotalBytes() int64 {
	ret := obj.rawPtr.CallGetTotalBytes()
	_ = ret
	return 0
}

func (obj *downloadItemImpl) GetReceivedBytes() int64 {
	ret := obj.rawPtr.CallGetReceivedBytes()
	_ = ret
	return 0
}

func (obj *downloadItemImpl) GetStartTime() uintptr {
	ret := obj.rawPtr.CallGetStartTime()
	_ = ret
	return 0
}

func (obj *downloadItemImpl) GetEndTime() uintptr {
	ret := obj.rawPtr.CallGetEndTime()
	_ = ret
	return 0
}

func (obj *downloadItemImpl) GetFullPath() string {
	ret := obj.rawPtr.CallGetFullPath()
	_ = ret
	return ""
}

func (obj *downloadItemImpl) GetID() uint32 {
	ret := obj.rawPtr.CallGetID()
	_ = ret
	return 0
}

func (obj *downloadItemImpl) GetURL() string {
	ret := obj.rawPtr.CallGetURL()
	_ = ret
	return ""
}

func (obj *downloadItemImpl) GetOriginalURL() string {
	ret := obj.rawPtr.CallGetOriginalURL()
	_ = ret
	return ""
}

func (obj *downloadItemImpl) GetSuggestedFileName() string {
	ret := obj.rawPtr.CallGetSuggestedFileName()
	_ = ret
	return ""
}

func (obj *downloadItemImpl) GetContentDisposition() string {
	ret := obj.rawPtr.CallGetContentDisposition()
	_ = ret
	return ""
}

func (obj *downloadItemImpl) GetMimeType() string {
	ret := obj.rawPtr.CallGetMimeType()
	_ = ret
	return ""
}

func (obj *downloadItemImpl) IsPaused() bool {
	return obj.rawPtr.CallIsPaused() != 0
}

// Release releases the underlying CEF object.
func (obj *downloadItemImpl) Release() {
	base := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapDownloadItem(ptr unsafe.Pointer) DownloadItem {
	if ptr == nil {
		return nil
	}
	r := (*raw.CEFDownloadItemT)(ptr)
	base := (*raw.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &downloadItemImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *downloadItemImpl) {
		b := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}
