// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"unsafe"

	"github.com/ebitengine/purego"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// DevToolsMessageObserver Callback structure for cef_browser_host_t::AddDevToolsMessageObserver. The functions of this structure will be called on the browser process UI thread.
type DevToolsMessageObserver interface {
	// OnDevToolsMessage Method that will be called on receipt of a DevTools protocol message. |browser| is the originating browser instance. |message| is a UTF8-encoded JSON dictionary representing either a function result or an event. |message| is only valid for the scope of this callback and should be copied if necessary. Return true (1) if the message was handled or false (0) if the message should be further processed and passed to the OnDevToolsMethodResult or OnDevToolsEvent functions as appropriate. Method result dictionaries include an "id" (int) value that identifies the orginating function call sent from cef_browser_host_t::SendDevToolsMessage, and optionally either a "result" (dictionary) or "error" (dictionary) value. The "error" dictionary will contain "code" (int) and "message" (string) values. Event dictionaries include a "function" (string) value and optionally a "params" (dictionary) value. See the DevTools protocol documentation at https://chromedevtools.github.io/devtools-protocol/ for details of supported function calls and the expected "result" or "params" dictionary contents. JSON dictionaries can be parsed using the CefParseJSON function if desired, however be aware of performance considerations when parsing large messages (some of which may exceed 1MB in size).
	OnDevToolsMessage(browser Browser, message unsafe.Pointer, messageSize int) int32
	// OnDevToolsMethodResult Method that will be called after attempted execution of a DevTools protocol function. |browser| is the originating browser instance. |message_id| is the "id" value that identifies the originating function call message. If the function succeeded |success| will be true (1) and |result| will be the UTF8-encoded JSON "result" dictionary value (which may be NULL). If the function failed |success| will be false (0) and |result| will be the UTF8-encoded JSON "error" dictionary value. |result| is only valid for the scope of this callback and should be copied if necessary. See the OnDevToolsMessage documentation for additional details on |result| contents.
	OnDevToolsMethodResult(browser Browser, messageID int32, success int32, result unsafe.Pointer, resultSize int)
	// OnDevToolsEvent Method that will be called on receipt of a DevTools protocol event. |browser| is the originating browser instance. |function| is the "function" value. |params| is the UTF8-encoded JSON "params" dictionary value (which may be NULL). |params| is only valid for the scope of this callback and should be copied if necessary. See the OnDevToolsMessage documentation for additional details on |params| contents.
	OnDevToolsEvent(browser Browser, method string, params unsafe.Pointer, paramsSize int)
	// OnDevToolsAgentAttached Method that will be called when the DevTools agent has attached. |browser| is the originating browser instance. This will generally occur in response to the first message sent while the agent is detached.
	OnDevToolsAgentAttached(browser Browser)
	// OnDevToolsAgentDetached Method that will be called when the DevTools agent has detached. |browser| is the originating browser instance. Any function results that were pending before the agent became detached will not be delivered, and any active event subscriptions will be canceled.
	OnDevToolsAgentDetached(browser Browser)
}

// NewDevToolsMessageObserver creates a CEF handler backed by the given implementation.
// The returned pointer can be passed to CEF functions that expect this handler type.
func NewDevToolsMessageObserver(impl DevToolsMessageObserver) unsafe.Pointer {
	r := new(raw.CEFDevToolsMessageObserverT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnDevToolsMessage(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		message := unsafe.Pointer(arg1)
		messageSize := int(arg2)
		return uintptr(impl.OnDevToolsMessage(browser, message, messageSize))
	}))

	r.OverrideOnDevToolsMethodResult(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr, arg4 uintptr) {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		messageID := int32(arg1)
		success := int32(arg2)
		result := unsafe.Pointer(arg3)
		resultSize := int(arg4)
		impl.OnDevToolsMethodResult(browser, messageID, success, result, resultSize)
	}))

	r.OverrideOnDevToolsEvent(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		method := goString(unsafe.Pointer(arg1))
		params := unsafe.Pointer(arg2)
		paramsSize := int(arg3)
		impl.OnDevToolsEvent(browser, method, params, paramsSize)
	}))

	r.OverrideOnDevToolsAgentAttached(purego.NewCallback(func(self uintptr, arg0 uintptr) {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		impl.OnDevToolsAgentAttached(browser)
	}))

	r.OverrideOnDevToolsAgentDetached(purego.NewCallback(func(self uintptr, arg0 uintptr) {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		impl.OnDevToolsAgentDetached(browser)
	}))

	return unsafe.Pointer(r)
}

// wrapDevToolsMessageObserver wraps a CEF handler pointer received from CEF into a Go interface.
// This is a no-op wrapper since handler pointers from CEF are opaque; the returned
// interface is a thin facade that cannot call back into the original implementation.
func wrapDevToolsMessageObserver(ptr unsafe.Pointer) DevToolsMessageObserver {
	// Handler pointers returned by CEF cannot be meaningfully wrapped because
	// the underlying function pointers may be Go callbacks that we cannot call
	// back through purego.  Return nil for now; callers that need the handler
	// should keep their own reference.
	return nil
}
