// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"github.com/bnema/purego-cef/internal/capi"
)

// BaseRefCounted All ref-counted framework structures must include this structure first.
type BaseRefCounted = capi.CEFBaseRefCountedT

// BaseScoped All scoped framework structures must include this structure first.
type BaseScoped = capi.CEFBaseScopedT
