// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/ebitengine/purego"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// ResourceSkipCallback Callback for asynchronous continuation of cef_resource_handler_t::skip().
type ResourceSkipCallback interface {
	Cont(bytesSkipped int64)
}

type resourceSkipCallbackImpl struct {
	rawPtr *raw.CEFResourceSkipCallbackT
}

func (obj *resourceSkipCallbackImpl) Cont(bytesSkipped int64) {
	obj.rawPtr.CallCont(uintptr(0) /* bytesSkipped */)
}

// Release releases the underlying CEF object.
func (obj *resourceSkipCallbackImpl) Release() {
	base := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapResourceSkipCallback(ptr unsafe.Pointer) ResourceSkipCallback {
	if ptr == nil {
		return nil
	}
	r := (*raw.CEFResourceSkipCallbackT)(ptr)
	base := (*raw.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &resourceSkipCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *resourceSkipCallbackImpl) {
		b := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// ResourceReadCallback Callback for asynchronous continuation of cef_resource_handler_t::read().
type ResourceReadCallback interface {
	Cont(bytesRead int32)
}

type resourceReadCallbackImpl struct {
	rawPtr *raw.CEFResourceReadCallbackT
}

func (obj *resourceReadCallbackImpl) Cont(bytesRead int32) {
	obj.rawPtr.CallCont(uintptr(0) /* bytesRead */)
}

// Release releases the underlying CEF object.
func (obj *resourceReadCallbackImpl) Release() {
	base := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapResourceReadCallback(ptr unsafe.Pointer) ResourceReadCallback {
	if ptr == nil {
		return nil
	}
	r := (*raw.CEFResourceReadCallbackT)(ptr)
	base := (*raw.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &resourceReadCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *resourceReadCallbackImpl) {
		b := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// ResourceHandler Structure used to implement a custom request handler structure. The functions of this structure will be called on the IO thread unless otherwise indicated.
type ResourceHandler interface {
	// Open Open the response stream. To handle the request immediately set |handle_request| to true (1) and return true (1). To decide at a later time set |handle_request| to false (0), return true (1), and execute |callback| to continue or cancel the request. To cancel the request immediately set |handle_request| to true (1) and return false (0). This function will be called in sequence but not from a dedicated thread. For backwards compatibility set |handle_request| to false (0) and return false (0) and the ProcessRequest function will be called.
	Open(request Request, handleRequest unsafe.Pointer, callback Callback) int32
	// ProcessRequest Begin processing the request. To handle the request return true (1) and call cef_callback_t::cont() once the response header information is available (cef_callback_t::cont() can also be called from inside this function if header information is available immediately). To cancel the request return false (0). WARNING: This function is deprecated. Use Open instead.
	ProcessRequest(request Request, callback Callback) int32
	// GetResponseHeaders Retrieve response header information. If the response length is not known set |response_length| to -1 and read_response() will be called until it returns false (0). If the response length is known set |response_length| to a positive value and read_response() will be called until it returns false (0) or the specified number of bytes have been read. Use the |response| object to set the mime type, http status code and other optional header values. To redirect the request to a new URL set |redirectUrl| to the new URL. |redirectUrl| can be either a relative or fully qualified URL. It is also possible to set |response| to a redirect http status code and pass the new URL via a Location header. Likewise with |redirectUrl| it is valid to set a relative or fully qualified URL as the Location header value. If an error occured while setting up the request you can call set_error() on |response| to indicate the error condition.
	GetResponseHeaders(response Response, responseLength unsafe.Pointer, redirecturl *string)
	Skip(bytesToSkip int64, bytesSkipped unsafe.Pointer, callback ResourceSkipCallback) int32
	Read(dataOut unsafe.Pointer, bytesToRead int32, bytesRead unsafe.Pointer, callback ResourceReadCallback) int32
	ReadResponse(dataOut unsafe.Pointer, bytesToRead int32, bytesRead unsafe.Pointer, callback Callback) int32
	Cancel()
}

// NewResourceHandler creates a CEF handler backed by the given implementation.
// The returned pointer can be passed to CEF functions that expect this handler type.
func NewResourceHandler(impl ResourceHandler) unsafe.Pointer {
	r := new(raw.CEFResourceHandlerT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOpen(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.Open(...), marshal return
		return 0
	}))

	r.OverrideProcessRequest(purego.NewCallback(func(_ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.ProcessRequest(...), marshal return
		return 0
	}))

	r.OverrideGetResponseHeaders(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr) {
		// TODO: unmarshal args, call impl.GetResponseHeaders(...)
	}))

	r.OverrideSkip(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.Skip(...), marshal return
		return 0
	}))

	r.OverrideRead(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.Read(...), marshal return
		return 0
	}))

	r.OverrideReadResponse(purego.NewCallback(func(_ uintptr, _ uintptr, _ uintptr, _ uintptr) uintptr {
		// TODO: unmarshal args, call impl.ReadResponse(...), marshal return
		return 0
	}))

	r.OverrideCancel(purego.NewCallback(func() {
		// TODO: unmarshal args, call impl.Cancel(...)
	}))

	return unsafe.Pointer(r)
}
