// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// DragData Structure used to represent drag data. The functions of this structure may be called on any thread.
type DragData interface {
	// Clone Returns a copy of the current object.
	Clone() DragData
	// IsReadOnly Returns true (1) if this object is read-only.
	IsReadOnly() bool
	// IsLink Returns true (1) if the drag data is a link.
	IsLink() bool
	// IsFragment Returns true (1) if the drag data is a text or html fragment.
	IsFragment() bool
	// IsFile Returns true (1) if the drag data is a file.
	IsFile() bool
	// GetLinkURL Return the link URL that is being dragged.
	GetLinkURL() string
	// GetLinkTitle Return the title associated with the link being dragged.
	GetLinkTitle() string
	// GetLinkMetadata Return the metadata, if any, associated with the link being dragged.
	GetLinkMetadata() string
	// GetFragmentText Return the plain text fragment that is being dragged.
	GetFragmentText() string
	// GetFragmentHtml Return the text/html fragment that is being dragged.
	GetFragmentHtml() string
	// GetFragmentBaseURL Return the base URL that the fragment came from. This value is used for resolving relative URLs and may be NULL.
	GetFragmentBaseURL() string
	// GetFileName Return the name of the file being dragged out of the browser window.
	GetFileName() string
	// GetFileContents Write the contents of the file being dragged out of the web view into |writer|. Returns the number of bytes sent to |writer|. If |writer| is NULL this function will return the size of the file contents in bytes. Call get_file_name() to get a suggested name for the file.
	GetFileContents(writer StreamWriter) int
	// GetFileNames Retrieve the list of file names that are being dragged into the browser window.
	GetFileNames(names []string) int32
	// GetFilePaths Retrieve the list of file paths that are being dragged into the browser window.
	GetFilePaths(paths []string) int32
	// SetLinkURL Set the link URL that is being dragged.
	SetLinkURL(uRL string)
	// SetLinkTitle Set the title associated with the link being dragged.
	SetLinkTitle(title string)
	// SetLinkMetadata Set the metadata associated with the link being dragged.
	SetLinkMetadata(data string)
	// SetFragmentText Set the plain text fragment that is being dragged.
	SetFragmentText(text string)
	// SetFragmentHtml Set the text/html fragment that is being dragged.
	SetFragmentHtml(html string)
	// SetFragmentBaseURL Set the base URL that the fragment came from.
	SetFragmentBaseURL(baseURL string)
	// ResetFileContents Reset the file contents. You should do this before calling cef_browser_host_t::DragTargetDragEnter as the web view does not allow us to drag in this kind of data.
	ResetFileContents()
	// AddFile Add a file that is being dragged into the webview.
	AddFile(path string, displayName string)
	// ClearFilenames Clear list of filenames.
	ClearFilenames()
	// GetImage Get the image representation of drag data. May return NULL if no image representation is available.
	GetImage() Image
	// GetImageHotspot Get the image hotspot (drag start location relative to image dimensions).
	GetImageHotspot() uintptr
	// HasImage Returns true (1) if an image representation of drag data is available.
	HasImage() bool
}

type dragDataImpl struct {
	rawPtr *raw.CEFDragDataT
}

func (obj *dragDataImpl) Clone() DragData {
	ret := obj.rawPtr.CallClone()
	_ = ret
	return nil
}

func (obj *dragDataImpl) IsReadOnly() bool {
	return obj.rawPtr.CallIsReadOnly() != 0
}

func (obj *dragDataImpl) IsLink() bool {
	return obj.rawPtr.CallIsLink() != 0
}

func (obj *dragDataImpl) IsFragment() bool {
	return obj.rawPtr.CallIsFragment() != 0
}

func (obj *dragDataImpl) IsFile() bool {
	return obj.rawPtr.CallIsFile() != 0
}

func (obj *dragDataImpl) GetLinkURL() string {
	ret := obj.rawPtr.CallGetLinkURL()
	_ = ret
	return ""
}

func (obj *dragDataImpl) GetLinkTitle() string {
	ret := obj.rawPtr.CallGetLinkTitle()
	_ = ret
	return ""
}

func (obj *dragDataImpl) GetLinkMetadata() string {
	ret := obj.rawPtr.CallGetLinkMetadata()
	_ = ret
	return ""
}

func (obj *dragDataImpl) GetFragmentText() string {
	ret := obj.rawPtr.CallGetFragmentText()
	_ = ret
	return ""
}

func (obj *dragDataImpl) GetFragmentHtml() string {
	ret := obj.rawPtr.CallGetFragmentHtml()
	_ = ret
	return ""
}

func (obj *dragDataImpl) GetFragmentBaseURL() string {
	ret := obj.rawPtr.CallGetFragmentBaseURL()
	_ = ret
	return ""
}

func (obj *dragDataImpl) GetFileName() string {
	ret := obj.rawPtr.CallGetFileName()
	_ = ret
	return ""
}

func (obj *dragDataImpl) GetFileContents(writer StreamWriter) int {
	ret := obj.rawPtr.CallGetFileContents(uintptr(0) /* writer */)
	_ = ret
	return 0
}

func (obj *dragDataImpl) GetFileNames(names []string) int32 {
	ret := obj.rawPtr.CallGetFileNames(uintptr(0) /* names */)
	_ = ret
	return 0
}

func (obj *dragDataImpl) GetFilePaths(paths []string) int32 {
	ret := obj.rawPtr.CallGetFilePaths(uintptr(0) /* paths */)
	_ = ret
	return 0
}

func (obj *dragDataImpl) SetLinkURL(uRL string) {
	obj.rawPtr.CallSetLinkURL(uintptr(0) /* uRL */)
}

func (obj *dragDataImpl) SetLinkTitle(title string) {
	obj.rawPtr.CallSetLinkTitle(uintptr(0) /* title */)
}

func (obj *dragDataImpl) SetLinkMetadata(data string) {
	obj.rawPtr.CallSetLinkMetadata(uintptr(0) /* data */)
}

func (obj *dragDataImpl) SetFragmentText(text string) {
	obj.rawPtr.CallSetFragmentText(uintptr(0) /* text */)
}

func (obj *dragDataImpl) SetFragmentHtml(html string) {
	obj.rawPtr.CallSetFragmentHtml(uintptr(0) /* html */)
}

func (obj *dragDataImpl) SetFragmentBaseURL(baseURL string) {
	obj.rawPtr.CallSetFragmentBaseURL(uintptr(0) /* baseURL */)
}

func (obj *dragDataImpl) ResetFileContents() {
	obj.rawPtr.CallResetFileContents()
}

func (obj *dragDataImpl) AddFile(path string, displayName string) {
	obj.rawPtr.CallAddFile(uintptr(0) /* path */, uintptr(0) /* displayName */)
}

func (obj *dragDataImpl) ClearFilenames() {
	obj.rawPtr.CallClearFilenames()
}

func (obj *dragDataImpl) GetImage() Image {
	ret := obj.rawPtr.CallGetImage()
	_ = ret
	return nil
}

func (obj *dragDataImpl) GetImageHotspot() uintptr {
	ret := obj.rawPtr.CallGetImageHotspot()
	_ = ret
	return 0
}

func (obj *dragDataImpl) HasImage() bool {
	return obj.rawPtr.CallHasImage() != 0
}

// Release releases the underlying CEF object.
func (obj *dragDataImpl) Release() {
	base := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapDragData(ptr unsafe.Pointer) DragData {
	if ptr == nil {
		return nil
	}
	r := (*raw.CEFDragDataT)(ptr)
	base := (*raw.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &dragDataImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *dragDataImpl) {
		b := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// DragDataCreate Create a new cef_drag_data_t object.
func DragDataCreate() uintptr {
	// TODO: marshal args, call raw.CEFDragDataCreate(...), marshal return
	_ = raw.CEFDragDataCreate
	return 0
}
