// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// MediaRouter Supports discovery of and communication with media devices on the local network via the Cast and DIAL protocols. The functions of this structure may be called on any browser process thread unless otherwise indicated.
type MediaRouter = portin.MediaRouter

type mediaRouterImpl struct {
	rawPtr *capi.CEFMediaRouterT
}

func (obj *mediaRouterImpl) AddObserver(observer MediaObserver) Registration {
	ret := obj.rawPtr.CallAddObserver(uintptr(extractOrWrapRawPointer(observer, func() any { return NewMediaObserver(observer) })))
	return wrapRegistration(unsafe.Pointer(ret))
}

func (obj *mediaRouterImpl) GetSource(urn string) MediaSource {
	urnStr := cefString(urn)
	defer freeCefString(&urnStr)
	ret := obj.rawPtr.CallGetSource(uintptr(unsafe.Pointer(&urnStr)))
	return wrapMediaSource(unsafe.Pointer(ret))
}

func (obj *mediaRouterImpl) NotifyCurrentSinks() {
	obj.rawPtr.CallNotifyCurrentSinks()
}

func (obj *mediaRouterImpl) CreateRoute(source MediaSource, sink MediaSink, callback MediaRouteCreateCallback) {
	obj.rawPtr.CallCreateRoute(uintptr(extractRawPointer(source)), uintptr(extractRawPointer(sink)), uintptr(extractOrWrapRawPointer(callback, func() any { return NewMediaRouteCreateCallback(callback) })))
}

func (obj *mediaRouterImpl) NotifyCurrentRoutes() {
	obj.rawPtr.CallNotifyCurrentRoutes()
}

func (obj *mediaRouterImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *mediaRouterImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapMediaRouter(ptr unsafe.Pointer) MediaRouter {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFMediaRouterT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &mediaRouterImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *mediaRouterImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// MediaObserver Implemented by the client to observe MediaRouter events and registered via cef_media_router_t::AddObserver. The functions of this structure will be called on the browser process UI thread.
type MediaObserver = portin.MediaObserver

// mediaObserverWrapper wraps a user-provided MediaObserver implementation together
// with the raw CEF struct pointer allocated by NewMediaObserver.  It satisfies the
// MediaObserver interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type mediaObserverWrapper struct {
	MediaObserver // embed user impl for interface delegation
	rawPtr        *capi.CEFMediaObserverT
}

func (w *mediaObserverWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewMediaObserver creates a CEF handler backed by the given implementation.
func NewMediaObserver(impl MediaObserver) MediaObserver {
	r := new(capi.CEFMediaObserverT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnSinks(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr) {
		var sinks []MediaSink
		if arg1 != 0 && arg0 > 0 {
			sinksPtrs := unsafe.Slice((*uintptr)(unsafe.Pointer(arg1)), int(arg0))
			sinks = make([]MediaSink, int(arg0))
			for i, ptr := range sinksPtrs {
				sinks[i] = wrapMediaSink(unsafe.Pointer(ptr))
			}
		}
		impl.OnSinks(sinks)
	}))

	r.OverrideOnRoutes(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr) {
		var routes []MediaRoute
		if arg1 != 0 && arg0 > 0 {
			routesPtrs := unsafe.Slice((*uintptr)(unsafe.Pointer(arg1)), int(arg0))
			routes = make([]MediaRoute, int(arg0))
			for i, ptr := range routesPtrs {
				routes[i] = wrapMediaRoute(unsafe.Pointer(ptr))
			}
		}
		impl.OnRoutes(routes)
	}))

	r.OverrideOnRouteStateChanged(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr) {
		route := wrapMediaRoute(unsafe.Pointer(arg0))
		state := MediaRouteConnectionState(arg1)
		impl.OnRouteStateChanged(route, state)
	}))

	r.OverrideOnRouteMessageReceived(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr) {
		route := wrapMediaRoute(unsafe.Pointer(arg0))
		message := unsafe.Pointer(arg1)
		messageSize := int(arg2)
		impl.OnRouteMessageReceived(route, message, messageSize)
	}))

	w := &mediaObserverWrapper{rawPtr: r}
	w.MediaObserver = impl
	return w
}

type mediaObserverImpl struct {
	rawPtr *capi.CEFMediaObserverT
}

func (obj *mediaObserverImpl) OnSinks(sinks []MediaSink) {
	var sinksRaw []uintptr
	var sinksPtr unsafe.Pointer
	if len(sinks) > 0 {
		sinksRaw = make([]uintptr, len(sinks))
		for i, elem := range sinks {
			sinksRaw[i] = uintptr(extractRawPointer(elem))
		}
		sinksPtr = unsafe.Pointer(&sinksRaw[0])
	}
	obj.rawPtr.CallOnSinks(uintptr(len(sinks)), uintptr(sinksPtr))
}

func (obj *mediaObserverImpl) OnRoutes(routes []MediaRoute) {
	var routesRaw []uintptr
	var routesPtr unsafe.Pointer
	if len(routes) > 0 {
		routesRaw = make([]uintptr, len(routes))
		for i, elem := range routes {
			routesRaw[i] = uintptr(extractRawPointer(elem))
		}
		routesPtr = unsafe.Pointer(&routesRaw[0])
	}
	obj.rawPtr.CallOnRoutes(uintptr(len(routes)), uintptr(routesPtr))
}

func (obj *mediaObserverImpl) OnRouteStateChanged(route MediaRoute, state MediaRouteConnectionState) {
	obj.rawPtr.CallOnRouteStateChanged(uintptr(extractRawPointer(route)), uintptr(state))
}

func (obj *mediaObserverImpl) OnRouteMessageReceived(route MediaRoute, message unsafe.Pointer, messageSize int) {
	obj.rawPtr.CallOnRouteMessageReceived(uintptr(extractRawPointer(route)), uintptr(message), uintptr(messageSize))
}

func (obj *mediaObserverImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *mediaObserverImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

// wrapMediaObserver wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapMediaObserver(ptr unsafe.Pointer) MediaObserver {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFMediaObserverT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &mediaObserverImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *mediaObserverImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// MediaRoute Represents the route between a media source and sink. Instances of this object are created via cef_media_router_t::CreateRoute and retrieved via cef_media_observer_t::OnRoutes. Contains the status and metadata of a routing operation. The functions of this structure may be called on any browser process thread unless otherwise indicated.
type MediaRoute = portin.MediaRoute

type mediaRouteImpl struct {
	rawPtr *capi.CEFMediaRouteT
}

func (obj *mediaRouteImpl) GetID() string {
	ret := obj.rawPtr.CallGetID()
	return goStringUserfree(unsafe.Pointer(ret))
}

func (obj *mediaRouteImpl) GetSource() MediaSource {
	ret := obj.rawPtr.CallGetSource()
	return wrapMediaSource(unsafe.Pointer(ret))
}

func (obj *mediaRouteImpl) GetSink() MediaSink {
	ret := obj.rawPtr.CallGetSink()
	return wrapMediaSink(unsafe.Pointer(ret))
}

func (obj *mediaRouteImpl) SendRouteMessage(message unsafe.Pointer, messageSize int) {
	obj.rawPtr.CallSendRouteMessage(uintptr(message), uintptr(messageSize))
}

func (obj *mediaRouteImpl) Terminate() {
	obj.rawPtr.CallTerminate()
}

func (obj *mediaRouteImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *mediaRouteImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapMediaRoute(ptr unsafe.Pointer) MediaRoute {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFMediaRouteT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &mediaRouteImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *mediaRouteImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// MediaRouteCreateCallback Callback structure for cef_media_router_t::CreateRoute. The functions of this structure will be called on the browser process UI thread.
type MediaRouteCreateCallback = portin.MediaRouteCreateCallback

// mediaRouteCreateCallbackWrapper wraps a user-provided MediaRouteCreateCallback implementation together
// with the raw CEF struct pointer allocated by NewMediaRouteCreateCallback.  It satisfies the
// MediaRouteCreateCallback interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type mediaRouteCreateCallbackWrapper struct {
	MediaRouteCreateCallback // embed user impl for interface delegation
	rawPtr                   *capi.CEFMediaRouteCreateCallbackT
}

func (w *mediaRouteCreateCallbackWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewMediaRouteCreateCallback creates a CEF handler backed by the given implementation.
func NewMediaRouteCreateCallback(impl MediaRouteCreateCallback) MediaRouteCreateCallback {
	r := new(capi.CEFMediaRouteCreateCallbackT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnMediaRouteCreateFinished(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr) {
		result := MediaRouteCreateResult(arg0)
		error := goString(unsafe.Pointer(arg1))
		route := wrapMediaRoute(unsafe.Pointer(arg2))
		impl.OnMediaRouteCreateFinished(result, error, route)
	}))

	w := &mediaRouteCreateCallbackWrapper{rawPtr: r}
	w.MediaRouteCreateCallback = impl
	return w
}

type mediaRouteCreateCallbackImpl struct {
	rawPtr *capi.CEFMediaRouteCreateCallbackT
}

func (obj *mediaRouteCreateCallbackImpl) OnMediaRouteCreateFinished(result MediaRouteCreateResult, error string, route MediaRoute) {
	errorStr := cefString(error)
	defer freeCefString(&errorStr)
	obj.rawPtr.CallOnMediaRouteCreateFinished(uintptr(result), uintptr(unsafe.Pointer(&errorStr)), uintptr(extractRawPointer(route)))
}

func (obj *mediaRouteCreateCallbackImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *mediaRouteCreateCallbackImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

// wrapMediaRouteCreateCallback wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapMediaRouteCreateCallback(ptr unsafe.Pointer) MediaRouteCreateCallback {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFMediaRouteCreateCallbackT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &mediaRouteCreateCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *mediaRouteCreateCallbackImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// MediaSink Represents a sink to which media can be routed. Instances of this object are retrieved via cef_media_observer_t::OnSinks. The functions of this structure may be called on any browser process thread unless otherwise indicated.
type MediaSink = portin.MediaSink

type mediaSinkImpl struct {
	rawPtr *capi.CEFMediaSinkT
}

func (obj *mediaSinkImpl) GetID() string {
	ret := obj.rawPtr.CallGetID()
	return goStringUserfree(unsafe.Pointer(ret))
}

func (obj *mediaSinkImpl) GetName() string {
	ret := obj.rawPtr.CallGetName()
	return goStringUserfree(unsafe.Pointer(ret))
}

func (obj *mediaSinkImpl) GetIconType() MediaSinkIconType {
	ret := obj.rawPtr.CallGetIconType()
	return MediaSinkIconType(ret)
}

func (obj *mediaSinkImpl) GetDeviceInfo(callback MediaSinkDeviceInfoCallback) {
	obj.rawPtr.CallGetDeviceInfo(uintptr(extractOrWrapRawPointer(callback, func() any { return NewMediaSinkDeviceInfoCallback(callback) })))
}

func (obj *mediaSinkImpl) IsCastSink() bool {
	ret := obj.rawPtr.CallIsCastSink()
	return ret != 0
}

func (obj *mediaSinkImpl) IsDialSink() bool {
	ret := obj.rawPtr.CallIsDialSink()
	return ret != 0
}

func (obj *mediaSinkImpl) IsCompatibleWith(source MediaSource) bool {
	ret := obj.rawPtr.CallIsCompatibleWith(uintptr(extractRawPointer(source)))
	return ret != 0
}

func (obj *mediaSinkImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *mediaSinkImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapMediaSink(ptr unsafe.Pointer) MediaSink {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFMediaSinkT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &mediaSinkImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *mediaSinkImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// MediaSinkDeviceInfoCallback Callback structure for cef_media_sink_t::GetDeviceInfo. The functions of this structure will be called on the browser process UI thread.
type MediaSinkDeviceInfoCallback = portin.MediaSinkDeviceInfoCallback

// mediaSinkDeviceInfoCallbackWrapper wraps a user-provided MediaSinkDeviceInfoCallback implementation together
// with the raw CEF struct pointer allocated by NewMediaSinkDeviceInfoCallback.  It satisfies the
// MediaSinkDeviceInfoCallback interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type mediaSinkDeviceInfoCallbackWrapper struct {
	MediaSinkDeviceInfoCallback // embed user impl for interface delegation
	rawPtr                      *capi.CEFMediaSinkDeviceInfoCallbackT
}

func (w *mediaSinkDeviceInfoCallbackWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewMediaSinkDeviceInfoCallback creates a CEF handler backed by the given implementation.
func NewMediaSinkDeviceInfoCallback(impl MediaSinkDeviceInfoCallback) MediaSinkDeviceInfoCallback {
	r := new(capi.CEFMediaSinkDeviceInfoCallbackT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnMediaSinkDeviceInfo(purego.NewCallback(func(self uintptr, arg0 uintptr) {
		deviceInfo := (*MediaSinkDeviceInfo)(unsafe.Pointer(arg0))
		impl.OnMediaSinkDeviceInfo(deviceInfo)
	}))

	w := &mediaSinkDeviceInfoCallbackWrapper{rawPtr: r}
	w.MediaSinkDeviceInfoCallback = impl
	return w
}

type mediaSinkDeviceInfoCallbackImpl struct {
	rawPtr *capi.CEFMediaSinkDeviceInfoCallbackT
}

func (obj *mediaSinkDeviceInfoCallbackImpl) OnMediaSinkDeviceInfo(deviceInfo *MediaSinkDeviceInfo) {
	obj.rawPtr.CallOnMediaSinkDeviceInfo(uintptr(unsafe.Pointer(deviceInfo)))
}

func (obj *mediaSinkDeviceInfoCallbackImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *mediaSinkDeviceInfoCallbackImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

// wrapMediaSinkDeviceInfoCallback wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapMediaSinkDeviceInfoCallback(ptr unsafe.Pointer) MediaSinkDeviceInfoCallback {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFMediaSinkDeviceInfoCallbackT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &mediaSinkDeviceInfoCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *mediaSinkDeviceInfoCallbackImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// MediaSource Represents a source from which media can be routed. Instances of this object are retrieved via cef_media_router_t::GetSource. The functions of this structure may be called on any browser process thread unless otherwise indicated.
type MediaSource = portin.MediaSource

type mediaSourceImpl struct {
	rawPtr *capi.CEFMediaSourceT
}

func (obj *mediaSourceImpl) GetID() string {
	ret := obj.rawPtr.CallGetID()
	return goStringUserfree(unsafe.Pointer(ret))
}

func (obj *mediaSourceImpl) IsCastSource() bool {
	ret := obj.rawPtr.CallIsCastSource()
	return ret != 0
}

func (obj *mediaSourceImpl) IsDialSource() bool {
	ret := obj.rawPtr.CallIsDialSource()
	return ret != 0
}

func (obj *mediaSourceImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *mediaSourceImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapMediaSource(ptr unsafe.Pointer) MediaSource {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFMediaSourceT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &mediaSourceImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *mediaSourceImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// MediaRouterGetGlobal Returns the MediaRouter object associated with the global request context. If |callback| is non-NULL it will be executed asnychronously on the UI thread after the manager's storage has been initialized. Equivalent to calling cef_request_context_t::cef_request_context_get_global_context()- >get_media_router().
func MediaRouterGetGlobal(callback CompletionCallback) MediaRouter {
	ret := capi.CEFMediaRouterGetGlobal(extractOrWrapRawPointer(callback, func() any { return NewCompletionCallback(callback) }))
	return wrapMediaRouter(ret)
}
