// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego-cef/internal/capi"

	in "github.com/bnema/purego-cef/internal/ports/in"
)

// Frame Structure used to represent a frame in the browser window. When used in the browser process the functions of this structure may be called on any thread unless otherwise indicated in the comments. When used in the render process the functions of this structure may only be called on the main thread.
type Frame = in.Frame

type frameImpl struct {
	rawPtr *capi.CEFFrameT
}

func (obj *frameImpl) IsValid() bool {
	return obj.rawPtr.CallIsValid() != 0
}

func (obj *frameImpl) Undo() {
	obj.rawPtr.CallUndo()
}

func (obj *frameImpl) Redo() {
	obj.rawPtr.CallRedo()
}

func (obj *frameImpl) Cut() {
	obj.rawPtr.CallCut()
}

func (obj *frameImpl) Copy() {
	obj.rawPtr.CallCopy()
}

func (obj *frameImpl) Paste() {
	obj.rawPtr.CallPaste()
}

func (obj *frameImpl) PasteAndMatchStyle() {
	obj.rawPtr.CallPasteAndMatchStyle()
}

func (obj *frameImpl) Del() {
	obj.rawPtr.CallDel()
}

func (obj *frameImpl) SelectAll() {
	obj.rawPtr.CallSelectAll()
}

func (obj *frameImpl) ViewSource() {
	obj.rawPtr.CallViewSource()
}

func (obj *frameImpl) GetSource(visitor StringVisitor) {
	obj.rawPtr.CallGetSource(uintptr(extractRawPointer(visitor)))
}

func (obj *frameImpl) GetText(visitor StringVisitor) {
	obj.rawPtr.CallGetText(uintptr(extractRawPointer(visitor)))
}

func (obj *frameImpl) LoadRequest(request Request) {
	obj.rawPtr.CallLoadRequest(uintptr(extractRawPointer(request)))
}

func (obj *frameImpl) LoadURL(uRL string) {
	uRLStr := cefString(uRL)
	defer freeCefString(&uRLStr)
	obj.rawPtr.CallLoadURL(uintptr(unsafe.Pointer(&uRLStr)))
}

func (obj *frameImpl) ExecuteJavaScript(code string, scriptURL string, startLine int32) {
	codeStr := cefString(code)
	defer freeCefString(&codeStr)
	scriptURLStr := cefString(scriptURL)
	defer freeCefString(&scriptURLStr)
	obj.rawPtr.CallExecuteJavaScript(uintptr(unsafe.Pointer(&codeStr)), uintptr(unsafe.Pointer(&scriptURLStr)), uintptr(startLine))
}

func (obj *frameImpl) IsMain() bool {
	return obj.rawPtr.CallIsMain() != 0
}

func (obj *frameImpl) IsFocused() bool {
	return obj.rawPtr.CallIsFocused() != 0
}

func (obj *frameImpl) GetName() string {
	return goStringUserfree(unsafe.Pointer(obj.rawPtr.CallGetName()))
}

func (obj *frameImpl) GetIdentifier() string {
	return goStringUserfree(unsafe.Pointer(obj.rawPtr.CallGetIdentifier()))
}

func (obj *frameImpl) GetParent() Frame {
	return wrapFrame(unsafe.Pointer(obj.rawPtr.CallGetParent()))
}

func (obj *frameImpl) GetURL() string {
	return goStringUserfree(unsafe.Pointer(obj.rawPtr.CallGetURL()))
}

func (obj *frameImpl) GetBrowser() Browser {
	return wrapBrowser(unsafe.Pointer(obj.rawPtr.CallGetBrowser()))
}

func (obj *frameImpl) GetV8Context() V8Context {
	return wrapV8Context(unsafe.Pointer(obj.rawPtr.CallGetV8Context()))
}

func (obj *frameImpl) VisitDom(visitor Domvisitor) {
	obj.rawPtr.CallVisitDom(uintptr(extractRawPointer(visitor)))
}

func (obj *frameImpl) CreateUrlrequest(request Request, client UrlrequestClient) Urlrequest {
	return wrapUrlrequest(unsafe.Pointer(obj.rawPtr.CallCreateUrlrequest(uintptr(extractRawPointer(request)), uintptr(extractRawPointer(client)))))
}

func (obj *frameImpl) SendProcessMessage(targetProcess ProcessID, message ProcessMessage) {
	obj.rawPtr.CallSendProcessMessage(uintptr(targetProcess), uintptr(extractRawPointer(message)))
}

func (obj *frameImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *frameImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapFrame(ptr unsafe.Pointer) Frame {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFFrameT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &frameImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *frameImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}
