// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// CookieManager Structure used for managing cookies. The functions of this structure may be called on any thread unless otherwise indicated.
type CookieManager = portin.CookieManager

// cookieManagerImpl is a reverse wrapper for a CEF-owned CookieManager pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type cookieManagerImpl struct {
	rawPtr      *capi.CEFCookieManagerT
	releaseOnce sync.Once
}

func (obj *cookieManagerImpl) VisitAllCookies(visitor CookieVisitor) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallVisitAllCookies(uintptr(extractOrWrapRawPointer(visitor, func() any { return NewCookieVisitor(visitor) })))
	return int32(ret)
}

func (obj *cookieManagerImpl) VisitURLCookies(uRL string, includehttponly int32, visitor CookieVisitor) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	uRLStr := cefString(uRL)
	defer freeCefString(&uRLStr)
	ret := rawPtr.CallVisitURLCookies(uintptr(unsafe.Pointer(&uRLStr)), uintptr(includehttponly), uintptr(extractOrWrapRawPointer(visitor, func() any { return NewCookieVisitor(visitor) })))
	return int32(ret)
}

func (obj *cookieManagerImpl) SetCookie(uRL string, cookie *Cookie, callback SetCookieCallback) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	uRLStr := cefString(uRL)
	defer freeCefString(&uRLStr)
	ret := rawPtr.CallSetCookie(uintptr(unsafe.Pointer(&uRLStr)), uintptr(unsafe.Pointer(cookie)), uintptr(extractOrWrapRawPointer(callback, func() any { return NewSetCookieCallback(callback) })))
	return int32(ret)
}

func (obj *cookieManagerImpl) DeleteCookies(uRL string, cookieName string, callback DeleteCookiesCallback) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	uRLStr := cefString(uRL)
	defer freeCefString(&uRLStr)
	cookieNameStr := cefString(cookieName)
	defer freeCefString(&cookieNameStr)
	ret := rawPtr.CallDeleteCookies(uintptr(unsafe.Pointer(&uRLStr)), uintptr(unsafe.Pointer(&cookieNameStr)), uintptr(extractOrWrapRawPointer(callback, func() any { return NewDeleteCookiesCallback(callback) })))
	return int32(ret)
}

func (obj *cookieManagerImpl) FlushStore(callback CompletionCallback) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallFlushStore(uintptr(extractOrWrapRawPointer(callback, func() any { return NewCompletionCallback(callback) })))
	return int32(ret)
}

func (obj *cookieManagerImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *cookieManagerImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

func wrapCookieManager(ptr unsafe.Pointer) CookieManager {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFCookieManagerT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &cookieManagerImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*cookieManagerImpl).Release)
	return impl
}

// takeCookieManager adopts a CEF CookieManager pointer whose reference is already owned by
// the caller (as returned by a global factory function). Unlike wrapCookieManager it
// does NOT call AddRef, because the C API already transferred one reference to us.
func takeCookieManager(ptr unsafe.Pointer) CookieManager {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFCookieManagerT)(ptr)
	impl := &cookieManagerImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*cookieManagerImpl).Release)
	return impl
}

// CookieVisitor Structure to implement for visiting cookie values. The functions of this structure will always be called on the UI thread.
type CookieVisitor = portin.CookieVisitor

// cookieVisitorWrapper wraps a user-provided CookieVisitor implementation together
// with the raw CEF struct pointer allocated by NewCookieVisitor.  It satisfies the
// CookieVisitor interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type cookieVisitorWrapper struct {
	CookieVisitor // embed user impl for interface delegation
	rawPtr        *capi.CEFCookieVisitorT
}

func (w *cookieVisitorWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

var cookieVisitorVisitSharedOnce sync.Once
var cookieVisitorVisitSharedCallback uintptr

func cookieVisitorVisitCEFCallback() uintptr {
	return sharedCEFCallback(&cookieVisitorVisitSharedOnce, &cookieVisitorVisitSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
		impl, ownerOK := cefCallbackOwnerAs[CookieVisitor](self)
		if !ownerOK {
			return 0
		}
		cookie := (*Cookie)(unsafe.Pointer(arg0))
		count := int32(arg1)
		total := int32(arg2)
		deletecookie := (*int32)(unsafe.Pointer(arg3))
		return uintptr(impl.Visit(cookie, count, total, deletecookie))
	})
}

// NewCookieVisitor creates a CEF handler backed by the given implementation.
func NewCookieVisitor(impl CookieVisitor) CookieVisitor {
	if isNilImpl(impl) {
		return nil
	}
	r := new(capi.CEFCookieVisitorT)
	w := &cookieVisitorWrapper{rawPtr: r}
	w.CookieVisitor = impl
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), w)

	r.OverrideVisit(cookieVisitorVisitCEFCallback())

	return w
}

// cookieVisitorImpl is a reverse wrapper for a CEF-owned CookieVisitor pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type cookieVisitorImpl struct {
	rawPtr      *capi.CEFCookieVisitorT
	releaseOnce sync.Once
}

func (obj *cookieVisitorImpl) Visit(cookie *Cookie, count int32, total int32, deletecookie *int32) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	ret := rawPtr.CallVisit(uintptr(unsafe.Pointer(cookie)), uintptr(count), uintptr(total), uintptr(unsafe.Pointer(deletecookie)))
	return int32(ret)
}

func (obj *cookieVisitorImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *cookieVisitorImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

// wrapCookieVisitor wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapCookieVisitor(ptr unsafe.Pointer) CookieVisitor {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFCookieVisitorT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &cookieVisitorImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*cookieVisitorImpl).Release)
	return impl
}

// SetCookieCallback Structure to implement to be notified of asynchronous completion via cef_cookie_manager_t::set_cookie().
type SetCookieCallback = portin.SetCookieCallback

// setCookieCallbackWrapper wraps a user-provided SetCookieCallback implementation together
// with the raw CEF struct pointer allocated by NewSetCookieCallback.  It satisfies the
// SetCookieCallback interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type setCookieCallbackWrapper struct {
	SetCookieCallback // embed user impl for interface delegation
	rawPtr            *capi.CEFSetCookieCallbackT
}

func (w *setCookieCallbackWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

var setCookieCallbackOnCompleteSharedOnce sync.Once
var setCookieCallbackOnCompleteSharedCallback uintptr

func setCookieCallbackOnCompleteCEFCallback() uintptr {
	return sharedCEFCallback(&setCookieCallbackOnCompleteSharedOnce, &setCookieCallbackOnCompleteSharedCallback, func(self uintptr, arg0 uintptr) {
		impl, ownerOK := cefCallbackOwnerAs[SetCookieCallback](self)
		if !ownerOK {
			return
		}
		success := int32(arg0)
		impl.OnComplete(success)
	})
}

// NewSetCookieCallback creates a CEF handler backed by the given implementation.
func NewSetCookieCallback(impl SetCookieCallback) SetCookieCallback {
	if isNilImpl(impl) {
		return nil
	}
	r := new(capi.CEFSetCookieCallbackT)
	w := &setCookieCallbackWrapper{rawPtr: r}
	w.SetCookieCallback = impl
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), w)

	r.OverrideOnComplete(setCookieCallbackOnCompleteCEFCallback())

	return w
}

// setCookieCallbackImpl is a reverse wrapper for a CEF-owned SetCookieCallback pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type setCookieCallbackImpl struct {
	rawPtr      *capi.CEFSetCookieCallbackT
	releaseOnce sync.Once
}

func (obj *setCookieCallbackImpl) OnComplete(success int32) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallOnComplete(uintptr(success))
}

func (obj *setCookieCallbackImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *setCookieCallbackImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

// wrapSetCookieCallback wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapSetCookieCallback(ptr unsafe.Pointer) SetCookieCallback {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFSetCookieCallbackT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &setCookieCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*setCookieCallbackImpl).Release)
	return impl
}

// DeleteCookiesCallback Structure to implement to be notified of asynchronous completion via cef_cookie_manager_t::delete_cookies().
type DeleteCookiesCallback = portin.DeleteCookiesCallback

// deleteCookiesCallbackWrapper wraps a user-provided DeleteCookiesCallback implementation together
// with the raw CEF struct pointer allocated by NewDeleteCookiesCallback.  It satisfies the
// DeleteCookiesCallback interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type deleteCookiesCallbackWrapper struct {
	DeleteCookiesCallback // embed user impl for interface delegation
	rawPtr                *capi.CEFDeleteCookiesCallbackT
}

func (w *deleteCookiesCallbackWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

var deleteCookiesCallbackOnCompleteSharedOnce sync.Once
var deleteCookiesCallbackOnCompleteSharedCallback uintptr

func deleteCookiesCallbackOnCompleteCEFCallback() uintptr {
	return sharedCEFCallback(&deleteCookiesCallbackOnCompleteSharedOnce, &deleteCookiesCallbackOnCompleteSharedCallback, func(self uintptr, arg0 uintptr) {
		impl, ownerOK := cefCallbackOwnerAs[DeleteCookiesCallback](self)
		if !ownerOK {
			return
		}
		numDeleted := int32(arg0)
		impl.OnComplete(numDeleted)
	})
}

// NewDeleteCookiesCallback creates a CEF handler backed by the given implementation.
func NewDeleteCookiesCallback(impl DeleteCookiesCallback) DeleteCookiesCallback {
	if isNilImpl(impl) {
		return nil
	}
	r := new(capi.CEFDeleteCookiesCallbackT)
	w := &deleteCookiesCallbackWrapper{rawPtr: r}
	w.DeleteCookiesCallback = impl
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), w)

	r.OverrideOnComplete(deleteCookiesCallbackOnCompleteCEFCallback())

	return w
}

// deleteCookiesCallbackImpl is a reverse wrapper for a CEF-owned DeleteCookiesCallback pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type deleteCookiesCallbackImpl struct {
	rawPtr      *capi.CEFDeleteCookiesCallbackT
	releaseOnce sync.Once
}

func (obj *deleteCookiesCallbackImpl) OnComplete(numDeleted int32) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallOnComplete(uintptr(numDeleted))
}

func (obj *deleteCookiesCallbackImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *deleteCookiesCallbackImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

// wrapDeleteCookiesCallback wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapDeleteCookiesCallback(ptr unsafe.Pointer) DeleteCookiesCallback {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFDeleteCookiesCallbackT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &deleteCookiesCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*deleteCookiesCallbackImpl).Release)
	return impl
}

// CookieManagerGetGlobalManager Returns the global cookie manager. By default data will be stored at cef_settings_t.cache_path if specified or in memory otherwise. If |callback| is non-NULL it will be executed asnychronously on the UI thread after the manager's storage has been initialized. Using this function is equivalent to calling cef_request_context_t::cef_request_context_get_global_context()- >GetDefaultCookieManager().
func CookieManagerGetGlobalManager(callback CompletionCallback) CookieManager {
	ret := capi.CEFCookieManagerGetGlobalManager(extractOrWrapRawPointer(callback, func() any { return NewCompletionCallback(callback) }))
	return takeCookieManager(ret)
}
