// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// ResourceBundle Structure used for retrieving resources from the resource bundle (*.pak) files loaded by CEF during startup or via the cef_resource_bundle_handler_t returned from cef_app_t::GetResourceBundleHandler. See CefSettings for additional options related to resource bundle loading. The functions of this structure may be called on any thread unless otherwise indicated.
type ResourceBundle interface {
	// GetLocalizedString Returns the localized string for the specified |string_id| or an NULL string if the value is not found. Use the cef_id_for_pack_string_name() function for version-safe mapping of string IDS names from cef_pack_strings.h to version-specific numerical |string_id| values.
	GetLocalizedString(stringID int32) string
	// GetDataResource Returns a cef_binary_value_t containing the decompressed contents of the specified scale independent |resource_id| or NULL if not found. Use the cef_id_for_pack_resource_name() function for version-safe mapping of resource IDR names from cef_pack_resources.h to version-specific numerical |resource_id| values.
	GetDataResource(resourceID int32) BinaryValue
	// GetDataResourceForScale Returns a cef_binary_value_t containing the decompressed contents of the specified |resource_id| nearest the scale factor |scale_factor| or NULL if not found. Use a |scale_factor| value of SCALE_FACTOR_NONE for scale independent resources or call GetDataResource instead. Use the cef_id_for_pack_resource_name() function for version-safe mapping of resource IDR names from cef_pack_resources.h to version-specific numerical |resource_id| values.
	GetDataResourceForScale(resourceID int32, scaleFactor ScaleFactor) BinaryValue
}

type resourceBundleImpl struct {
	rawPtr *raw.CEFResourceBundleT
}

func (obj *resourceBundleImpl) GetLocalizedString(stringID int32) string {
	return goStringUserfree(unsafe.Pointer(obj.rawPtr.CallGetLocalizedString(uintptr(0) /* stringID */)))
}

func (obj *resourceBundleImpl) GetDataResource(resourceID int32) BinaryValue {
	return wrapBinaryValue(unsafe.Pointer(obj.rawPtr.CallGetDataResource(uintptr(0) /* resourceID */)))
}

func (obj *resourceBundleImpl) GetDataResourceForScale(resourceID int32, scaleFactor ScaleFactor) BinaryValue {
	return wrapBinaryValue(unsafe.Pointer(obj.rawPtr.CallGetDataResourceForScale(uintptr(0) /* resourceID */, uintptr(0) /* scaleFactor */)))
}

func (obj *resourceBundleImpl) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *resourceBundleImpl) Release() {
	base := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapResourceBundle(ptr unsafe.Pointer) ResourceBundle {
	if ptr == nil {
		return nil
	}
	r := (*raw.CEFResourceBundleT)(ptr)
	base := (*raw.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &resourceBundleImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *resourceBundleImpl) {
		b := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// ResourceBundleGetGlobal Returns the global resource bundle instance.
func ResourceBundleGetGlobal() uintptr {
	// TODO: marshal args, call raw.CEFResourceBundleGetGlobal(...), marshal return
	_ = raw.CEFResourceBundleGetGlobal
	return 0
}
