// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// XmlReader Structure that supports the reading of XML data via the libxml streaming API. The functions of this structure should only be called on the thread that creates the object.
type XmlReader interface {
	// MoveToNextNode Moves the cursor to the next node in the document. This function must be called at least once to set the current cursor position. Returns true (1) if the cursor position was set successfully.
	MoveToNextNode() int32
	// Close Close the document. This should be called directly to ensure that cleanup occurs on the correct thread.
	Close() int32
	// HasError Returns true (1) if an error has been reported by the XML parser.
	HasError() bool
	// GetError Returns the error string.
	GetError() string
	// GetType Returns the node type.
	GetType() XmlNodeType
	// GetDepth Returns the node depth. Depth starts at 0 for the root node.
	GetDepth() int32
	// GetLocalName Returns the local name. See http://www.w3.org/TR/REC-xml-names/#NT- LocalPart for additional details.
	GetLocalName() string
	// GetPrefix Returns the namespace prefix. See http://www.w3.org/TR/REC-xml-names/ for additional details.
	GetPrefix() string
	// GetQualifiedName Returns the qualified name, equal to (Prefix:)LocalName. See http://www.w3.org/TR/REC-xml-names/#ns-qualnames for additional details.
	GetQualifiedName() string
	// GetNamespaceUri Returns the URI defining the namespace associated with the node. See http://www.w3.org/TR/REC-xml-names/ for additional details.
	GetNamespaceUri() string
	// GetBaseUri Returns the base URI of the node. See http://www.w3.org/TR/xmlbase/ for additional details.
	GetBaseUri() string
	// GetXmlLang Returns the xml:lang scope within which the node resides. See http://www.w3.org/TR/REC-xml/#sec-lang-tag for additional details.
	GetXmlLang() string
	// IsEmptyElement Returns true (1) if the node represents an NULL element. "<a/>" is considered NULL but "<a></a>" is not.
	IsEmptyElement() bool
	// HasValue Returns true (1) if the node has a text value.
	HasValue() bool
	// GetValue Returns the text value.
	GetValue() string
	// HasAttributes Returns true (1) if the node has attributes.
	HasAttributes() bool
	// GetAttributeCount Returns the number of attributes.
	GetAttributeCount() int
	// GetAttributeByindex Returns the value of the attribute at the specified 0-based index.
	GetAttributeByindex(index int32) string
	// GetAttributeByqname Returns the value of the attribute with the specified qualified name.
	GetAttributeByqname(qualifiedname string) string
	// GetAttributeBylname Returns the value of the attribute with the specified local name and namespace URI.
	GetAttributeBylname(localname string, namespaceuri string) string
	// GetInnerXml Returns an XML representation of the current node's children.
	GetInnerXml() string
	// GetOuterXml Returns an XML representation of the current node including its children.
	GetOuterXml() string
	// GetLineNumber Returns the line number for the current node.
	GetLineNumber() int32
	// MoveToAttributeByindex Moves the cursor to the attribute at the specified 0-based index. Returns true (1) if the cursor position was set successfully.
	MoveToAttributeByindex(index int32) int32
	// MoveToAttributeByqname Moves the cursor to the attribute with the specified qualified name. Returns true (1) if the cursor position was set successfully.
	MoveToAttributeByqname(qualifiedname string) int32
	// MoveToAttributeBylname Moves the cursor to the attribute with the specified local name and namespace URI. Returns true (1) if the cursor position was set successfully.
	MoveToAttributeBylname(localname string, namespaceuri string) int32
	// MoveToFirstAttribute Moves the cursor to the first attribute in the current element. Returns true (1) if the cursor position was set successfully.
	MoveToFirstAttribute() int32
	// MoveToNextAttribute Moves the cursor to the next attribute in the current element. Returns true (1) if the cursor position was set successfully.
	MoveToNextAttribute() int32
	// MoveToCarryingElement Moves the cursor back to the carrying element. Returns true (1) if the cursor position was set successfully.
	MoveToCarryingElement() int32
}

type xmlReaderImpl struct {
	rawPtr *raw.CEFXmlReaderT
}

func (obj *xmlReaderImpl) MoveToNextNode() int32 {
	ret := obj.rawPtr.CallMoveToNextNode()
	_ = ret
	return 0
}

func (obj *xmlReaderImpl) Close() int32 {
	ret := obj.rawPtr.CallClose()
	_ = ret
	return 0
}

func (obj *xmlReaderImpl) HasError() bool {
	return obj.rawPtr.CallHasError() != 0
}

func (obj *xmlReaderImpl) GetError() string {
	ret := obj.rawPtr.CallGetError()
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) GetType() XmlNodeType {
	return XmlNodeType(obj.rawPtr.CallGetType())
}

func (obj *xmlReaderImpl) GetDepth() int32 {
	ret := obj.rawPtr.CallGetDepth()
	_ = ret
	return 0
}

func (obj *xmlReaderImpl) GetLocalName() string {
	ret := obj.rawPtr.CallGetLocalName()
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) GetPrefix() string {
	ret := obj.rawPtr.CallGetPrefix()
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) GetQualifiedName() string {
	ret := obj.rawPtr.CallGetQualifiedName()
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) GetNamespaceUri() string {
	ret := obj.rawPtr.CallGetNamespaceUri()
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) GetBaseUri() string {
	ret := obj.rawPtr.CallGetBaseUri()
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) GetXmlLang() string {
	ret := obj.rawPtr.CallGetXmlLang()
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) IsEmptyElement() bool {
	return obj.rawPtr.CallIsEmptyElement() != 0
}

func (obj *xmlReaderImpl) HasValue() bool {
	return obj.rawPtr.CallHasValue() != 0
}

func (obj *xmlReaderImpl) GetValue() string {
	ret := obj.rawPtr.CallGetValue()
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) HasAttributes() bool {
	return obj.rawPtr.CallHasAttributes() != 0
}

func (obj *xmlReaderImpl) GetAttributeCount() int {
	ret := obj.rawPtr.CallGetAttributeCount()
	_ = ret
	return 0
}

func (obj *xmlReaderImpl) GetAttributeByindex(index int32) string {
	ret := obj.rawPtr.CallGetAttributeByindex(uintptr(0) /* index */)
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) GetAttributeByqname(qualifiedname string) string {
	ret := obj.rawPtr.CallGetAttributeByqname(uintptr(0) /* qualifiedname */)
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) GetAttributeBylname(localname string, namespaceuri string) string {
	ret := obj.rawPtr.CallGetAttributeBylname(uintptr(0) /* localname */, uintptr(0) /* namespaceuri */)
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) GetInnerXml() string {
	ret := obj.rawPtr.CallGetInnerXml()
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) GetOuterXml() string {
	ret := obj.rawPtr.CallGetOuterXml()
	_ = ret
	return ""
}

func (obj *xmlReaderImpl) GetLineNumber() int32 {
	ret := obj.rawPtr.CallGetLineNumber()
	_ = ret
	return 0
}

func (obj *xmlReaderImpl) MoveToAttributeByindex(index int32) int32 {
	ret := obj.rawPtr.CallMoveToAttributeByindex(uintptr(0) /* index */)
	_ = ret
	return 0
}

func (obj *xmlReaderImpl) MoveToAttributeByqname(qualifiedname string) int32 {
	ret := obj.rawPtr.CallMoveToAttributeByqname(uintptr(0) /* qualifiedname */)
	_ = ret
	return 0
}

func (obj *xmlReaderImpl) MoveToAttributeBylname(localname string, namespaceuri string) int32 {
	ret := obj.rawPtr.CallMoveToAttributeBylname(uintptr(0) /* localname */, uintptr(0) /* namespaceuri */)
	_ = ret
	return 0
}

func (obj *xmlReaderImpl) MoveToFirstAttribute() int32 {
	ret := obj.rawPtr.CallMoveToFirstAttribute()
	_ = ret
	return 0
}

func (obj *xmlReaderImpl) MoveToNextAttribute() int32 {
	ret := obj.rawPtr.CallMoveToNextAttribute()
	_ = ret
	return 0
}

func (obj *xmlReaderImpl) MoveToCarryingElement() int32 {
	ret := obj.rawPtr.CallMoveToCarryingElement()
	_ = ret
	return 0
}

// Release releases the underlying CEF object.
func (obj *xmlReaderImpl) Release() {
	base := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapXmlReader(ptr unsafe.Pointer) XmlReader {
	if ptr == nil {
		return nil
	}
	r := (*raw.CEFXmlReaderT)(ptr)
	base := (*raw.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &xmlReaderImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *xmlReaderImpl) {
		b := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// XmlReaderCreate Create a new cef_xml_reader_t object. The returned object's functions can only be called from the thread that created the object.
func XmlReaderCreate(stream StreamReader, encodingtype XmlEncodingType, uri string) uintptr {
	// TODO: marshal args, call raw.CEFXmlReaderCreate(...), marshal return
	_ = raw.CEFXmlReaderCreate
	return 0
}
