// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"sync"
	"unsafe"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// FileDialogCallback Callback structure for asynchronous continuation of file dialog requests.
type FileDialogCallback = portin.FileDialogCallback

// fileDialogCallbackImpl is a reverse wrapper for a CEF-owned FileDialogCallback pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type fileDialogCallbackImpl struct {
	rawPtr      *capi.CEFFileDialogCallbackT
	releaseOnce sync.Once
}

func (obj *fileDialogCallbackImpl) Cont(filePaths StringList) {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallCont(uintptr(filePaths))
}

func (obj *fileDialogCallbackImpl) Cancel() {
	if obj == nil || obj.rawPtr == nil {
		return
	}
	rawPtr := obj.rawPtr
	rawPtr.CallCancel()
}

func (obj *fileDialogCallbackImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *fileDialogCallbackImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

func wrapFileDialogCallback(ptr unsafe.Pointer) FileDialogCallback {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFFileDialogCallbackT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &fileDialogCallbackImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*fileDialogCallbackImpl).Release)
	return impl
}

// DialogHandler Implement this structure to handle dialog events. The functions of this structure will be called on the browser process UI thread.
type DialogHandler = portin.DialogHandler

// dialogHandlerWrapper wraps a user-provided DialogHandler implementation together
// with the raw CEF struct pointer allocated by NewDialogHandler.  It satisfies the
// DialogHandler interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type dialogHandlerWrapper struct {
	DialogHandler // embed user impl for interface delegation
	rawPtr        *capi.CEFDialogHandlerT
}

func (w *dialogHandlerWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

var dialogHandlerOnFileDialogSharedOnce sync.Once
var dialogHandlerOnFileDialogSharedCallback uintptr

func dialogHandlerOnFileDialogCEFCallback() uintptr {
	return sharedCEFCallback(&dialogHandlerOnFileDialogSharedOnce, &dialogHandlerOnFileDialogSharedCallback, func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr, arg6 uintptr, arg7 uintptr) uintptr {
		impl, ownerOK := cefCallbackOwnerAs[DialogHandler](self)
		if !ownerOK {
			return 0
		}
		browser := wrapBrowser(unsafe.Pointer(arg0))
		mode := FileDialogMode(arg1)
		title := goString(unsafe.Pointer(arg2))
		defaultFilePath := goString(unsafe.Pointer(arg3))
		acceptFilters := StringList(arg4)
		acceptExtensions := StringList(arg5)
		acceptDescriptions := StringList(arg6)
		callback := wrapFileDialogCallback(unsafe.Pointer(arg7))
		return uintptr(impl.OnFileDialog(browser, mode, title, defaultFilePath, acceptFilters, acceptExtensions, acceptDescriptions, callback))
	})
}

// NewDialogHandler creates a CEF handler backed by the given implementation.
func NewDialogHandler(impl DialogHandler) DialogHandler {
	if isNilImpl(impl) {
		return nil
	}
	r := new(capi.CEFDialogHandlerT)
	w := &dialogHandlerWrapper{rawPtr: r}
	w.DialogHandler = impl
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), w)

	r.OverrideOnFileDialog(dialogHandlerOnFileDialogCEFCallback())

	return w
}

// dialogHandlerImpl is a reverse wrapper for a CEF-owned DialogHandler pointer.
// Release is idempotent, but callers must externally synchronize Release with
// concurrent method calls and must not use the wrapper after Release returns.
type dialogHandlerImpl struct {
	rawPtr      *capi.CEFDialogHandlerT
	releaseOnce sync.Once
}

func (obj *dialogHandlerImpl) OnFileDialog(browser Browser, mode FileDialogMode, title string, defaultFilePath string, acceptFilters StringList, acceptExtensions StringList, acceptDescriptions StringList, callback FileDialogCallback) int32 {
	if obj == nil || obj.rawPtr == nil {
		return 0
	}
	rawPtr := obj.rawPtr
	titleStr := cefString(title)
	defer freeCefString(&titleStr)
	defaultFilePathStr := cefString(defaultFilePath)
	defer freeCefString(&defaultFilePathStr)
	ret := rawPtr.CallOnFileDialog(uintptr(extractRawPointer(browser)), uintptr(mode), uintptr(unsafe.Pointer(&titleStr)), uintptr(unsafe.Pointer(&defaultFilePathStr)), uintptr(acceptFilters), uintptr(acceptExtensions), uintptr(acceptDescriptions), uintptr(extractRawPointer(callback)))
	return int32(ret)
}

func (obj *dialogHandlerImpl) RawPointer() unsafe.Pointer {
	if obj == nil || obj.rawPtr == nil {
		return nil
	}
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *dialogHandlerImpl) Release() {
	if obj == nil {
		return
	}
	obj.releaseOnce.Do(func() {
		if obj.rawPtr == nil {
			return
		}
		rawPtr := obj.rawPtr
		obj.rawPtr = nil
		runtime.SetFinalizer(obj, nil)
		base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(rawPtr))
		base.CallRelease()
	})
}

// wrapDialogHandler wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapDialogHandler(ptr unsafe.Pointer) DialogHandler {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFDialogHandlerT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &dialogHandlerImpl{rawPtr: r}
	runtime.SetFinalizer(impl, (*dialogHandlerImpl).Release)
	return impl
}
