// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// Task Implement this structure for asynchronous task execution. If the task is posted successfully and if the associated message loop is still running then the execute() function will be called on the target thread. If the task fails to post then the task object may be destroyed on the source thread instead of the target thread. For this reason be cautious when performing work in the task object destructor.
type Task = portin.Task

// taskWrapper wraps a user-provided Task implementation together
// with the raw CEF struct pointer allocated by NewTask.  It satisfies the
// Task interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type taskWrapper struct {
	Task   // embed user impl for interface delegation
	rawPtr *capi.CEFTaskT
}

func (w *taskWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewTask creates a CEF handler backed by the given implementation.
func NewTask(impl Task) Task {
	if isNilImpl(impl) {
		return nil
	}
	r := new(capi.CEFTaskT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideExecute(purego.NewCallback(func(self uintptr) {
		impl.Execute()
	}))

	w := &taskWrapper{rawPtr: r}
	w.Task = impl
	return w
}

type taskImpl struct {
	rawPtr *capi.CEFTaskT
}

func (obj *taskImpl) Execute() {
	obj.rawPtr.CallExecute()
}

func (obj *taskImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *taskImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

// wrapTask wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapTask(ptr unsafe.Pointer) Task {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFTaskT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &taskImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *taskImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// TaskRunner Structure that asynchronously executes tasks on the associated thread. It is safe to call the functions of this structure on any thread. CEF maintains multiple internal threads that are used for handling different types of tasks in different processes. The cef_thread_id_t definitions in cef_types.h list the common CEF threads. Task runners are also available for other CEF threads as appropriate (for example, V8 WebWorker threads).
type TaskRunner = portin.TaskRunner

type taskRunnerImpl struct {
	rawPtr *capi.CEFTaskRunnerT
}

func (obj *taskRunnerImpl) IsSame(that TaskRunner) bool {
	ret := obj.rawPtr.CallIsSame(uintptr(extractRawPointer(that)))
	return ret != 0
}

func (obj *taskRunnerImpl) BelongsToCurrentThread() int32 {
	ret := obj.rawPtr.CallBelongsToCurrentThread()
	return int32(ret)
}

func (obj *taskRunnerImpl) BelongsToThread(threadid ThreadID) int32 {
	ret := obj.rawPtr.CallBelongsToThread(uintptr(threadid))
	return int32(ret)
}

func (obj *taskRunnerImpl) PostTask(task Task) int32 {
	ret := obj.rawPtr.CallPostTask(uintptr(extractOrWrapRawPointer(task, func() any { return NewTask(task) })))
	return int32(ret)
}

func (obj *taskRunnerImpl) PostDelayedTask(task Task, delayMs int64) int32 {
	ret := obj.rawPtr.CallPostDelayedTask(uintptr(extractOrWrapRawPointer(task, func() any { return NewTask(task) })), uintptr(delayMs))
	return int32(ret)
}

func (obj *taskRunnerImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *taskRunnerImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapTaskRunner(ptr unsafe.Pointer) TaskRunner {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFTaskRunnerT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &taskRunnerImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *taskRunnerImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// TaskRunnerGetForCurrentThread Returns the task runner for the current thread. Only CEF threads will have task runners. An NULL reference will be returned if this function is called on an invalid thread.
func TaskRunnerGetForCurrentThread() TaskRunner {
	ret := capi.CEFTaskRunnerGetForCurrentThread()
	return wrapTaskRunner(ret)
}

// TaskRunnerGetForThread Returns the task runner for the specified CEF thread.
func TaskRunnerGetForThread(threadid ThreadID) TaskRunner {
	ret := capi.CEFTaskRunnerGetForThread(capi.CEFThreadIDT(threadid))
	return wrapTaskRunner(ret)
}

// CurrentlyOn Returns true (1) if called on the specified thread. Equivalent to using cef_task_runner_t::GetForThread(threadId)->belongs_to_current_thread().
func CurrentlyOn(threadid ThreadID) int32 {
	ret := capi.CEFCurrentlyOn(capi.CEFThreadIDT(threadid))
	return int32(ret)
}

// PostTask Post a task for execution on the specified thread. Equivalent to using cef_task_runner_t::GetForThread(threadId)->PostTask(task).
func PostTask(threadid ThreadID, task Task) int32 {
	ret := capi.CEFPostTask(capi.CEFThreadIDT(threadid), extractOrWrapRawPointer(task, func() any { return NewTask(task) }))
	return int32(ret)
}

// PostDelayedTask Post a task for delayed execution on the specified thread. Equivalent to using cef_task_runner_t::GetForThread(threadId)->PostDelayedTask(task, delay_ms).
func PostDelayedTask(threadid ThreadID, task Task, delayMs int64) int32 {
	ret := capi.CEFPostDelayedTask(capi.CEFThreadIDT(threadid), extractOrWrapRawPointer(task, func() any { return NewTask(task) }), delayMs)
	return int32(ret)
}
