// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"unsafe"

	"github.com/bnema/purego"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// Client Implement this structure to provide handler implementations.
type Client = portin.Client

// clientWrapper wraps a user-provided Client implementation together
// with the raw CEF struct pointer allocated by newRawClient.  It satisfies the
// Client interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type clientWrapper struct {
	Client // embed user impl for interface delegation
	rawPtr *capi.CEFClientT
}

func (w *clientWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// newRawClient creates a CEF handler backed by the given implementation.
func newRawClient(impl Client) Client {
	r := new(capi.CEFClientT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetAudioHandlerPtr unsafe.Pointer
	if h := impl.GetAudioHandler(); h != nil {
		cachedGetAudioHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewAudioHandler(h)
		})
	}
	r.OverrideGetAudioHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetAudioHandlerPtr != nil {
			addRef(cachedGetAudioHandlerPtr)
		}
		return uintptr(cachedGetAudioHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetCommandHandlerPtr unsafe.Pointer
	if h := impl.GetCommandHandler(); h != nil {
		cachedGetCommandHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewCommandHandler(h)
		})
	}
	r.OverrideGetCommandHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetCommandHandlerPtr != nil {
			addRef(cachedGetCommandHandlerPtr)
		}
		return uintptr(cachedGetCommandHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetContextMenuHandlerPtr unsafe.Pointer
	if h := impl.GetContextMenuHandler(); h != nil {
		cachedGetContextMenuHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewContextMenuHandler(h)
		})
	}
	r.OverrideGetContextMenuHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetContextMenuHandlerPtr != nil {
			addRef(cachedGetContextMenuHandlerPtr)
		}
		return uintptr(cachedGetContextMenuHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetDialogHandlerPtr unsafe.Pointer
	if h := impl.GetDialogHandler(); h != nil {
		cachedGetDialogHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewDialogHandler(h)
		})
	}
	r.OverrideGetDialogHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetDialogHandlerPtr != nil {
			addRef(cachedGetDialogHandlerPtr)
		}
		return uintptr(cachedGetDialogHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetDisplayHandlerPtr unsafe.Pointer
	if h := impl.GetDisplayHandler(); h != nil {
		cachedGetDisplayHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewDisplayHandler(h)
		})
	}
	r.OverrideGetDisplayHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetDisplayHandlerPtr != nil {
			addRef(cachedGetDisplayHandlerPtr)
		}
		return uintptr(cachedGetDisplayHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetDownloadHandlerPtr unsafe.Pointer
	if h := impl.GetDownloadHandler(); h != nil {
		cachedGetDownloadHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewDownloadHandler(h)
		})
	}
	r.OverrideGetDownloadHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetDownloadHandlerPtr != nil {
			addRef(cachedGetDownloadHandlerPtr)
		}
		return uintptr(cachedGetDownloadHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetDragHandlerPtr unsafe.Pointer
	if h := impl.GetDragHandler(); h != nil {
		cachedGetDragHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewDragHandler(h)
		})
	}
	r.OverrideGetDragHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetDragHandlerPtr != nil {
			addRef(cachedGetDragHandlerPtr)
		}
		return uintptr(cachedGetDragHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetFindHandlerPtr unsafe.Pointer
	if h := impl.GetFindHandler(); h != nil {
		cachedGetFindHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewFindHandler(h)
		})
	}
	r.OverrideGetFindHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetFindHandlerPtr != nil {
			addRef(cachedGetFindHandlerPtr)
		}
		return uintptr(cachedGetFindHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetFocusHandlerPtr unsafe.Pointer
	if h := impl.GetFocusHandler(); h != nil {
		cachedGetFocusHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewFocusHandler(h)
		})
	}
	r.OverrideGetFocusHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetFocusHandlerPtr != nil {
			addRef(cachedGetFocusHandlerPtr)
		}
		return uintptr(cachedGetFocusHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetFrameHandlerPtr unsafe.Pointer
	if h := impl.GetFrameHandler(); h != nil {
		cachedGetFrameHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewFrameHandler(h)
		})
	}
	r.OverrideGetFrameHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetFrameHandlerPtr != nil {
			addRef(cachedGetFrameHandlerPtr)
		}
		return uintptr(cachedGetFrameHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetPermissionHandlerPtr unsafe.Pointer
	if h := impl.GetPermissionHandler(); h != nil {
		cachedGetPermissionHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewPermissionHandler(h)
		})
	}
	r.OverrideGetPermissionHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetPermissionHandlerPtr != nil {
			addRef(cachedGetPermissionHandlerPtr)
		}
		return uintptr(cachedGetPermissionHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetJsdialogHandlerPtr unsafe.Pointer
	if h := impl.GetJsdialogHandler(); h != nil {
		cachedGetJsdialogHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewJsdialogHandler(h)
		})
	}
	r.OverrideGetJsdialogHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetJsdialogHandlerPtr != nil {
			addRef(cachedGetJsdialogHandlerPtr)
		}
		return uintptr(cachedGetJsdialogHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetKeyboardHandlerPtr unsafe.Pointer
	if h := impl.GetKeyboardHandler(); h != nil {
		cachedGetKeyboardHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewKeyboardHandler(h)
		})
	}
	r.OverrideGetKeyboardHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetKeyboardHandlerPtr != nil {
			addRef(cachedGetKeyboardHandlerPtr)
		}
		return uintptr(cachedGetKeyboardHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetLifeSpanHandlerPtr unsafe.Pointer
	if h := impl.GetLifeSpanHandler(); h != nil {
		cachedGetLifeSpanHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return newRawLifeSpanHandler(h)
		})
	}
	r.OverrideGetLifeSpanHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetLifeSpanHandlerPtr != nil {
			addRef(cachedGetLifeSpanHandlerPtr)
		}
		return uintptr(cachedGetLifeSpanHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetLoadHandlerPtr unsafe.Pointer
	if h := impl.GetLoadHandler(); h != nil {
		cachedGetLoadHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewLoadHandler(h)
		})
	}
	r.OverrideGetLoadHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetLoadHandlerPtr != nil {
			addRef(cachedGetLoadHandlerPtr)
		}
		return uintptr(cachedGetLoadHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetPrintHandlerPtr unsafe.Pointer
	if h := impl.GetPrintHandler(); h != nil {
		cachedGetPrintHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewPrintHandler(h)
		})
	}
	r.OverrideGetPrintHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetPrintHandlerPtr != nil {
			addRef(cachedGetPrintHandlerPtr)
		}
		return uintptr(cachedGetPrintHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetRenderHandlerPtr unsafe.Pointer
	if h := impl.GetRenderHandler(); h != nil {
		cachedGetRenderHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewRenderHandler(h)
		})
	}
	r.OverrideGetRenderHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetRenderHandlerPtr != nil {
			addRef(cachedGetRenderHandlerPtr)
		}
		return uintptr(cachedGetRenderHandlerPtr)
	}))

	// Cache the fully-wrapped handler once to avoid allocating on every callback.
	var cachedGetRequestHandlerPtr unsafe.Pointer
	if h := impl.GetRequestHandler(); h != nil {
		cachedGetRequestHandlerPtr = extractOrWrapRawPointer(h, func() any {
			return NewRequestHandler(h)
		})
	}
	r.OverrideGetRequestHandler(purego.NewCallback(func(_ uintptr) uintptr {
		if cachedGetRequestHandlerPtr != nil {
			addRef(cachedGetRequestHandlerPtr)
		}
		return uintptr(cachedGetRequestHandlerPtr)
	}))

	r.OverrideOnProcessMessageReceived(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
		browser := wrapBrowser(unsafe.Pointer(arg0))
		frame := wrapFrame(unsafe.Pointer(arg1))
		sourceProcess := ProcessID(arg2)
		message := wrapProcessMessage(unsafe.Pointer(arg3))
		return uintptr(impl.OnProcessMessageReceived(browser, frame, sourceProcess, message))
	}))

	w := &clientWrapper{rawPtr: r}
	w.Client = impl
	return w
}

// wrapClient wraps a CEF handler pointer received from CEF into a Go interface.
// This is a no-op wrapper since handler pointers from CEF are opaque; the returned
// interface is a thin facade that cannot call back into the original implementation.
func wrapClient(ptr unsafe.Pointer) Client {
	// Handler pointers returned by CEF cannot be meaningfully wrapped because
	// the underlying function pointers may be Go callbacks that we cannot call
	// back through purego.  Return nil for now; callers that need the handler
	// should keep their own reference.
	return nil
}
