// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/ebitengine/purego"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// MenuButtonPressedLock MenuButton pressed lock is released when this object is destroyed.
type MenuButtonPressedLock interface {
}

type menuButtonPressedLockImpl struct {
	rawPtr *raw.CEFMenuButtonPressedLockT
}

func (obj *menuButtonPressedLockImpl) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *menuButtonPressedLockImpl) Release() {
	base := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapMenuButtonPressedLock(ptr unsafe.Pointer) MenuButtonPressedLock {
	if ptr == nil {
		return nil
	}
	r := (*raw.CEFMenuButtonPressedLockT)(ptr)
	base := (*raw.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &menuButtonPressedLockImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *menuButtonPressedLockImpl) {
		b := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// MenuButtonDelegate Implement this structure to handle MenuButton events. The functions of this structure will be called on the browser process UI thread unless otherwise indicated.
type MenuButtonDelegate interface {
	// OnMenuButtonPressed Called when |button| is pressed. Call cef_menu_button_t::show_menu() to show a popup menu at |screen_point|. When showing a custom popup such as a window keep a reference to |button_pressed_lock| until the popup is hidden to maintain the pressed button state.
	OnMenuButtonPressed(menuButton MenuButton, screenPoint *Point, buttonPressedLock MenuButtonPressedLock)
}

// menuButtonDelegateWrapper wraps a user-provided MenuButtonDelegate implementation together
// with the raw CEF struct pointer allocated by NewMenuButtonDelegate.  It satisfies the
// MenuButtonDelegate interface (by embedding the user impl) and rawPointerHolder (so
// extractRawPointer can recover the raw pointer).
type menuButtonDelegateWrapper struct {
	MenuButtonDelegate // embed user impl for interface delegation
	rawPtr             *raw.CEFMenuButtonDelegateT
}

func (w *menuButtonDelegateWrapper) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewMenuButtonDelegate creates a CEF handler backed by the given implementation.
// The returned value can be passed directly to CEF functions that expect
// this handler type (e.g. BrowserHostCreateBrowser for Client).
func NewMenuButtonDelegate(impl MenuButtonDelegate) MenuButtonDelegate {
	r := new(raw.CEFMenuButtonDelegateT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnMenuButtonPressed(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr) {
		menuButton := wrapMenuButton(unsafe.Pointer(arg0))
		screenPoint := (*Point)(unsafe.Pointer(arg1))
		buttonPressedLock := wrapMenuButtonPressedLock(unsafe.Pointer(arg2))
		impl.OnMenuButtonPressed(menuButton, screenPoint, buttonPressedLock)
	}))

	w := &menuButtonDelegateWrapper{rawPtr: r}
	w.MenuButtonDelegate = impl
	return w
}

// wrapMenuButtonDelegate wraps a CEF handler pointer received from CEF into a Go interface.
// This is a no-op wrapper since handler pointers from CEF are opaque; the returned
// interface is a thin facade that cannot call back into the original implementation.
func wrapMenuButtonDelegate(ptr unsafe.Pointer) MenuButtonDelegate {
	// Handler pointers returned by CEF cannot be meaningfully wrapped because
	// the underlying function pointers may be Go callbacks that we cannot call
	// back through purego.  Return nil for now; callers that need the handler
	// should keep their own reference.
	return nil
}
