// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// ScrollView A ScrollView will show horizontal and/or vertical scrollbars when necessary based on the size of the attached content view. Methods must be called on the browser process UI thread unless otherwise indicated.
type ScrollView = portin.ScrollView

type scrollViewImpl struct {
	rawPtr *capi.CEFScrollViewT
}

func (obj *scrollViewImpl) SetContentView(view View) {
	obj.rawPtr.CallSetContentView(uintptr(extractRawPointer(view)))
}

func (obj *scrollViewImpl) GetContentView() View {
	return wrapView(unsafe.Pointer(obj.rawPtr.CallGetContentView()))
}

func (obj *scrollViewImpl) GetVisibleContentRect() uintptr {
	return uintptr(obj.rawPtr.CallGetVisibleContentRect())
}

func (obj *scrollViewImpl) HasHorizontalScrollbar() bool {
	return obj.rawPtr.CallHasHorizontalScrollbar() != 0
}

func (obj *scrollViewImpl) GetHorizontalScrollbarHeight() int32 {
	return int32(obj.rawPtr.CallGetHorizontalScrollbarHeight())
}

func (obj *scrollViewImpl) HasVerticalScrollbar() bool {
	return obj.rawPtr.CallHasVerticalScrollbar() != 0
}

func (obj *scrollViewImpl) GetVerticalScrollbarWidth() int32 {
	return int32(obj.rawPtr.CallGetVerticalScrollbarWidth())
}

func (obj *scrollViewImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *scrollViewImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapScrollView(ptr unsafe.Pointer) ScrollView {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFScrollViewT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &scrollViewImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *scrollViewImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// ScrollViewCreate Create a new ScrollView.
func ScrollViewCreate(delegate ViewDelegate) ScrollView {
	return wrapScrollView(capi.CEFScrollViewCreate(extractRawPointer(delegate)))
}
