// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"unsafe"

	"github.com/ebitengine/purego"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// BrowserViewDelegate Implement this structure to handle BrowserView events. The functions of this structure will be called on the browser process UI thread unless otherwise indicated.
type BrowserViewDelegate = portin.BrowserViewDelegate

// browserViewDelegateWrapper wraps a user-provided BrowserViewDelegate implementation together
// with the raw CEF struct pointer allocated by NewBrowserViewDelegate.  It satisfies the
// BrowserViewDelegate interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type browserViewDelegateWrapper struct {
	BrowserViewDelegate // embed user impl for interface delegation
	rawPtr              *capi.CEFBrowserViewDelegateT
}

func (w *browserViewDelegateWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewBrowserViewDelegate creates a CEF handler backed by the given implementation.
// The returned value can be passed directly to CEF functions that expect
// this handler type (e.g. BrowserHostCreateBrowser for Client).
func NewBrowserViewDelegate(impl BrowserViewDelegate) BrowserViewDelegate {
	r := new(capi.CEFBrowserViewDelegateT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	r.OverrideOnBrowserCreated(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr) {
		browserView := wrapBrowserView(unsafe.Pointer(arg0))
		browser := wrapBrowser(unsafe.Pointer(arg1))
		impl.OnBrowserCreated(browserView, browser)
	}))

	r.OverrideOnBrowserDestroyed(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr) {
		browserView := wrapBrowserView(unsafe.Pointer(arg0))
		browser := wrapBrowser(unsafe.Pointer(arg1))
		impl.OnBrowserDestroyed(browserView, browser)
	}))

	r.OverrideGetDelegateForPopupBrowserView(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
		browserView := wrapBrowserView(unsafe.Pointer(arg0))
		settings := (*BrowserSettings)(unsafe.Pointer(arg1))
		client := wrapClient(unsafe.Pointer(arg2))
		isDevtools := int32(arg3)
		result := impl.GetDelegateForPopupBrowserView(browserView, settings, client, isDevtools)
		if result == nil {
			return 0
		}
		return uintptr(extractOrWrapRawPointer(result, func() any {
			return NewBrowserViewDelegate(result)
		}))
	}))

	r.OverrideOnPopupBrowserViewCreated(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
		browserView := wrapBrowserView(unsafe.Pointer(arg0))
		popupBrowserView := wrapBrowserView(unsafe.Pointer(arg1))
		isDevtools := int32(arg2)
		return uintptr(impl.OnPopupBrowserViewCreated(browserView, popupBrowserView, isDevtools))
	}))

	r.OverrideGetChromeToolbarType(purego.NewCallback(func(self uintptr, arg0 uintptr) uintptr {
		browserView := wrapBrowserView(unsafe.Pointer(arg0))
		return uintptr(impl.GetChromeToolbarType(browserView))
	}))

	r.OverrideUseFramelessWindowForPictureInPicture(purego.NewCallback(func(self uintptr, arg0 uintptr) uintptr {
		browserView := wrapBrowserView(unsafe.Pointer(arg0))
		return uintptr(impl.UseFramelessWindowForPictureInPicture(browserView))
	}))

	r.OverrideOnGestureCommand(purego.NewCallback(func(self uintptr, arg0 uintptr, arg1 uintptr) uintptr {
		browserView := wrapBrowserView(unsafe.Pointer(arg0))
		gestureCommand := GestureCommand(arg1)
		return uintptr(impl.OnGestureCommand(browserView, gestureCommand))
	}))

	r.OverrideGetBrowserRuntimeStyle(purego.NewCallback(func(self uintptr) uintptr {
		return uintptr(impl.GetBrowserRuntimeStyle())
	}))

	r.OverrideAllowMoveForPictureInPicture(purego.NewCallback(func(self uintptr, arg0 uintptr) uintptr {
		browserView := wrapBrowserView(unsafe.Pointer(arg0))
		return uintptr(impl.AllowMoveForPictureInPicture(browserView))
	}))

	r.OverrideAllowPictureInPictureWithoutUserActivation(purego.NewCallback(func(self uintptr, arg0 uintptr) uintptr {
		browserView := wrapBrowserView(unsafe.Pointer(arg0))
		return uintptr(impl.AllowPictureInPictureWithoutUserActivation(browserView))
	}))

	w := &browserViewDelegateWrapper{rawPtr: r}
	w.BrowserViewDelegate = impl
	return w
}

// wrapBrowserViewDelegate wraps a CEF handler pointer received from CEF into a Go interface.
// This is a no-op wrapper since handler pointers from CEF are opaque; the returned
// interface is a thin facade that cannot call back into the original implementation.
func wrapBrowserViewDelegate(ptr unsafe.Pointer) BrowserViewDelegate {
	// Handler pointers returned by CEF cannot be meaningfully wrapped because
	// the underlying function pointers may be Go callbacks that we cannot call
	// back through purego.  Return nil for now; callers that need the handler
	// should keep their own reference.
	return nil
}
