// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego-cef/internal/capi"

	portin "github.com/bnema/purego-cef/internal/ports/in"
)

// PanelDelegate Implement this structure to handle Panel events. The functions of this structure will be called on the browser process UI thread unless otherwise indicated.
type PanelDelegate = portin.PanelDelegate

// panelDelegateWrapper wraps a user-provided PanelDelegate implementation together
// with the raw CEF struct pointer allocated by NewPanelDelegate.  It satisfies the
// PanelDelegate interface (by embedding the user impl) and core.RawPointerHolder
// (so extractRawPointer can recover the raw pointer).
type panelDelegateWrapper struct {
	PanelDelegate // embed user impl for interface delegation
	rawPtr        *capi.CEFPanelDelegateT
}

func (w *panelDelegateWrapper) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewPanelDelegate creates a CEF handler backed by the given implementation.
func NewPanelDelegate(impl PanelDelegate) PanelDelegate {
	r := new(capi.CEFPanelDelegateT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	w := &panelDelegateWrapper{rawPtr: r}
	w.PanelDelegate = impl
	return w
}

type panelDelegateImpl struct {
	rawPtr *capi.CEFPanelDelegateT
}

func (obj *panelDelegateImpl) RawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *panelDelegateImpl) Release() {
	base := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

// wrapPanelDelegate wraps a CEF handler pointer received from CEF into a thin Go façade.
func wrapPanelDelegate(ptr unsafe.Pointer) PanelDelegate {
	if ptr == nil {
		return nil
	}
	r := (*capi.CEFPanelDelegateT)(ptr)
	base := (*capi.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &panelDelegateImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *panelDelegateImpl) {
		b := (*capi.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}
