// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"unsafe"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// PanelDelegate Implement this structure to handle Panel events. The functions of this structure will be called on the browser process UI thread unless otherwise indicated.
type PanelDelegate interface {
}

// panelDelegateWrapper wraps a user-provided PanelDelegate implementation together
// with the raw CEF struct pointer allocated by NewPanelDelegate.  It satisfies the
// PanelDelegate interface (by embedding the user impl) and rawPointerHolder (so
// extractRawPointer can recover the raw pointer).
type panelDelegateWrapper struct {
	PanelDelegate // embed user impl for interface delegation
	rawPtr        *raw.CEFPanelDelegateT
}

func (w *panelDelegateWrapper) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(w.rawPtr)
}

// NewPanelDelegate creates a CEF handler backed by the given implementation.
// The returned value can be passed directly to CEF functions that expect
// this handler type (e.g. BrowserHostCreateBrowser for Client).
func NewPanelDelegate(impl PanelDelegate) PanelDelegate {
	r := new(raw.CEFPanelDelegateT)
	initRefCount(unsafe.Pointer(r), unsafe.Sizeof(*r), r)

	w := &panelDelegateWrapper{rawPtr: r}
	w.PanelDelegate = impl
	return w
}

// wrapPanelDelegate wraps a CEF handler pointer received from CEF into a Go interface.
// This is a no-op wrapper since handler pointers from CEF are opaque; the returned
// interface is a thin facade that cannot call back into the original implementation.
func wrapPanelDelegate(ptr unsafe.Pointer) PanelDelegate {
	// Handler pointers returned by CEF cannot be meaningfully wrapped because
	// the underlying function pointers may be Go callbacks that we cannot call
	// back through purego.  Return nil for now; callers that need the handler
	// should keep their own reference.
	return nil
}
