// Code generated by cefgen. DO NOT EDIT.

package cef

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego-cef/cef/internal/raw"
)

// Textfield A Textfield supports editing of text. This control is custom rendered with no platform-specific code. Methods must be called on the browser process UI thread unless otherwise indicated.
type Textfield interface {
	// SetPasswordInput Sets whether the text will be displayed as asterisks.
	SetPasswordInput(passwordInput int32)
	// IsPasswordInput Returns true (1) if the text will be displayed as asterisks.
	IsPasswordInput() bool
	// SetReadOnly Sets whether the text will read-only.
	SetReadOnly(readOnly int32)
	// IsReadOnly Returns true (1) if the text is read-only.
	IsReadOnly() bool
	// GetText Returns the currently displayed text.
	GetText() string
	// SetText Sets the contents to |text|. The cursor will be moved to end of the text if the current position is outside of the text range.
	SetText(text string)
	// AppendText Appends |text| to the previously-existing text.
	AppendText(text string)
	// InsertOrReplaceText Inserts |text| at the current cursor position replacing any selected text.
	InsertOrReplaceText(text string)
	// HasSelection Returns true (1) if there is any selected text.
	HasSelection() bool
	// GetSelectedText Returns the currently selected text.
	GetSelectedText() string
	// SelectAll Selects all text. If |reversed| is true (1) the range will end at the logical beginning of the text; this generally shows the leading portion of text that overflows its display area.
	SelectAll(reversed int32)
	// ClearSelection Clears the text selection and sets the caret to the end.
	ClearSelection()
	// GetSelectedRange Returns the selected logical text range.
	GetSelectedRange() uintptr
	// SelectRange Selects the specified logical text range.
	SelectRange(range_ uintptr)
	// GetCursorPosition Returns the current cursor position.
	GetCursorPosition() int
	// SetTextColor Sets the text color.
	SetTextColor(color uintptr)
	// GetTextColor Returns the text color.
	GetTextColor() uintptr
	// SetSelectionTextColor Sets the selection text color.
	SetSelectionTextColor(color uintptr)
	// GetSelectionTextColor Returns the selection text color.
	GetSelectionTextColor() uintptr
	// SetSelectionBackgroundColor Sets the selection background color.
	SetSelectionBackgroundColor(color uintptr)
	// GetSelectionBackgroundColor Returns the selection background color.
	GetSelectionBackgroundColor() uintptr
	// SetFontList Sets the font list. The format is "<FONT_FAMILY_LIST>,[STYLES] <SIZE>", where: - FONT_FAMILY_LIST is a comma-separated list of font family names, - STYLES is an optional space-separated list of style names (case-   sensitive "Bold" and "Italic" are supported), and - SIZE is an integer font size in pixels with the suffix "px". Here are examples of valid font description strings: - "Arial, Helvetica, Bold Italic 14px" - "Arial, 14px"
	SetFontList(fontList string)
	// ApplyTextColor Applies |color| to the specified |range| without changing the default color. If |range| is NULL the color will be set on the complete text contents.
	ApplyTextColor(color uintptr, range_ uintptr)
	// ApplyTextStyle Applies |style| to the specified |range| without changing the default style. If |add| is true (1) the style will be added, otherwise the style will be removed. If |range| is NULL the style will be set on the complete text contents.
	ApplyTextStyle(style TextStyle, add int32, range_ uintptr)
	// IsCommandEnabled Returns true (1) if the action associated with the specified command id is enabled. See additional comments on execute_command().
	IsCommandEnabled(commandID TextFieldCommands) bool
	ExecuteCommand(commandID TextFieldCommands)
	// ClearEditHistory Clears Edit history.
	ClearEditHistory()
	// SetPlaceholderText Sets the placeholder text that will be displayed when the Textfield is NULL.
	SetPlaceholderText(text string)
	// GetPlaceholderText Returns the placeholder text that will be displayed when the Textfield is NULL.
	GetPlaceholderText() string
	// SetPlaceholderTextColor Sets the placeholder text color.
	SetPlaceholderTextColor(color uintptr)
	// SetAccessibleName Set the accessible name that will be exposed to assistive technology (AT).
	SetAccessibleName(name string)
}

type textfieldImpl struct {
	rawPtr *raw.CEFTextfieldT
}

func (obj *textfieldImpl) SetPasswordInput(passwordInput int32) {
	obj.rawPtr.CallSetPasswordInput(uintptr(passwordInput))
}

func (obj *textfieldImpl) IsPasswordInput() bool {
	return obj.rawPtr.CallIsPasswordInput() != 0
}

func (obj *textfieldImpl) SetReadOnly(readOnly int32) {
	obj.rawPtr.CallSetReadOnly(uintptr(readOnly))
}

func (obj *textfieldImpl) IsReadOnly() bool {
	return obj.rawPtr.CallIsReadOnly() != 0
}

func (obj *textfieldImpl) GetText() string {
	return goStringUserfree(unsafe.Pointer(obj.rawPtr.CallGetText()))
}

func (obj *textfieldImpl) SetText(text string) {
	textStr := cefString(text)
	defer freeCefString(&textStr)
	obj.rawPtr.CallSetText(uintptr(unsafe.Pointer(&textStr)))
}

func (obj *textfieldImpl) AppendText(text string) {
	textStr := cefString(text)
	defer freeCefString(&textStr)
	obj.rawPtr.CallAppendText(uintptr(unsafe.Pointer(&textStr)))
}

func (obj *textfieldImpl) InsertOrReplaceText(text string) {
	textStr := cefString(text)
	defer freeCefString(&textStr)
	obj.rawPtr.CallInsertOrReplaceText(uintptr(unsafe.Pointer(&textStr)))
}

func (obj *textfieldImpl) HasSelection() bool {
	return obj.rawPtr.CallHasSelection() != 0
}

func (obj *textfieldImpl) GetSelectedText() string {
	return goStringUserfree(unsafe.Pointer(obj.rawPtr.CallGetSelectedText()))
}

func (obj *textfieldImpl) SelectAll(reversed int32) {
	obj.rawPtr.CallSelectAll(uintptr(reversed))
}

func (obj *textfieldImpl) ClearSelection() {
	obj.rawPtr.CallClearSelection()
}

func (obj *textfieldImpl) GetSelectedRange() uintptr {
	return uintptr(obj.rawPtr.CallGetSelectedRange())
}

func (obj *textfieldImpl) SelectRange(range_ uintptr) {
	obj.rawPtr.CallSelectRange(uintptr(range_))
}

func (obj *textfieldImpl) GetCursorPosition() int {
	return int(obj.rawPtr.CallGetCursorPosition())
}

func (obj *textfieldImpl) SetTextColor(color uintptr) {
	obj.rawPtr.CallSetTextColor(uintptr(color))
}

func (obj *textfieldImpl) GetTextColor() uintptr {
	return uintptr(obj.rawPtr.CallGetTextColor())
}

func (obj *textfieldImpl) SetSelectionTextColor(color uintptr) {
	obj.rawPtr.CallSetSelectionTextColor(uintptr(color))
}

func (obj *textfieldImpl) GetSelectionTextColor() uintptr {
	return uintptr(obj.rawPtr.CallGetSelectionTextColor())
}

func (obj *textfieldImpl) SetSelectionBackgroundColor(color uintptr) {
	obj.rawPtr.CallSetSelectionBackgroundColor(uintptr(color))
}

func (obj *textfieldImpl) GetSelectionBackgroundColor() uintptr {
	return uintptr(obj.rawPtr.CallGetSelectionBackgroundColor())
}

func (obj *textfieldImpl) SetFontList(fontList string) {
	fontListStr := cefString(fontList)
	defer freeCefString(&fontListStr)
	obj.rawPtr.CallSetFontList(uintptr(unsafe.Pointer(&fontListStr)))
}

func (obj *textfieldImpl) ApplyTextColor(color uintptr, range_ uintptr) {
	obj.rawPtr.CallApplyTextColor(uintptr(color), uintptr(range_))
}

func (obj *textfieldImpl) ApplyTextStyle(style TextStyle, add int32, range_ uintptr) {
	obj.rawPtr.CallApplyTextStyle(uintptr(style), uintptr(add), uintptr(range_))
}

func (obj *textfieldImpl) IsCommandEnabled(commandID TextFieldCommands) bool {
	return obj.rawPtr.CallIsCommandEnabled(uintptr(commandID)) != 0
}

func (obj *textfieldImpl) ExecuteCommand(commandID TextFieldCommands) {
	obj.rawPtr.CallExecuteCommand(uintptr(commandID))
}

func (obj *textfieldImpl) ClearEditHistory() {
	obj.rawPtr.CallClearEditHistory()
}

func (obj *textfieldImpl) SetPlaceholderText(text string) {
	textStr := cefString(text)
	defer freeCefString(&textStr)
	obj.rawPtr.CallSetPlaceholderText(uintptr(unsafe.Pointer(&textStr)))
}

func (obj *textfieldImpl) GetPlaceholderText() string {
	return goStringUserfree(unsafe.Pointer(obj.rawPtr.CallGetPlaceholderText()))
}

func (obj *textfieldImpl) SetPlaceholderTextColor(color uintptr) {
	obj.rawPtr.CallSetPlaceholderTextColor(uintptr(color))
}

func (obj *textfieldImpl) SetAccessibleName(name string) {
	nameStr := cefString(name)
	defer freeCefString(&nameStr)
	obj.rawPtr.CallSetAccessibleName(uintptr(unsafe.Pointer(&nameStr)))
}

func (obj *textfieldImpl) rawPointer() unsafe.Pointer {
	return unsafe.Pointer(obj.rawPtr)
}

// Release releases the underlying CEF object.
func (obj *textfieldImpl) Release() {
	base := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(obj.rawPtr))
	base.CallRelease()
}

func wrapTextfield(ptr unsafe.Pointer) Textfield {
	if ptr == nil {
		return nil
	}
	r := (*raw.CEFTextfieldT)(ptr)
	base := (*raw.CEFBaseRefCountedT)(ptr)
	base.CallAddRef()
	impl := &textfieldImpl{rawPtr: r}
	runtime.SetFinalizer(impl, func(o *textfieldImpl) {
		b := (*raw.CEFBaseRefCountedT)(unsafe.Pointer(o.rawPtr))
		b.CallRelease()
	})
	return impl
}

// TextfieldCreate Create a new Textfield.
func TextfieldCreate(delegate TextfieldDelegate) uintptr {
	// TODO: marshal args, call raw.CEFTextfieldCreate(...), marshal return
	_ = raw.CEFTextfieldCreate
	return 0
}
