// Code generated by cefgen. DO NOT EDIT.

package capi

import (
	"unsafe"
)

var CEFLaunchProcess func(CommandLine unsafe.Pointer) int32

func RegisterProcessUtil(handle uintptr) {
	tryRegisterLibFunc(&CEFLaunchProcess, handle, "cef_launch_process")
}
