// Code generated by cefgen. DO NOT EDIT.

package capi

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
)

type CEFValueT struct {
	_             structs.HostLayout
	Base          CEFBaseRefCountedT
	IsValid       uintptr
	IsOwned       uintptr
	IsReadOnly    uintptr
	IsSame        uintptr
	IsEqual       uintptr
	Copy          uintptr
	GetType       uintptr
	GetBool       uintptr
	GetInt        uintptr
	GetDouble     uintptr
	GetString     uintptr
	GetBinary     uintptr
	GetDictionary uintptr
	GetList       uintptr
	SetNull       uintptr
	SetBool       uintptr
	SetInt        uintptr
	SetDouble     uintptr
	SetString     uintptr
	SetBinary     uintptr
	SetDictionary uintptr
	SetList       uintptr
}

func (v *CEFValueT) OverrideIsValid(fn uintptr) { v.IsValid = fn }

func (v *CEFValueT) CallIsValid(args ...uintptr) uintptr {
	if v.IsValid == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsValid, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideIsOwned(fn uintptr) { v.IsOwned = fn }

func (v *CEFValueT) CallIsOwned(args ...uintptr) uintptr {
	if v.IsOwned == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsOwned, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideIsReadOnly(fn uintptr) { v.IsReadOnly = fn }

func (v *CEFValueT) CallIsReadOnly(args ...uintptr) uintptr {
	if v.IsReadOnly == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsReadOnly, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideIsSame(fn uintptr) { v.IsSame = fn }

func (v *CEFValueT) CallIsSame(args ...uintptr) uintptr {
	if v.IsSame == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsSame, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideIsEqual(fn uintptr) { v.IsEqual = fn }

func (v *CEFValueT) CallIsEqual(args ...uintptr) uintptr {
	if v.IsEqual == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsEqual, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideCopy(fn uintptr) { v.Copy = fn }

func (v *CEFValueT) CallCopy(args ...uintptr) uintptr {
	if v.Copy == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.Copy, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideGetType(fn uintptr) { v.GetType = fn }

func (v *CEFValueT) CallGetType(args ...uintptr) uintptr {
	if v.GetType == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetType, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideGetBool(fn uintptr) { v.GetBool = fn }

func (v *CEFValueT) CallGetBool(args ...uintptr) uintptr {
	if v.GetBool == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetBool, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideGetInt(fn uintptr) { v.GetInt = fn }

func (v *CEFValueT) CallGetInt(args ...uintptr) uintptr {
	if v.GetInt == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetInt, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideGetDouble(fn uintptr) { v.GetDouble = fn }

func (v *CEFValueT) CallGetDouble(args ...uintptr) uintptr {
	if v.GetDouble == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetDouble, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideGetString(fn uintptr) { v.GetString = fn }

func (v *CEFValueT) CallGetString(args ...uintptr) uintptr {
	if v.GetString == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetString, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideGetBinary(fn uintptr) { v.GetBinary = fn }

func (v *CEFValueT) CallGetBinary(args ...uintptr) uintptr {
	if v.GetBinary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetBinary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideGetDictionary(fn uintptr) { v.GetDictionary = fn }

func (v *CEFValueT) CallGetDictionary(args ...uintptr) uintptr {
	if v.GetDictionary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetDictionary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideGetList(fn uintptr) { v.GetList = fn }

func (v *CEFValueT) CallGetList(args ...uintptr) uintptr {
	if v.GetList == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetList, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideSetNull(fn uintptr) { v.SetNull = fn }

func (v *CEFValueT) CallSetNull(args ...uintptr) uintptr {
	if v.SetNull == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetNull, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideSetBool(fn uintptr) { v.SetBool = fn }

func (v *CEFValueT) CallSetBool(args ...uintptr) uintptr {
	if v.SetBool == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetBool, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideSetInt(fn uintptr) { v.SetInt = fn }

func (v *CEFValueT) CallSetInt(args ...uintptr) uintptr {
	if v.SetInt == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetInt, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideSetDouble(fn uintptr) { v.SetDouble = fn }

func (v *CEFValueT) CallSetDouble(args ...uintptr) uintptr {
	if v.SetDouble == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetDouble, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideSetString(fn uintptr) { v.SetString = fn }

func (v *CEFValueT) CallSetString(args ...uintptr) uintptr {
	if v.SetString == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetString, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideSetBinary(fn uintptr) { v.SetBinary = fn }

func (v *CEFValueT) CallSetBinary(args ...uintptr) uintptr {
	if v.SetBinary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetBinary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideSetDictionary(fn uintptr) { v.SetDictionary = fn }

func (v *CEFValueT) CallSetDictionary(args ...uintptr) uintptr {
	if v.SetDictionary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetDictionary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFValueT) OverrideSetList(fn uintptr) { v.SetList = fn }

func (v *CEFValueT) CallSetList(args ...uintptr) uintptr {
	if v.SetList == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetList, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

type CEFBinaryValueT struct {
	_          structs.HostLayout
	Base       CEFBaseRefCountedT
	IsValid    uintptr
	IsOwned    uintptr
	IsSame     uintptr
	IsEqual    uintptr
	Copy       uintptr
	GetRawData uintptr
	GetSize    uintptr
	GetData    uintptr
}

func (v *CEFBinaryValueT) OverrideIsValid(fn uintptr) { v.IsValid = fn }

func (v *CEFBinaryValueT) CallIsValid(args ...uintptr) uintptr {
	if v.IsValid == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsValid, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBinaryValueT) OverrideIsOwned(fn uintptr) { v.IsOwned = fn }

func (v *CEFBinaryValueT) CallIsOwned(args ...uintptr) uintptr {
	if v.IsOwned == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsOwned, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBinaryValueT) OverrideIsSame(fn uintptr) { v.IsSame = fn }

func (v *CEFBinaryValueT) CallIsSame(args ...uintptr) uintptr {
	if v.IsSame == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsSame, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBinaryValueT) OverrideIsEqual(fn uintptr) { v.IsEqual = fn }

func (v *CEFBinaryValueT) CallIsEqual(args ...uintptr) uintptr {
	if v.IsEqual == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsEqual, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBinaryValueT) OverrideCopy(fn uintptr) { v.Copy = fn }

func (v *CEFBinaryValueT) CallCopy(args ...uintptr) uintptr {
	if v.Copy == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.Copy, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBinaryValueT) OverrideGetRawData(fn uintptr) { v.GetRawData = fn }

func (v *CEFBinaryValueT) CallGetRawData(args ...uintptr) uintptr {
	if v.GetRawData == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetRawData, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBinaryValueT) OverrideGetSize(fn uintptr) { v.GetSize = fn }

func (v *CEFBinaryValueT) CallGetSize(args ...uintptr) uintptr {
	if v.GetSize == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetSize, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBinaryValueT) OverrideGetData(fn uintptr) { v.GetData = fn }

func (v *CEFBinaryValueT) CallGetData(args ...uintptr) uintptr {
	if v.GetData == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetData, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

type CEFDictionaryValueT struct {
	_             structs.HostLayout
	Base          CEFBaseRefCountedT
	IsValid       uintptr
	IsOwned       uintptr
	IsReadOnly    uintptr
	IsSame        uintptr
	IsEqual       uintptr
	Copy          uintptr
	GetSize       uintptr
	Clear         uintptr
	HasKey        uintptr
	GetKeys       uintptr
	Remove        uintptr
	GetType       uintptr
	GetValue      uintptr
	GetBool       uintptr
	GetInt        uintptr
	GetDouble     uintptr
	GetString     uintptr
	GetBinary     uintptr
	GetDictionary uintptr
	GetList       uintptr
	SetValue      uintptr
	SetNull       uintptr
	SetBool       uintptr
	SetInt        uintptr
	SetDouble     uintptr
	SetString     uintptr
	SetBinary     uintptr
	SetDictionary uintptr
	SetList       uintptr
}

func (v *CEFDictionaryValueT) OverrideIsValid(fn uintptr) { v.IsValid = fn }

func (v *CEFDictionaryValueT) CallIsValid(args ...uintptr) uintptr {
	if v.IsValid == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsValid, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideIsOwned(fn uintptr) { v.IsOwned = fn }

func (v *CEFDictionaryValueT) CallIsOwned(args ...uintptr) uintptr {
	if v.IsOwned == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsOwned, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideIsReadOnly(fn uintptr) { v.IsReadOnly = fn }

func (v *CEFDictionaryValueT) CallIsReadOnly(args ...uintptr) uintptr {
	if v.IsReadOnly == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsReadOnly, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideIsSame(fn uintptr) { v.IsSame = fn }

func (v *CEFDictionaryValueT) CallIsSame(args ...uintptr) uintptr {
	if v.IsSame == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsSame, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideIsEqual(fn uintptr) { v.IsEqual = fn }

func (v *CEFDictionaryValueT) CallIsEqual(args ...uintptr) uintptr {
	if v.IsEqual == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsEqual, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideCopy(fn uintptr) { v.Copy = fn }

func (v *CEFDictionaryValueT) CallCopy(args ...uintptr) uintptr {
	if v.Copy == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.Copy, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideGetSize(fn uintptr) { v.GetSize = fn }

func (v *CEFDictionaryValueT) CallGetSize(args ...uintptr) uintptr {
	if v.GetSize == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetSize, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideClear(fn uintptr) { v.Clear = fn }

func (v *CEFDictionaryValueT) CallClear(args ...uintptr) uintptr {
	if v.Clear == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.Clear, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideHasKey(fn uintptr) { v.HasKey = fn }

func (v *CEFDictionaryValueT) CallHasKey(args ...uintptr) uintptr {
	if v.HasKey == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.HasKey, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideGetKeys(fn uintptr) { v.GetKeys = fn }

func (v *CEFDictionaryValueT) CallGetKeys(args ...uintptr) uintptr {
	if v.GetKeys == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetKeys, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideRemove(fn uintptr) { v.Remove = fn }

func (v *CEFDictionaryValueT) CallRemove(args ...uintptr) uintptr {
	if v.Remove == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.Remove, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideGetType(fn uintptr) { v.GetType = fn }

func (v *CEFDictionaryValueT) CallGetType(args ...uintptr) uintptr {
	if v.GetType == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetType, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideGetValue(fn uintptr) { v.GetValue = fn }

func (v *CEFDictionaryValueT) CallGetValue(args ...uintptr) uintptr {
	if v.GetValue == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetValue, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideGetBool(fn uintptr) { v.GetBool = fn }

func (v *CEFDictionaryValueT) CallGetBool(args ...uintptr) uintptr {
	if v.GetBool == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetBool, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideGetInt(fn uintptr) { v.GetInt = fn }

func (v *CEFDictionaryValueT) CallGetInt(args ...uintptr) uintptr {
	if v.GetInt == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetInt, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideGetDouble(fn uintptr) { v.GetDouble = fn }

func (v *CEFDictionaryValueT) CallGetDouble(args ...uintptr) uintptr {
	if v.GetDouble == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetDouble, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideGetString(fn uintptr) { v.GetString = fn }

func (v *CEFDictionaryValueT) CallGetString(args ...uintptr) uintptr {
	if v.GetString == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetString, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideGetBinary(fn uintptr) { v.GetBinary = fn }

func (v *CEFDictionaryValueT) CallGetBinary(args ...uintptr) uintptr {
	if v.GetBinary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetBinary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideGetDictionary(fn uintptr) { v.GetDictionary = fn }

func (v *CEFDictionaryValueT) CallGetDictionary(args ...uintptr) uintptr {
	if v.GetDictionary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetDictionary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideGetList(fn uintptr) { v.GetList = fn }

func (v *CEFDictionaryValueT) CallGetList(args ...uintptr) uintptr {
	if v.GetList == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetList, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideSetValue(fn uintptr) { v.SetValue = fn }

func (v *CEFDictionaryValueT) CallSetValue(args ...uintptr) uintptr {
	if v.SetValue == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetValue, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideSetNull(fn uintptr) { v.SetNull = fn }

func (v *CEFDictionaryValueT) CallSetNull(args ...uintptr) uintptr {
	if v.SetNull == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetNull, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideSetBool(fn uintptr) { v.SetBool = fn }

func (v *CEFDictionaryValueT) CallSetBool(args ...uintptr) uintptr {
	if v.SetBool == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetBool, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideSetInt(fn uintptr) { v.SetInt = fn }

func (v *CEFDictionaryValueT) CallSetInt(args ...uintptr) uintptr {
	if v.SetInt == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetInt, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideSetDouble(fn uintptr) { v.SetDouble = fn }

func (v *CEFDictionaryValueT) CallSetDouble(args ...uintptr) uintptr {
	if v.SetDouble == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetDouble, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideSetString(fn uintptr) { v.SetString = fn }

func (v *CEFDictionaryValueT) CallSetString(args ...uintptr) uintptr {
	if v.SetString == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetString, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideSetBinary(fn uintptr) { v.SetBinary = fn }

func (v *CEFDictionaryValueT) CallSetBinary(args ...uintptr) uintptr {
	if v.SetBinary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetBinary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideSetDictionary(fn uintptr) { v.SetDictionary = fn }

func (v *CEFDictionaryValueT) CallSetDictionary(args ...uintptr) uintptr {
	if v.SetDictionary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetDictionary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFDictionaryValueT) OverrideSetList(fn uintptr) { v.SetList = fn }

func (v *CEFDictionaryValueT) CallSetList(args ...uintptr) uintptr {
	if v.SetList == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetList, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

type CEFListValueT struct {
	_             structs.HostLayout
	Base          CEFBaseRefCountedT
	IsValid       uintptr
	IsOwned       uintptr
	IsReadOnly    uintptr
	IsSame        uintptr
	IsEqual       uintptr
	Copy          uintptr
	SetSize       uintptr
	GetSize       uintptr
	Clear         uintptr
	Remove        uintptr
	GetType       uintptr
	GetValue      uintptr
	GetBool       uintptr
	GetInt        uintptr
	GetDouble     uintptr
	GetString     uintptr
	GetBinary     uintptr
	GetDictionary uintptr
	GetList       uintptr
	SetValue      uintptr
	SetNull       uintptr
	SetBool       uintptr
	SetInt        uintptr
	SetDouble     uintptr
	SetString     uintptr
	SetBinary     uintptr
	SetDictionary uintptr
	SetList       uintptr
}

func (v *CEFListValueT) OverrideIsValid(fn uintptr) { v.IsValid = fn }

func (v *CEFListValueT) CallIsValid(args ...uintptr) uintptr {
	if v.IsValid == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsValid, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideIsOwned(fn uintptr) { v.IsOwned = fn }

func (v *CEFListValueT) CallIsOwned(args ...uintptr) uintptr {
	if v.IsOwned == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsOwned, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideIsReadOnly(fn uintptr) { v.IsReadOnly = fn }

func (v *CEFListValueT) CallIsReadOnly(args ...uintptr) uintptr {
	if v.IsReadOnly == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsReadOnly, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideIsSame(fn uintptr) { v.IsSame = fn }

func (v *CEFListValueT) CallIsSame(args ...uintptr) uintptr {
	if v.IsSame == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsSame, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideIsEqual(fn uintptr) { v.IsEqual = fn }

func (v *CEFListValueT) CallIsEqual(args ...uintptr) uintptr {
	if v.IsEqual == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsEqual, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideCopy(fn uintptr) { v.Copy = fn }

func (v *CEFListValueT) CallCopy(args ...uintptr) uintptr {
	if v.Copy == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.Copy, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideSetSize(fn uintptr) { v.SetSize = fn }

func (v *CEFListValueT) CallSetSize(args ...uintptr) uintptr {
	if v.SetSize == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetSize, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideGetSize(fn uintptr) { v.GetSize = fn }

func (v *CEFListValueT) CallGetSize(args ...uintptr) uintptr {
	if v.GetSize == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetSize, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideClear(fn uintptr) { v.Clear = fn }

func (v *CEFListValueT) CallClear(args ...uintptr) uintptr {
	if v.Clear == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.Clear, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideRemove(fn uintptr) { v.Remove = fn }

func (v *CEFListValueT) CallRemove(args ...uintptr) uintptr {
	if v.Remove == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.Remove, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideGetType(fn uintptr) { v.GetType = fn }

func (v *CEFListValueT) CallGetType(args ...uintptr) uintptr {
	if v.GetType == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetType, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideGetValue(fn uintptr) { v.GetValue = fn }

func (v *CEFListValueT) CallGetValue(args ...uintptr) uintptr {
	if v.GetValue == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetValue, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideGetBool(fn uintptr) { v.GetBool = fn }

func (v *CEFListValueT) CallGetBool(args ...uintptr) uintptr {
	if v.GetBool == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetBool, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideGetInt(fn uintptr) { v.GetInt = fn }

func (v *CEFListValueT) CallGetInt(args ...uintptr) uintptr {
	if v.GetInt == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetInt, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideGetDouble(fn uintptr) { v.GetDouble = fn }

func (v *CEFListValueT) CallGetDouble(args ...uintptr) uintptr {
	if v.GetDouble == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetDouble, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideGetString(fn uintptr) { v.GetString = fn }

func (v *CEFListValueT) CallGetString(args ...uintptr) uintptr {
	if v.GetString == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetString, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideGetBinary(fn uintptr) { v.GetBinary = fn }

func (v *CEFListValueT) CallGetBinary(args ...uintptr) uintptr {
	if v.GetBinary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetBinary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideGetDictionary(fn uintptr) { v.GetDictionary = fn }

func (v *CEFListValueT) CallGetDictionary(args ...uintptr) uintptr {
	if v.GetDictionary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetDictionary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideGetList(fn uintptr) { v.GetList = fn }

func (v *CEFListValueT) CallGetList(args ...uintptr) uintptr {
	if v.GetList == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetList, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideSetValue(fn uintptr) { v.SetValue = fn }

func (v *CEFListValueT) CallSetValue(args ...uintptr) uintptr {
	if v.SetValue == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetValue, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideSetNull(fn uintptr) { v.SetNull = fn }

func (v *CEFListValueT) CallSetNull(args ...uintptr) uintptr {
	if v.SetNull == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetNull, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideSetBool(fn uintptr) { v.SetBool = fn }

func (v *CEFListValueT) CallSetBool(args ...uintptr) uintptr {
	if v.SetBool == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetBool, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideSetInt(fn uintptr) { v.SetInt = fn }

func (v *CEFListValueT) CallSetInt(args ...uintptr) uintptr {
	if v.SetInt == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetInt, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideSetDouble(fn uintptr) { v.SetDouble = fn }

func (v *CEFListValueT) CallSetDouble(args ...uintptr) uintptr {
	if v.SetDouble == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetDouble, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideSetString(fn uintptr) { v.SetString = fn }

func (v *CEFListValueT) CallSetString(args ...uintptr) uintptr {
	if v.SetString == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetString, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideSetBinary(fn uintptr) { v.SetBinary = fn }

func (v *CEFListValueT) CallSetBinary(args ...uintptr) uintptr {
	if v.SetBinary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetBinary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideSetDictionary(fn uintptr) { v.SetDictionary = fn }

func (v *CEFListValueT) CallSetDictionary(args ...uintptr) uintptr {
	if v.SetDictionary == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetDictionary, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFListValueT) OverrideSetList(fn uintptr) { v.SetList = fn }

func (v *CEFListValueT) CallSetList(args ...uintptr) uintptr {
	if v.SetList == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetList, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

var CEFValueCreate func() unsafe.Pointer

var CEFBinaryValueCreate func(Data unsafe.Pointer, DataSize uintptr) unsafe.Pointer

var CEFDictionaryValueCreate func() unsafe.Pointer

var CEFListValueCreate func() unsafe.Pointer

func RegisterValues(handle uintptr) {
	tryRegisterLibFunc(&CEFValueCreate, handle, "cef_value_create")
	tryRegisterLibFunc(&CEFBinaryValueCreate, handle, "cef_binary_value_create")
	tryRegisterLibFunc(&CEFDictionaryValueCreate, handle, "cef_dictionary_value_create")
	tryRegisterLibFunc(&CEFListValueCreate, handle, "cef_list_value_create")
}
