// Code generated by cefgen. DO NOT EDIT.

package capi

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
)

type CEFReadHandlerT struct {
	_        structs.HostLayout
	Base     CEFBaseRefCountedT
	Read     uintptr
	Seek     uintptr
	Tell     uintptr
	Eof      uintptr
	MayBlock uintptr
}

func (v *CEFReadHandlerT) OverrideRead(fn uintptr) { v.Read = fn }

func (v *CEFReadHandlerT) CallRead(Ptr unsafe.Pointer, Size uintptr, N uintptr) uintptr {
	if v.Read == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Read, uintptr(unsafe.Pointer(v)), uintptr(Ptr), Size, N)
	return r1
}

func (v *CEFReadHandlerT) OverrideSeek(fn uintptr) { v.Seek = fn }

func (v *CEFReadHandlerT) CallSeek(Offset uintptr, Whence uintptr) uintptr {
	if v.Seek == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Seek, uintptr(unsafe.Pointer(v)), Offset, Whence)
	return r1
}

func (v *CEFReadHandlerT) OverrideTell(fn uintptr) { v.Tell = fn }

func (v *CEFReadHandlerT) CallTell() uintptr {
	if v.Tell == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Tell, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFReadHandlerT) OverrideEof(fn uintptr) { v.Eof = fn }

func (v *CEFReadHandlerT) CallEof() uintptr {
	if v.Eof == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Eof, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFReadHandlerT) OverrideMayBlock(fn uintptr) { v.MayBlock = fn }

func (v *CEFReadHandlerT) CallMayBlock() uintptr {
	if v.MayBlock == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.MayBlock, uintptr(unsafe.Pointer(v)))
	return r1
}

type CEFStreamReaderT struct {
	_        structs.HostLayout
	Base     CEFBaseRefCountedT
	Read     uintptr
	Seek     uintptr
	Tell     uintptr
	Eof      uintptr
	MayBlock uintptr
}

func (v *CEFStreamReaderT) OverrideRead(fn uintptr) { v.Read = fn }

func (v *CEFStreamReaderT) CallRead(Ptr unsafe.Pointer, Size uintptr, N uintptr) uintptr {
	if v.Read == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Read, uintptr(unsafe.Pointer(v)), uintptr(Ptr), Size, N)
	return r1
}

func (v *CEFStreamReaderT) OverrideSeek(fn uintptr) { v.Seek = fn }

func (v *CEFStreamReaderT) CallSeek(Offset uintptr, Whence uintptr) uintptr {
	if v.Seek == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Seek, uintptr(unsafe.Pointer(v)), Offset, Whence)
	return r1
}

func (v *CEFStreamReaderT) OverrideTell(fn uintptr) { v.Tell = fn }

func (v *CEFStreamReaderT) CallTell() uintptr {
	if v.Tell == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Tell, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFStreamReaderT) OverrideEof(fn uintptr) { v.Eof = fn }

func (v *CEFStreamReaderT) CallEof() uintptr {
	if v.Eof == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Eof, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFStreamReaderT) OverrideMayBlock(fn uintptr) { v.MayBlock = fn }

func (v *CEFStreamReaderT) CallMayBlock() uintptr {
	if v.MayBlock == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.MayBlock, uintptr(unsafe.Pointer(v)))
	return r1
}

type CEFWriteHandlerT struct {
	_        structs.HostLayout
	Base     CEFBaseRefCountedT
	Write    uintptr
	Seek     uintptr
	Tell     uintptr
	Flush    uintptr
	MayBlock uintptr
}

func (v *CEFWriteHandlerT) OverrideWrite(fn uintptr) { v.Write = fn }

func (v *CEFWriteHandlerT) CallWrite(Ptr unsafe.Pointer, Size uintptr, N uintptr) uintptr {
	if v.Write == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Write, uintptr(unsafe.Pointer(v)), uintptr(Ptr), Size, N)
	return r1
}

func (v *CEFWriteHandlerT) OverrideSeek(fn uintptr) { v.Seek = fn }

func (v *CEFWriteHandlerT) CallSeek(Offset uintptr, Whence uintptr) uintptr {
	if v.Seek == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Seek, uintptr(unsafe.Pointer(v)), Offset, Whence)
	return r1
}

func (v *CEFWriteHandlerT) OverrideTell(fn uintptr) { v.Tell = fn }

func (v *CEFWriteHandlerT) CallTell() uintptr {
	if v.Tell == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Tell, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFWriteHandlerT) OverrideFlush(fn uintptr) { v.Flush = fn }

func (v *CEFWriteHandlerT) CallFlush() uintptr {
	if v.Flush == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Flush, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFWriteHandlerT) OverrideMayBlock(fn uintptr) { v.MayBlock = fn }

func (v *CEFWriteHandlerT) CallMayBlock() uintptr {
	if v.MayBlock == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.MayBlock, uintptr(unsafe.Pointer(v)))
	return r1
}

type CEFStreamWriterT struct {
	_        structs.HostLayout
	Base     CEFBaseRefCountedT
	Write    uintptr
	Seek     uintptr
	Tell     uintptr
	Flush    uintptr
	MayBlock uintptr
}

func (v *CEFStreamWriterT) OverrideWrite(fn uintptr) { v.Write = fn }

func (v *CEFStreamWriterT) CallWrite(Ptr unsafe.Pointer, Size uintptr, N uintptr) uintptr {
	if v.Write == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Write, uintptr(unsafe.Pointer(v)), uintptr(Ptr), Size, N)
	return r1
}

func (v *CEFStreamWriterT) OverrideSeek(fn uintptr) { v.Seek = fn }

func (v *CEFStreamWriterT) CallSeek(Offset uintptr, Whence uintptr) uintptr {
	if v.Seek == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Seek, uintptr(unsafe.Pointer(v)), Offset, Whence)
	return r1
}

func (v *CEFStreamWriterT) OverrideTell(fn uintptr) { v.Tell = fn }

func (v *CEFStreamWriterT) CallTell() uintptr {
	if v.Tell == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Tell, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFStreamWriterT) OverrideFlush(fn uintptr) { v.Flush = fn }

func (v *CEFStreamWriterT) CallFlush() uintptr {
	if v.Flush == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.Flush, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFStreamWriterT) OverrideMayBlock(fn uintptr) { v.MayBlock = fn }

func (v *CEFStreamWriterT) CallMayBlock() uintptr {
	if v.MayBlock == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.MayBlock, uintptr(unsafe.Pointer(v)))
	return r1
}

var CEFStreamReaderCreateForFile func(Filename unsafe.Pointer) unsafe.Pointer

var CEFStreamReaderCreateForData func(Data unsafe.Pointer, Size uintptr) unsafe.Pointer

var CEFStreamReaderCreateForHandler func(Handler unsafe.Pointer) unsafe.Pointer

var CEFStreamWriterCreateForFile func(Filename unsafe.Pointer) unsafe.Pointer

var CEFStreamWriterCreateForHandler func(Handler unsafe.Pointer) unsafe.Pointer

func RegisterStream(handle uintptr) {
	tryRegisterLibFunc(&CEFStreamReaderCreateForFile, handle, "cef_stream_reader_create_for_file")
	tryRegisterLibFunc(&CEFStreamReaderCreateForData, handle, "cef_stream_reader_create_for_data")
	tryRegisterLibFunc(&CEFStreamReaderCreateForHandler, handle, "cef_stream_reader_create_for_handler")
	tryRegisterLibFunc(&CEFStreamWriterCreateForFile, handle, "cef_stream_writer_create_for_file")
	tryRegisterLibFunc(&CEFStreamWriterCreateForHandler, handle, "cef_stream_writer_create_for_handler")
}
