// Code generated by cefgen. DO NOT EDIT.

package capi

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
)

type CEFEndTracingCallbackT struct {
	_                    structs.HostLayout
	Base                 CEFBaseRefCountedT
	OnEndTracingComplete uintptr
}

func (v *CEFEndTracingCallbackT) OverrideOnEndTracingComplete(fn uintptr) {
	v.OnEndTracingComplete = fn
}

func (v *CEFEndTracingCallbackT) CallOnEndTracingComplete(TracingFile unsafe.Pointer) uintptr {
	if v.OnEndTracingComplete == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.OnEndTracingComplete, uintptr(unsafe.Pointer(v)), uintptr(TracingFile))
	return r1
}

var CEFBeginTracing func(Categories unsafe.Pointer, Callback unsafe.Pointer) int32

var CEFEndTracing func(TracingFile unsafe.Pointer, Callback unsafe.Pointer) int32

var CEFNowFromSystemTraceTime func() int64

func RegisterTrace(handle uintptr) {
	tryRegisterLibFunc(&CEFBeginTracing, handle, "cef_begin_tracing")
	tryRegisterLibFunc(&CEFEndTracing, handle, "cef_end_tracing")
	tryRegisterLibFunc(&CEFNowFromSystemTraceTime, handle, "cef_now_from_system_trace_time")
}
