// Code generated by cefgen. DO NOT EDIT.

package capi

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
)

type CEFSslstatusT struct {
	_                  structs.HostLayout
	Base               CEFBaseRefCountedT
	IsSecureConnection uintptr
	GetCertStatus      uintptr
	GetSslversion      uintptr
	GetContentStatus   uintptr
	GetX509Certificate uintptr
}

func (v *CEFSslstatusT) OverrideIsSecureConnection(fn uintptr) { v.IsSecureConnection = fn }

func (v *CEFSslstatusT) CallIsSecureConnection(args ...uintptr) uintptr {
	if v.IsSecureConnection == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.IsSecureConnection, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFSslstatusT) OverrideGetCertStatus(fn uintptr) { v.GetCertStatus = fn }

func (v *CEFSslstatusT) CallGetCertStatus(args ...uintptr) uintptr {
	if v.GetCertStatus == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetCertStatus, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFSslstatusT) OverrideGetSslversion(fn uintptr) { v.GetSslversion = fn }

func (v *CEFSslstatusT) CallGetSslversion(args ...uintptr) uintptr {
	if v.GetSslversion == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetSslversion, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFSslstatusT) OverrideGetContentStatus(fn uintptr) { v.GetContentStatus = fn }

func (v *CEFSslstatusT) CallGetContentStatus(args ...uintptr) uintptr {
	if v.GetContentStatus == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetContentStatus, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFSslstatusT) OverrideGetX509Certificate(fn uintptr) { v.GetX509Certificate = fn }

func (v *CEFSslstatusT) CallGetX509Certificate(args ...uintptr) uintptr {
	if v.GetX509Certificate == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetX509Certificate, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func RegisterSslStatus(_ uintptr) {}
