// Code generated by cefgen. DO NOT EDIT.

package capi

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
)

type CEFLabelButtonT struct {
	_                      structs.HostLayout
	Base                   CEFButtonT
	AsMenuButton           uintptr
	SetText                uintptr
	GetText                uintptr
	SetImage               uintptr
	GetImage               uintptr
	SetTextColor           uintptr
	SetEnabledTextColors   uintptr
	SetFontList            uintptr
	SetHorizontalAlignment uintptr
	SetMinimumSize         uintptr
	SetMaximumSize         uintptr
}

func (v *CEFLabelButtonT) OverrideAsMenuButton(fn uintptr) { v.AsMenuButton = fn }

func (v *CEFLabelButtonT) CallAsMenuButton(args ...uintptr) uintptr {
	if v.AsMenuButton == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.AsMenuButton, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFLabelButtonT) OverrideSetText(fn uintptr) { v.SetText = fn }

func (v *CEFLabelButtonT) CallSetText(args ...uintptr) uintptr {
	if v.SetText == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetText, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFLabelButtonT) OverrideGetText(fn uintptr) { v.GetText = fn }

func (v *CEFLabelButtonT) CallGetText(args ...uintptr) uintptr {
	if v.GetText == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetText, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFLabelButtonT) OverrideSetImage(fn uintptr) { v.SetImage = fn }

func (v *CEFLabelButtonT) CallSetImage(args ...uintptr) uintptr {
	if v.SetImage == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetImage, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFLabelButtonT) OverrideGetImage(fn uintptr) { v.GetImage = fn }

func (v *CEFLabelButtonT) CallGetImage(args ...uintptr) uintptr {
	if v.GetImage == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetImage, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFLabelButtonT) OverrideSetTextColor(fn uintptr) { v.SetTextColor = fn }

func (v *CEFLabelButtonT) CallSetTextColor(args ...uintptr) uintptr {
	if v.SetTextColor == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetTextColor, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFLabelButtonT) OverrideSetEnabledTextColors(fn uintptr) { v.SetEnabledTextColors = fn }

func (v *CEFLabelButtonT) CallSetEnabledTextColors(args ...uintptr) uintptr {
	if v.SetEnabledTextColors == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetEnabledTextColors, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFLabelButtonT) OverrideSetFontList(fn uintptr) { v.SetFontList = fn }

func (v *CEFLabelButtonT) CallSetFontList(args ...uintptr) uintptr {
	if v.SetFontList == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetFontList, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFLabelButtonT) OverrideSetHorizontalAlignment(fn uintptr) { v.SetHorizontalAlignment = fn }

func (v *CEFLabelButtonT) CallSetHorizontalAlignment(args ...uintptr) uintptr {
	if v.SetHorizontalAlignment == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetHorizontalAlignment, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFLabelButtonT) OverrideSetMinimumSize(fn uintptr) { v.SetMinimumSize = fn }

func (v *CEFLabelButtonT) CallSetMinimumSize(args ...uintptr) uintptr {
	if v.SetMinimumSize == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetMinimumSize, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFLabelButtonT) OverrideSetMaximumSize(fn uintptr) { v.SetMaximumSize = fn }

func (v *CEFLabelButtonT) CallSetMaximumSize(args ...uintptr) uintptr {
	if v.SetMaximumSize == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.SetMaximumSize, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

var CEFLabelButtonCreate func(Delegate unsafe.Pointer, Text unsafe.Pointer) unsafe.Pointer

func RegisterLabelButton(handle uintptr) {
	tryRegisterLibFunc(&CEFLabelButtonCreate, handle, "cef_label_button_create")
}
