// Code generated by cefgen. DO NOT EDIT.

package capi

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
)

type CEFButtonDelegateT struct {
	_                    structs.HostLayout
	Base                 CEFViewDelegateT
	OnButtonPressed      uintptr
	OnButtonStateChanged uintptr
}

func (v *CEFButtonDelegateT) OverrideOnButtonPressed(fn uintptr) { v.OnButtonPressed = fn }

func (v *CEFButtonDelegateT) CallOnButtonPressed(Button unsafe.Pointer) uintptr {
	if v.OnButtonPressed == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.OnButtonPressed, uintptr(unsafe.Pointer(v)), uintptr(Button))
	return r1
}

func (v *CEFButtonDelegateT) OverrideOnButtonStateChanged(fn uintptr) { v.OnButtonStateChanged = fn }

func (v *CEFButtonDelegateT) CallOnButtonStateChanged(Button unsafe.Pointer) uintptr {
	if v.OnButtonStateChanged == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.OnButtonStateChanged, uintptr(unsafe.Pointer(v)), uintptr(Button))
	return r1
}

func RegisterButtonDelegate(_ uintptr) {}
