// Code generated by cefgen. DO NOT EDIT.

package capi

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
)

type CEFButtonT struct {
	_                 structs.HostLayout
	Base              CEFViewT
	AsLabelButton     uintptr
	SetState          uintptr
	GetState          uintptr
	SetInkDropEnabled uintptr
	SetTooltipText    uintptr
	SetAccessibleName uintptr
}

func (v *CEFButtonT) OverrideAsLabelButton(fn uintptr) { v.AsLabelButton = fn }

func (v *CEFButtonT) CallAsLabelButton() uintptr {
	if v.AsLabelButton == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.AsLabelButton, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFButtonT) OverrideSetState(fn uintptr) { v.SetState = fn }

func (v *CEFButtonT) CallSetState(State uintptr) uintptr {
	if v.SetState == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.SetState, uintptr(unsafe.Pointer(v)), State)
	return r1
}

func (v *CEFButtonT) OverrideGetState(fn uintptr) { v.GetState = fn }

func (v *CEFButtonT) CallGetState() uintptr {
	if v.GetState == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.GetState, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFButtonT) OverrideSetInkDropEnabled(fn uintptr) { v.SetInkDropEnabled = fn }

func (v *CEFButtonT) CallSetInkDropEnabled(Enabled uintptr) uintptr {
	if v.SetInkDropEnabled == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.SetInkDropEnabled, uintptr(unsafe.Pointer(v)), Enabled)
	return r1
}

func (v *CEFButtonT) OverrideSetTooltipText(fn uintptr) { v.SetTooltipText = fn }

func (v *CEFButtonT) CallSetTooltipText(TooltipText unsafe.Pointer) uintptr {
	if v.SetTooltipText == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.SetTooltipText, uintptr(unsafe.Pointer(v)), uintptr(TooltipText))
	return r1
}

func (v *CEFButtonT) OverrideSetAccessibleName(fn uintptr) { v.SetAccessibleName = fn }

func (v *CEFButtonT) CallSetAccessibleName(Name unsafe.Pointer) uintptr {
	if v.SetAccessibleName == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.SetAccessibleName, uintptr(unsafe.Pointer(v)), uintptr(Name))
	return r1
}

func RegisterButton(_ uintptr) {}
