// Code generated by cefgen. DO NOT EDIT.

package capi

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
)

type CEFBrowserViewDelegateT struct {
	_                                          structs.HostLayout
	Base                                       CEFViewDelegateT
	OnBrowserCreated                           uintptr
	OnBrowserDestroyed                         uintptr
	GetDelegateForPopupBrowserView             uintptr
	OnPopupBrowserViewCreated                  uintptr
	GetChromeToolbarType                       uintptr
	UseFramelessWindowForPictureInPicture      uintptr
	OnGestureCommand                           uintptr
	GetBrowserRuntimeStyle                     uintptr
	AllowMoveForPictureInPicture               uintptr
	AllowPictureInPictureWithoutUserActivation uintptr
}

func (v *CEFBrowserViewDelegateT) OverrideOnBrowserCreated(fn uintptr) { v.OnBrowserCreated = fn }

func (v *CEFBrowserViewDelegateT) CallOnBrowserCreated(args ...uintptr) uintptr {
	if v.OnBrowserCreated == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.OnBrowserCreated, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBrowserViewDelegateT) OverrideOnBrowserDestroyed(fn uintptr) { v.OnBrowserDestroyed = fn }

func (v *CEFBrowserViewDelegateT) CallOnBrowserDestroyed(args ...uintptr) uintptr {
	if v.OnBrowserDestroyed == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.OnBrowserDestroyed, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBrowserViewDelegateT) OverrideGetDelegateForPopupBrowserView(fn uintptr) {
	v.GetDelegateForPopupBrowserView = fn
}

func (v *CEFBrowserViewDelegateT) CallGetDelegateForPopupBrowserView(args ...uintptr) uintptr {
	if v.GetDelegateForPopupBrowserView == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetDelegateForPopupBrowserView, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBrowserViewDelegateT) OverrideOnPopupBrowserViewCreated(fn uintptr) {
	v.OnPopupBrowserViewCreated = fn
}

func (v *CEFBrowserViewDelegateT) CallOnPopupBrowserViewCreated(args ...uintptr) uintptr {
	if v.OnPopupBrowserViewCreated == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.OnPopupBrowserViewCreated, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBrowserViewDelegateT) OverrideGetChromeToolbarType(fn uintptr) {
	v.GetChromeToolbarType = fn
}

func (v *CEFBrowserViewDelegateT) CallGetChromeToolbarType(args ...uintptr) uintptr {
	if v.GetChromeToolbarType == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetChromeToolbarType, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBrowserViewDelegateT) OverrideUseFramelessWindowForPictureInPicture(fn uintptr) {
	v.UseFramelessWindowForPictureInPicture = fn
}

func (v *CEFBrowserViewDelegateT) CallUseFramelessWindowForPictureInPicture(args ...uintptr) uintptr {
	if v.UseFramelessWindowForPictureInPicture == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.UseFramelessWindowForPictureInPicture, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBrowserViewDelegateT) OverrideOnGestureCommand(fn uintptr) { v.OnGestureCommand = fn }

func (v *CEFBrowserViewDelegateT) CallOnGestureCommand(args ...uintptr) uintptr {
	if v.OnGestureCommand == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.OnGestureCommand, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBrowserViewDelegateT) OverrideGetBrowserRuntimeStyle(fn uintptr) {
	v.GetBrowserRuntimeStyle = fn
}

func (v *CEFBrowserViewDelegateT) CallGetBrowserRuntimeStyle(args ...uintptr) uintptr {
	if v.GetBrowserRuntimeStyle == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.GetBrowserRuntimeStyle, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBrowserViewDelegateT) OverrideAllowMoveForPictureInPicture(fn uintptr) {
	v.AllowMoveForPictureInPicture = fn
}

func (v *CEFBrowserViewDelegateT) CallAllowMoveForPictureInPicture(args ...uintptr) uintptr {
	if v.AllowMoveForPictureInPicture == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.AllowMoveForPictureInPicture, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func (v *CEFBrowserViewDelegateT) OverrideAllowPictureInPictureWithoutUserActivation(fn uintptr) {
	v.AllowPictureInPictureWithoutUserActivation = fn
}

func (v *CEFBrowserViewDelegateT) CallAllowPictureInPictureWithoutUserActivation(args ...uintptr) uintptr {
	if v.AllowPictureInPictureWithoutUserActivation == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallN(v.AllowPictureInPictureWithoutUserActivation, append([]uintptr{uintptr(unsafe.Pointer(v))}, args...)...)
	return r1
}

func RegisterBrowserViewDelegate(_ uintptr) {}
