// Code generated by cefgen. DO NOT EDIT.

package capi

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
)

type CEFLayoutT struct {
	_            structs.HostLayout
	Base         CEFBaseRefCountedT
	AsBoxLayout  uintptr
	AsFillLayout uintptr
	IsValid      uintptr
}

func (v *CEFLayoutT) OverrideAsBoxLayout(fn uintptr) { v.AsBoxLayout = fn }

func (v *CEFLayoutT) CallAsBoxLayout() uintptr {
	if v.AsBoxLayout == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.AsBoxLayout, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFLayoutT) OverrideAsFillLayout(fn uintptr) { v.AsFillLayout = fn }

func (v *CEFLayoutT) CallAsFillLayout() uintptr {
	if v.AsFillLayout == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.AsFillLayout, uintptr(unsafe.Pointer(v)))
	return r1
}

func (v *CEFLayoutT) OverrideIsValid(fn uintptr) { v.IsValid = fn }

func (v *CEFLayoutT) CallIsValid() uintptr {
	if v.IsValid == 0 {
		return 0
	}
	r1, _, _ := purego.SyscallSelf(v.IsValid, uintptr(unsafe.Pointer(v)))
	return r1
}

func RegisterLayout(_ uintptr) {}
